// GP_Term.cpp : Defines the class behaviors for the application.
//
#include "stdafx.h"
#include "GP_Term.h"

#include "MainFrm.h"
#include "IpFrame.h"
#include "GP_TermDoc.h"
#include "GP_TermView.h"
#include "Splash.h"
#include <initguid.h>
#include "GP_Term_i.c"
#include "GPTInterface.h"
#include "AutoSizing.h"
#include "Connector.h"
#include "Scintilla\ScintillaWin.h"
#include "COMServer.h"
#include "DllServer.h"
#include "GPUnit.h"


#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

const char *m_TermVersion="G2.6.0.1";
int m_LastScanf;
GPCurrent GPC;

CCOMServer m_COMServer;
DllServer m_DllServer;

CTermCap m_TermCap;
UINT cFEtalon[16];
UINT cBEtalon[16];
GP_comm m_Comm(1);

const char *hexchars="0123456789ABCDEFabcdef";
const DWORD hexValues[]={0,1,2,3,4,5,6,7,8,9,0xA,0xB,0xC,0xD,0xE,0xF,0xa,0xb,0xc,0xd,0xe,0xf,};


DWORD m_dwReg[MAX_REGISTERROT];
CString m_dwRegStr[MAX_REGISTERROT];

#ifdef RUS
const char *ErrObjSub="ÃÂÚÓ‰ %s ‰Îˇ ‰‡ÌÌÓ„Ó Ó·˙ÂÍÚ‡ ÓÚÒÛÚÒÚ‚ÛÂÚ!";
#else
const char *ErrObjSub="Missing %s method for this object!";
#endif
// ÔÓÒÎÂ‰ÌËÈ ‰ÓÎÊÂÌ ·˚Ú¸ WS_CHILD
const char *aWndStyleName[N_WND_STYLES]={"WS_BORDER|","WS_CAPTION|","WS_CLIPCHILDREN|","WS_CLIPSIBLINGS|","WS_DISABLED|","WS_DLGFRAME|","WS_GROUP|","WS_HSCROLL|","WS_MAXIMIZE|","WS_MAXIMIZEBOX|","WS_MINIMIZE|","WS_MINIMIZEBOX|","WS_OVERLAPPED|","WS_OVERLAPPEDWINDOW|","WS_POPUP|","WS_POPUPWINDOW|","WS_SYSMENU|","WS_TABSTOP|","WS_THICKFRAME|","WS_VISIBLE|","WS_VSCROLL|","WS_CHILD|",};
const UINT  aWndStyleUINT[N_WND_STYLES]={ WS_BORDER, WS_CAPTION, WS_CLIPCHILDREN, WS_CLIPSIBLINGS, WS_DISABLED, WS_DLGFRAME, WS_GROUP, WS_HSCROLL, WS_MAXIMIZE, WS_MAXIMIZEBOX, WS_MINIMIZE, WS_MINIMIZEBOX, WS_OVERLAPPED, WS_OVERLAPPEDWINDOW, WS_POPUP, WS_POPUPWINDOW, WS_SYSMENU, WS_TABSTOP, WS_THICKFRAME, WS_VISIBLE, WS_VSCROLL, WS_CHILD,};
const UINT  aWndStyleMask[N_WND_STYLES]={ WS_BORDER, WS_CAPTION, WS_CLIPCHILDREN, WS_CLIPSIBLINGS, WS_DISABLED, WS_DLGFRAME, WS_GROUP, WS_HSCROLL, WS_MAXIMIZE, WS_MAXIMIZEBOX, WS_MINIMIZE, WS_MINIMIZEBOX, WS_POPUP, WS_OVERLAPPEDWINDOW, WS_POPUP, WS_POPUPWINDOW, WS_SYSMENU, WS_TABSTOP, WS_THICKFRAME, WS_VISIBLE, WS_VSCROLL, WS_CHILD,};

const char *aUnitCommonStyleName[N_UNITCOMMON_STYLES]={"UCS_CRAM|","UCS_CRVM|","UCS_CRSVM|",};
const UINT  aUnitCommonStyleUINT[N_UNITCOMMON_STYLES]={ UCS_CRAM,   UCS_CRVM,   UCS_CRSVM,};
const UINT  aUnitCommonStyleMask[N_UNITCOMMON_STYLES]={ UCS_CRAM,   UCS_CRVM,   UCS_CRSVM,};

const char *aWndExStyleName[N_WND_EX_STYLES]={"WS_EX_ACCEPTFILES|","WS_EX_CLIENTEDGE|","WS_EX_CONTEXTHELP|","WS_EX_CONTROLPARENT|","WS_EX_DLGMODALFRAME|","WS_EX_LEFT|","WS_EX_LEFTSCROLLBAR|","WS_EX_LTRREADING|","WS_EX_MDICHILD|","WS_EX_NOPARENTNOTIFY|","WS_EX_OVERLAPPEDWINDOW|","WS_EX_PALETTEWINDOW|","WS_EX_RIGHT|","WS_EX_RIGHTSCROLLBAR|","WS_EX_RTLREADING|","WS_EX_STATICEDGE|","WS_EX_TOOLWINDOW|","WS_EX_TOPMOST|","WS_EX_TRANSPARENT|","WS_EX_WINDOWEDGE|","WS_EX_LAYERED|","WS_EX_NOINHERITLAYOUT|","WS_EX_LAYOUTRTL|","WS_EX_NOACTIVATE|","WS_EX_COMPOSITED|","WS_EX_APPWINDOW|","WS_EX_SMCAPTION|",};
const UINT  aWndExStyleUINT[N_WND_EX_STYLES]={WS_EX_ACCEPTFILES,WS_EX_CLIENTEDGE,WS_EX_CONTEXTHELP,WS_EX_CONTROLPARENT,WS_EX_DLGMODALFRAME,WS_EX_LEFT,WS_EX_LEFTSCROLLBAR,WS_EX_LTRREADING,WS_EX_MDICHILD,WS_EX_NOPARENTNOTIFY,WS_EX_OVERLAPPEDWINDOW,WS_EX_PALETTEWINDOW,WS_EX_RIGHT,WS_EX_RIGHTSCROLLBAR,WS_EX_RTLREADING,WS_EX_STATICEDGE,WS_EX_TOOLWINDOW,WS_EX_TOPMOST,WS_EX_TRANSPARENT,WS_EX_WINDOWEDGE,WS_EX_LAYERED,WS_EX_NOINHERITLAYOUT,WS_EX_LAYOUTRTL,WS_EX_NOACTIVATE,WS_EX_COMPOSITED,WS_EX_APPWINDOW,WS_EX_APPWINDOW,};
const UINT  aWndExStyleMask[N_WND_EX_STYLES]={WS_EX_ACCEPTFILES,WS_EX_CLIENTEDGE,WS_EX_CONTEXTHELP,WS_EX_CONTROLPARENT,WS_EX_DLGMODALFRAME,WS_EX_RIGHT,WS_EX_LEFTSCROLLBAR,WS_EX_RTLREADING,WS_EX_MDICHILD,WS_EX_NOPARENTNOTIFY,WS_EX_OVERLAPPEDWINDOW,WS_EX_PALETTEWINDOW,WS_EX_RIGHT,WS_EX_LEFTSCROLLBAR,WS_EX_RTLREADING,WS_EX_STATICEDGE,WS_EX_TOOLWINDOW,WS_EX_TOPMOST,WS_EX_TRANSPARENT,WS_EX_WINDOWEDGE,WS_EX_LAYERED,WS_EX_NOINHERITLAYOUT,WS_EX_LAYOUTRTL,WS_EX_NOACTIVATE,WS_EX_COMPOSITED,WS_EX_APPWINDOW,WS_EX_APPWINDOW,};

const char *aWndShowStyleName[N_WND_SHOW_STYLES]={"SW_HIDE","SW_MINIMIZE","SW_RESTORE","SW_SHOW","SW_SHOWMAXIMIZED","SW_SHOWMINIMIZED","SW_SHOWMINNOACTIVE","SW_SHOWNA","SW_SHOWNOACTIVATE","SW_SHOWNORMAL","SW_MAXIMIZE","SW_FORCEMINIMIZE","SW_SHOWDEFAULT",};
const UINT  aWndShowStyleUINT[N_WND_SHOW_STYLES]={SW_HIDE,SW_MINIMIZE,SW_RESTORE,SW_SHOW,SW_SHOWMAXIMIZED,SW_SHOWMINIMIZED,SW_SHOWMINNOACTIVE,SW_SHOWNA,SW_SHOWNOACTIVATE,SW_SHOWNORMAL,SW_MAXIMIZE,SW_FORCEMINIMIZE,SW_SHOWDEFAULT,};
const UINT  aWndShowStyleMask[N_WND_SHOW_STYLES]={SW_HIDE,SW_MINIMIZE,SW_RESTORE,SW_SHOW,SW_SHOWMAXIMIZED,SW_SHOWMINIMIZED,SW_SHOWMINNOACTIVE,SW_SHOWNA,SW_SHOWNOACTIVATE,SW_SHOWNORMAL,SW_MAXIMIZE,SW_FORCEMINIMIZE,SW_SHOWDEFAULT,};

const char *aWindowPosStyleName[N_WINDOWPOS_STYLES]={"SWP_DRAWFRAME|","SWP_FRAMECHANGED|","SWP_HIDEWINDOW|","SWP_NOACTIVATE|","SWP_NOCOPYBITS|","SWP_NOMOVE|","SWP_NOOWNERZORDER|","SWP_NOREDRAW|","SWP_NOREPOSITION|","SWP_NOSENDCHANGING|","SWP_NOSIZE|","SWP_NOZORDER|","SWP_SHOWWINDOW|","SWP_DEFERERASE|","SWP_ASYNCWINDOWPOS|",};
const UINT  aWindowPosStyleUINT[N_WINDOWPOS_STYLES]={SWP_DRAWFRAME,SWP_FRAMECHANGED,SWP_HIDEWINDOW,SWP_NOACTIVATE,SWP_NOCOPYBITS,SWP_NOMOVE,SWP_NOOWNERZORDER,SWP_NOREDRAW,SWP_NOREPOSITION,SWP_NOSENDCHANGING,SWP_NOSIZE,SWP_NOZORDER,SWP_SHOWWINDOW,SWP_DEFERERASE,SWP_ASYNCWINDOWPOS};

const char *aDrawTextFlagName[N_DRAWTEXT_FLAGS]={"DT_TOP|","DT_LEFT|","DT_CENTER|","DT_RIGHT|","DT_VCENTER|","DT_BOTTOM|","DT_WORDBREAK|","DT_SINGLELINE|","DT_EXPANDTABS|","DT_TABSTOP|","DT_NOCLIP|","DT_EXTERNALLEADING|","DT_CALCRECT|","DT_NOPREFIX|","DT_INTERNAL|","DT_EDITCONTROL|","DT_PATH_ELLIPSIS|","DT_END_ELLIPSIS|","DT_MODIFYSTRING|","DT_RTLREADING|","DT_WORD_ELLIPSIS|","DT_NOFULLWIDTHCHARBREAK|","DT_HIDEPREFIX|","DT_PREFIXONLY|"};
const UINT  aDrawTextFlagUINT[N_DRAWTEXT_FLAGS]={DT_TOP,DT_LEFT,DT_CENTER,DT_RIGHT,DT_VCENTER,DT_BOTTOM,DT_WORDBREAK,DT_SINGLELINE,DT_EXPANDTABS,DT_TABSTOP,DT_NOCLIP,DT_EXTERNALLEADING,DT_CALCRECT,DT_NOPREFIX,DT_INTERNAL,DT_EDITCONTROL,DT_PATH_ELLIPSIS,DT_END_ELLIPSIS,DT_MODIFYSTRING,DT_RTLREADING,DT_WORD_ELLIPSIS,DT_NOFULLWIDTHCHARBREAK,DT_HIDEPREFIX,DT_PREFIXONLY,};

const char *aCtrlBarStyleName[N_CTRLBAR_STYLES]={"CBRS_ALIGN_LEFT|","CBRS_ALIGN_TOP|","CBRS_ALIGN_RIGHT|","CBRS_ALIGN_BOTTOM|","CBRS_ALIGN_ANY|","CBRS_BORDER_LEFT|","CBRS_BORDER_TOP|","CBRS_BORDER_RIGHT|","CBRS_BORDER_BOTTOM|","CBRS_BORDER_ANY|","CBRS_TOOLTIPS|","CBRS_FLYBY|","CBRS_FLOAT_MULTI|","CBRS_BORDER_3D|","CBRS_HIDE_INPLACE|","CBRS_SIZE_DYNAMIC|","CBRS_SIZE_FIXED|","CBRS_FLOATING|","CBRS_GRIPPER|","CBRS_ORIENT_HORZ|","CBRS_ORIENT_VERT|","CBRS_ORIENT_ANY|","CBRS_ALL|","CBRS_LEFT|","CBRS_TOP|","CBRS_RIGHT|","CBRS_BOTTOM|",};
const UINT  aCtrlBarStyleUINT[N_CTRLBAR_STYLES]={CBRS_ALIGN_LEFT,    CBRS_ALIGN_TOP,   CBRS_ALIGN_RIGHT,   CBRS_ALIGN_BOTTOM,   CBRS_ALIGN_ANY,   CBRS_BORDER_LEFT,   CBRS_BORDER_TOP,   CBRS_BORDER_RIGHT,   CBRS_BORDER_BOTTOM,   CBRS_BORDER_ANY,   CBRS_TOOLTIPS,   CBRS_FLYBY,   CBRS_FLOAT_MULTI,   CBRS_BORDER_3D,   CBRS_HIDE_INPLACE,   CBRS_SIZE_DYNAMIC,   CBRS_SIZE_FIXED,   CBRS_FLOATING,   CBRS_GRIPPER,   CBRS_ORIENT_HORZ,   CBRS_ORIENT_VERT,   CBRS_ORIENT_ANY,   CBRS_ALL,   CBRS_LEFT,   CBRS_TOP,   CBRS_RIGHT,   CBRS_BOTTOM,};
const UINT  aCtrlBarStyleMask[N_CTRLBAR_STYLES]={CBRS_ALIGN_LEFT,CBRS_ALIGN_TOP,CBRS_ALIGN_RIGHT,CBRS_ALIGN_BOTTOM,CBRS_ALIGN_ANY,CBRS_BORDER_LEFT,CBRS_BORDER_TOP,CBRS_BORDER_RIGHT,CBRS_BORDER_BOTTOM,CBRS_BORDER_ANY,CBRS_TOOLTIPS,CBRS_FLYBY,CBRS_FLOAT_MULTI,CBRS_BORDER_3D,CBRS_HIDE_INPLACE,CBRS_SIZE_DYNAMIC,CBRS_SIZE_FIXED,CBRS_FLOATING,CBRS_GRIPPER,CBRS_ORIENT_HORZ,CBRS_ORIENT_VERT,CBRS_ORIENT_ANY,CBRS_ALL,CBRS_LEFT,CBRS_TOP,CBRS_RIGHT,CBRS_BOTTOM,};

const char *aDlgStyleName[N_DLG_STYLES]={"DS_3DLOOK|","DS_ABSALIGN|","DS_CENTER|","DS_CENTERMOUSE|","DS_CONTEXTHELP|","DS_CONTROL|","DS_FIXEDSYS|","DS_LOCALEDIT|","DS_MODALFRAME|","DS_NOFAILCREATE|","DS_NOIDLEMSG|","DS_SETFONT|","DS_SETFOREGROUND|","DS_SYSMODAL|","DS_SHELLFONT|",};
const UINT  aDlgStyleUINT[N_DLG_STYLES]={DS_3DLOOK,DS_ABSALIGN,DS_CENTER,DS_CENTERMOUSE,DS_CONTEXTHELP,DS_CONTROL,DS_FIXEDSYS,DS_LOCALEDIT,DS_MODALFRAME,DS_NOFAILCREATE,DS_NOIDLEMSG,DS_SETFONT,DS_SETFOREGROUND,DS_SYSMODAL,DS_SHELLFONT,};
const UINT  aDlgStyleMask[N_DLG_STYLES]={DS_3DLOOK,DS_ABSALIGN,DS_CENTER,DS_CENTERMOUSE,DS_CONTEXTHELP,DS_CONTROL,DS_FIXEDSYS,DS_LOCALEDIT,DS_MODALFRAME,DS_NOFAILCREATE,DS_NOIDLEMSG,DS_SETFONT,DS_SETFOREGROUND,DS_SYSMODAL,DS_SHELLFONT,};

const char *aComCtrlStyleName[N_COMCTRL_STYLES]={"CCS_TOP|","CCS_NOMOVEY|","CCS_BOTTOM|","CCS_NORESIZE|","CCS_NOPARENTALIGN|","CCS_ADJUSTABLE|","CCS_NODIVIDER|","CCS_VERT|",};
const UINT  aComCtrlStyleUINT[N_COMCTRL_STYLES]={CCS_TOP,CCS_NOMOVEY,CCS_BOTTOM,CCS_NORESIZE,CCS_NOPARENTALIGN,CCS_ADJUSTABLE,CCS_NODIVIDER,CCS_VERT,};
const UINT  aComCtrlStyleMask[N_COMCTRL_STYLES]={0x00000003L,0x00000003L,0x00000003L,CCS_NORESIZE,CCS_NOPARENTALIGN,CCS_ADJUSTABLE,CCS_NODIVIDER,CCS_VERT,};

const char *aListCtrlStyleName[N_LISTCTRL_STYLES]={"_ALIGNLEFT|","_AUTOARRANGE|","_EDITLABELS|","_LIST|","_NOCOLUMNHEADER|","_NOLABELWRAP|","_NOSCROLL|","_NOSORTHEADER|","_OWNERDRAWFIXED|","_REPORT|","_SHAREIMAGELISTS|","_SHOWSELALWAYS|","_SINGLESEL|","_SMALLICON|","_SORTASCENDING|","_SORTDESCENDING|","LVS_OWNERDATA|",};
const UINT  aListCtrlStyleUINT[N_LISTCTRL_STYLES]={LVS_ALIGNLEFT,LVS_AUTOARRANGE,LVS_EDITLABELS,LVS_LIST,LVS_NOCOLUMNHEADER,LVS_NOLABELWRAP,LVS_NOSCROLL,LVS_NOSORTHEADER,LVS_OWNERDRAWFIXED,LVS_REPORT,LVS_SHAREIMAGELISTS,LVS_SHOWSELALWAYS,LVS_SINGLESEL,LVS_SMALLICON,LVS_SORTASCENDING,LVS_SORTDESCENDING,LVS_OWNERDATA,};
const UINT  aListCtrlStyleMask[N_LISTCTRL_STYLES]={LVS_ALIGNLEFT,LVS_AUTOARRANGE,LVS_EDITLABELS,LVS_LIST,LVS_NOCOLUMNHEADER,LVS_NOLABELWRAP,LVS_NOSCROLL,LVS_NOSORTHEADER,LVS_OWNERDRAWFIXED,LVS_REPORT,LVS_SHAREIMAGELISTS,LVS_SHOWSELALWAYS,LVS_SINGLESEL,LVS_SMALLICON,LVS_SORTASCENDING,LVS_SORTDESCENDING,LVS_OWNERDATA,};

const char *aListCtrlExStyleName[N_LISTCTRL_EX_STYLES]={
	"_EX_CHECKBOXES|","_EX_FLATSB|","_EX_FULLROWSELECT|","_EX_GRIDLINES|","_EX_HEADERDRAGDROP|",
	"_EX_INFOTIP|","_EX_MULTIWORKAREAS|","_EX_ONECLICKACTIVATE|","_EX_REGIONAL|","_EX_SUBITEMIMAGES|",
	"_EX_TRACKSELECT|","_EX_TWOCLICKACTIVATE|","_EX_UNDERLINECOLD|","_EX_UNDERLINEHOT|",
	"_EX_LABELTIP|","_EX_BORDERSELECT|","_EX_DOUBLEBUFFER|","_EX_HIDELABELS|","_EX_SINGLEROW|",
	"_EX_SNAPTOGRID|","_EX_SIMPLESELECT|","_EX_JUSTIFYCOLUMNS|","_EX_TRANSPARENTBKGND|","_EX_TRANSPARENTSHADOWTEXT|",
	"_EX_AUTOAUTOARRANGE|","_EX_HEADERINALLVIEWS|","_EX_AUTOCHECKSELECT|","_EX_AUTOSIZECOLUMNS|",
	"_EX_COLUMNSNAPPOINTS|","_EX_COLUMNOVERFLOW|",
};
const UINT  aListCtrlExStyleUINT[N_LISTCTRL_EX_STYLES]={
	LVS_EX_CHECKBOXES,LVS_EX_FLATSB,LVS_EX_FULLROWSELECT,LVS_EX_GRIDLINES,LVS_EX_HEADERDRAGDROP,
	LVS_EX_INFOTIP,LVS_EX_MULTIWORKAREAS,LVS_EX_ONECLICKACTIVATE,LVS_EX_REGIONAL,LVS_EX_SUBITEMIMAGES,
	LVS_EX_TRACKSELECT,LVS_EX_TWOCLICKACTIVATE,LVS_EX_UNDERLINECOLD,LVS_EX_UNDERLINEHOT,
	LVS_EX_LABELTIP,LVS_EX_BORDERSELECT,LVS_EX_DOUBLEBUFFER,LVS_EX_HIDELABELS,LVS_EX_SINGLEROW,
	LVS_EX_SNAPTOGRID,LVS_EX_SIMPLESELECT,LVS_EX_JUSTIFYCOLUMNS,LVS_EX_TRANSPARENTBKGND,LVS_EX_TRANSPARENTSHADOWTEXT,
	LVS_EX_AUTOAUTOARRANGE,LVS_EX_HEADERINALLVIEWS,LVS_EX_AUTOCHECKSELECT,LVS_EX_AUTOSIZECOLUMNS,
	LVS_EX_COLUMNSNAPPOINTS,LVS_EX_COLUMNOVERFLOW,
};
const UINT  aListCtrlExStyleMask[N_LISTCTRL_EX_STYLES]={
	LVS_EX_CHECKBOXES,LVS_EX_FLATSB,LVS_EX_FULLROWSELECT,LVS_EX_GRIDLINES,LVS_EX_HEADERDRAGDROP,
	LVS_EX_INFOTIP,LVS_EX_MULTIWORKAREAS,LVS_EX_ONECLICKACTIVATE,LVS_EX_REGIONAL,LVS_EX_SUBITEMIMAGES,
	LVS_EX_TRACKSELECT,LVS_EX_TWOCLICKACTIVATE,LVS_EX_UNDERLINECOLD,LVS_EX_UNDERLINEHOT,
	LVS_EX_LABELTIP,LVS_EX_BORDERSELECT,LVS_EX_DOUBLEBUFFER,LVS_EX_HIDELABELS,LVS_EX_SINGLEROW,
	LVS_EX_SNAPTOGRID,LVS_EX_SIMPLESELECT,LVS_EX_JUSTIFYCOLUMNS,LVS_EX_TRANSPARENTBKGND,LVS_EX_TRANSPARENTSHADOWTEXT,
	LVS_EX_AUTOAUTOARRANGE,LVS_EX_HEADERINALLVIEWS,LVS_EX_AUTOCHECKSELECT,LVS_EX_AUTOSIZECOLUMNS,
	LVS_EX_COLUMNSNAPPOINTS,LVS_EX_COLUMNOVERFLOW,
};

const char *aAnimationStyleName[N_ANIMATION_STYLES]={"_CENTER|","_TRANSPARENT|","_AUTOPLAY|","_TIMER|"};
const UINT  aAnimationStyleUINT[N_ANIMATION_STYLES]={ACS_CENTER,ACS_TRANSPARENT,ACS_AUTOPLAY,ACS_TIMER,};
const UINT  aAnimationStyleMask[N_ANIMATION_STYLES]={ACS_CENTER,ACS_TRANSPARENT,ACS_AUTOPLAY,ACS_TIMER,};

const char *aProgressStyleName[N_PROGRESS_STYLES]={"_VERTICAL|","_SMOOTH|","_MARQUEE|","_SMOOTHREVERSE|"};
const UINT  aProgressStyleUINT[N_PROGRESS_STYLES]={PBS_VERTICAL,PBS_SMOOTH,PBS_MARQUEE,PBS_SMOOTHREVERSE,};
const UINT  aProgressStyleMask[N_PROGRESS_STYLES]={PBS_VERTICAL,PBS_SMOOTH,PBS_MARQUEE,PBS_SMOOTHREVERSE,};

const char *aScrollStyleName[N_SCROLL_STYLES]={"_BOTTOMALIGN|","_HORZ|","_LEFTALIGN|","_RIGHTALIGN|","_SIZEBOX|","_SIZEBOXBOTTOMRIGHTALIGN|","_SIZEBOXTOPLEFTALIGN|","_TOPALIGN|","_VERT|","_SIZEGRIP|"};
const UINT  aScrollStyleUINT[N_SCROLL_STYLES]={SBS_BOTTOMALIGN,SBS_HORZ,SBS_LEFTALIGN,SBS_RIGHTALIGN,SBS_SIZEBOX,SBS_SIZEBOXBOTTOMRIGHTALIGN,SBS_SIZEBOXTOPLEFTALIGN,SBS_TOPALIGN,SBS_VERT,SBS_SIZEGRIP,};
const UINT  aScrollStyleMask[N_SCROLL_STYLES]={SBS_BOTTOMALIGN,SBS_HORZ,SBS_LEFTALIGN,SBS_RIGHTALIGN,SBS_SIZEBOX,SBS_SIZEBOXBOTTOMRIGHTALIGN,SBS_SIZEBOXTOPLEFTALIGN,SBS_TOPALIGN,SBS_VERT,SBS_SIZEGRIP,};

const char *aComboBoxStyleName[N_COMBOBOX_STYLES]={"_AUTOHSCROLL|" ,"_DROPDOWN|" ,"_DROPDOWNLIST|" ,"_HASSTRINGS|" ,"_OEMCONVERT|" ,"_OWNERDRAWFIXED|" ,"_OWNERDRAWVARIABLE|","_SIMPLE|","_SORT|","_DISABLENOSCROLL|","_NOINTEGRALHEIGHT|","_UPPERCASE|","_LOWERCASE|"};
const UINT  aComboBoxStyleUINT[N_COMBOBOX_STYLES]={CBS_AUTOHSCROLL,CBS_DROPDOWN,CBS_DROPDOWNLIST,CBS_HASSTRINGS,CBS_OEMCONVERT,CBS_OWNERDRAWFIXED,CBS_OWNERDRAWVARIABLE,CBS_SIMPLE,CBS_SORT,CBS_DISABLENOSCROLL,CBS_NOINTEGRALHEIGHT,CBS_UPPERCASE,CBS_LOWERCASE,};
const UINT  aComboBoxStyleMask[N_COMBOBOX_STYLES]={CBS_AUTOHSCROLL,0x0003L,0x0003L,CBS_HASSTRINGS,CBS_OEMCONVERT,CBS_OWNERDRAWFIXED,CBS_OWNERDRAWVARIABLE,0x0003L,CBS_SORT,CBS_DISABLENOSCROLL,CBS_NOINTEGRALHEIGHT,CBS_UPPERCASE,CBS_LOWERCASE,};

const char *aComboBoxExStyleName[N_COMBOBOXEX_STYLES]={"_AUTOHSCROLL|" ,"_DROPDOWN|" ,"_DROPDOWNLIST|" ,"_HASSTRINGS|" ,"_OEMCONVERT|" ,"_OWNERDRAWFIXED|" ,"_OWNERDRAWVARIABLE|","_SIMPLE|","_SORT|","_DISABLENOSCROLL|","_NOINTEGRALHEIGHT|","_UPPERCASE|","_LOWERCASE|"};
const UINT  aComboBoxExStyleUINT[N_COMBOBOXEX_STYLES]={CBS_AUTOHSCROLL,CBS_DROPDOWN,CBS_DROPDOWNLIST,CBS_HASSTRINGS,CBS_OEMCONVERT,CBS_OWNERDRAWFIXED,CBS_OWNERDRAWVARIABLE,CBS_SIMPLE,CBS_SORT,CBS_DISABLENOSCROLL,CBS_NOINTEGRALHEIGHT,CBS_UPPERCASE,CBS_LOWERCASE,};
const UINT  aComboBoxExStyleMask[N_COMBOBOXEX_STYLES]={CBS_AUTOHSCROLL,0x0003L,0x0003L,CBS_HASSTRINGS,CBS_OEMCONVERT,CBS_OWNERDRAWFIXED,CBS_OWNERDRAWVARIABLE,0x0003L,CBS_SORT,CBS_DISABLENOSCROLL,CBS_NOINTEGRALHEIGHT,CBS_UPPERCASE,CBS_LOWERCASE,};

const char *aComboBoxExExStyleName[N_COMBOBOXEX_EX_STYLES]={"_EX_CASESENSITIVE|" ,"_EX_NOSIZELIMIT|" ,"_EX_PATHWORDBREAKPROC|" ,"_EX_NOEDITIMAGEINDENT|" ,"_EX_NOEDITIMAGE|" ,"_EX_TEXTENDELLIPSIS|" ,};
const UINT  aComboBoxExExStyleUINT[N_COMBOBOXEX_EX_STYLES]={CBES_EX_CASESENSITIVE,CBES_EX_NOSIZELIMIT,CBES_EX_PATHWORDBREAKPROC,CBES_EX_NOEDITIMAGEINDENT,CBES_EX_NOEDITIMAGE,CBES_EX_TEXTENDELLIPSIS};
const UINT  aComboBoxExExStyleMask[N_COMBOBOXEX_EX_STYLES]={CBES_EX_CASESENSITIVE,CBES_EX_NOSIZELIMIT,CBES_EX_PATHWORDBREAKPROC,CBES_EX_NOEDITIMAGEINDENT,CBES_EX_NOEDITIMAGE,CBES_EX_TEXTENDELLIPSIS,};

const char *aListBoxStyleName[N_LISTBOX_STYLES]={"_EXTENDEDSEL|","_HASSTRINGS|","_MULTICOLUMN|","_MULTIPLESEL|","_NOINTEGRALHEIGHT|","_NOREDRAW|","_NOTIFY|","_OWNERDRAWFIXED|","_OWNERDRAWVARIABLE|","_SORT|","_STANDARD|","_USETABSTOPS|","_WANTKEYBOARDINPUT|","_DISABLENOSCROLL|","_NODATA|","_NOSEL|","_COMBOBOX|",};
const UINT  aListBoxStyleUINT[N_LISTBOX_STYLES]={LBS_EXTENDEDSEL,LBS_HASSTRINGS,LBS_MULTICOLUMN,LBS_MULTIPLESEL,LBS_NOINTEGRALHEIGHT,LBS_NOREDRAW,LBS_NOTIFY,LBS_OWNERDRAWFIXED,LBS_OWNERDRAWVARIABLE,LBS_SORT,LBS_STANDARD,LBS_USETABSTOPS,LBS_WANTKEYBOARDINPUT,LBS_DISABLENOSCROLL,LBS_NODATA,LBS_NOSEL,LBS_COMBOBOX,};
const UINT  aListBoxStyleMask[N_LISTBOX_STYLES]={LBS_EXTENDEDSEL,LBS_HASSTRINGS,LBS_MULTICOLUMN,LBS_MULTIPLESEL,LBS_NOINTEGRALHEIGHT,LBS_NOREDRAW,LBS_NOTIFY,LBS_OWNERDRAWFIXED,LBS_OWNERDRAWVARIABLE,LBS_SORT,LBS_STANDARD,LBS_USETABSTOPS,LBS_WANTKEYBOARDINPUT,LBS_DISABLENOSCROLL,LBS_NODATA,LBS_NOSEL,LBS_COMBOBOX,};

const char *aButtonStyleName[N_BUTTON_STYLES]={"_AUTOCHECKBOX|","_AUTORADIOBUTTON|"	,"_AUTO3STATE|"	,"_CHECKBOX|"	,"_DEFPUSHBUTTON|"	,"_GROUPBOX|",	"_LEFTTEXT|",	"_OWNERDRAW|",	"_RADIOBUTTON|",	"_3STATE|",			"_ICON|",	"_BITMAP|",	"_LEFT|",	"_RIGHT|",	"_CENTER|",	"_TOP|",	"_BOTTOM|",	"_VCENTER|",	"_PUSHLIKE|",	"_MULTILINE|",	"_NOTIFY|",	"_FLAT|","_USERBUTTON|", "_PUSHBOX|",};
const UINT  aButtonStyleUINT[N_BUTTON_STYLES]={BS_AUTOCHECKBOX,BS_AUTORADIOBUTTON	,BS_AUTO3STATE	,BS_CHECKBOX	,BS_DEFPUSHBUTTON	,BS_GROUPBOX,	BS_LEFTTEXT,	BS_OWNERDRAW,	BS_RADIOBUTTON,		BS_3STATE,			BS_ICON,	BS_BITMAP,	BS_LEFT,	BS_RIGHT,	BS_CENTER,	BS_TOP,		BS_BOTTOM,	BS_VCENTER,		BS_PUSHLIKE,	BS_MULTILINE,	BS_NOTIFY,	BS_FLAT, BS_USERBUTTON, BS_PUSHBOX,};
const UINT  aButtonStyleMask[N_BUTTON_STYLES]={BS_TYPEMASK,    BS_TYPEMASK			,BS_TYPEMASK	,BS_TYPEMASK	,BS_TYPEMASK		,0x0000000FL,	BS_LEFTTEXT,	BS_TYPEMASK ,	BS_TYPEMASK  ,		BS_ICON|BS_BITMAP,	BS_ICON,	BS_BITMAP,	0x00000F00L,0x00000F00L,0x00000F00L,0x00000F00L,0x00000F00L,0x00000F00L,	BS_PUSHLIKE,	BS_MULTILINE,	BS_NOTIFY,	BS_FLAT, BS_USERBUTTON, BS_PUSHBOX,};

const char *aEditStyleName[N_EDIT_STYLES]={"_AUTOHSCROLL|","_AUTOVSCROLL|","_CENTER|","_LEFT|","_LOWERCASE|","_MULTILINE|","_NOHIDESEL|","_OEMCONVERT|","_PASSWORD|","_RIGHT|","_UPPERCASE|","_READONLY|","_WANTRETURN|","_NUMBER|",};
const UINT  aEditStyleUINT[N_EDIT_STYLES]={ES_AUTOHSCROLL,ES_AUTOVSCROLL,ES_CENTER,ES_LEFT,ES_LOWERCASE,ES_MULTILINE,ES_NOHIDESEL,ES_OEMCONVERT,ES_PASSWORD,ES_RIGHT,ES_UPPERCASE,ES_READONLY,ES_WANTRETURN,ES_NUMBER,};
const UINT  aEditStyleMask[N_EDIT_STYLES]={ES_AUTOHSCROLL,ES_AUTOVSCROLL,ES_CENTER,ES_RIGHT,ES_LOWERCASE,ES_MULTILINE,ES_NOHIDESEL,ES_OEMCONVERT,ES_PASSWORD,ES_RIGHT,ES_UPPERCASE,ES_READONLY,ES_WANTRETURN,ES_NUMBER,};

const char *aRTFStyleName[N_RTF_STYLES]={"_AUTOHSCROLL|","_AUTOVSCROLL|","_CENTER|","_LEFT|","_LOWERCASE|","_MULTILINE|","_NOHIDESEL|","_OEMCONVERT|","_PASSWORD|","_RIGHT|","_UPPERCASE|","_READONLY|","_WANTRETURN|","_NUMBER|","_SAVESEL|","_SUNKEN|","_DISABLENOSCROLL|","_SELECTIONBAR|","_NOOLEDRAGDROP|","_VERTICAL|","_NOIME|","_SELFIME|",};
const UINT  aRTFStyleUINT[N_RTF_STYLES]={ES_AUTOHSCROLL,ES_AUTOVSCROLL,ES_CENTER,ES_LEFT,ES_LOWERCASE,ES_MULTILINE,ES_NOHIDESEL,ES_OEMCONVERT,ES_PASSWORD,ES_RIGHT,ES_UPPERCASE,ES_READONLY,ES_WANTRETURN,ES_NUMBER,ES_SAVESEL,ES_SUNKEN,ES_DISABLENOSCROLL,ES_SELECTIONBAR,ES_NOOLEDRAGDROP,ES_VERTICAL,ES_NOIME,ES_SELFIME,};
const UINT  aRTFStyleMask[N_RTF_STYLES]={ES_AUTOHSCROLL,ES_AUTOVSCROLL,ES_CENTER,ES_RIGHT,ES_LOWERCASE,ES_MULTILINE,ES_NOHIDESEL,ES_OEMCONVERT,ES_PASSWORD,ES_RIGHT,ES_UPPERCASE,ES_READONLY,ES_WANTRETURN,ES_NUMBER,ES_SAVESEL,ES_SUNKEN,ES_DISABLENOSCROLL,ES_SELECTIONBAR,ES_NOOLEDRAGDROP,ES_VERTICAL,ES_NOIME,ES_SELFIME,};

const char *aRTFExStyleName[N_RTF_EX_STYLES]={"_EX_NOCALLOLEINIT|",};
const UINT  aRTFExStyleUINT[N_RTF_EX_STYLES]={ES_EX_NOCALLOLEINIT,};
const UINT  aRTFExStyleMask[N_RTF_EX_STYLES]={ES_EX_NOCALLOLEINIT,};

const char *aStaticStyleName[N_STATIC_STYLES]={"_LEFT|","_CENTER|","_RIGHT|","_ICON|","_BLACKRECT|","_GRAYRECT|","_WHITERECT|","_BLACKFRAME|","_GRAYFRAME|","_WHITEFRAME|","_USERITEM|","_SIMPLE|","_LEFTNOWORDWRAP|","_OWNERDRAW|","_BITMAP|","_ENHMETAFILE|","_ETCHEDHORZ|","_ETCHEDVERT|","_ETCHEDFRAME|","_TYPEMASK|","_NOPREFIX|","_NOTIFY|","_CENTERIMAGE|","_RIGHTJUST|","_REALSIZEIMAGE|","_SUNKEN|","_ENDELLIPSIS|","_PATHELLIPSIS|","_WORDELLIPSIS|","_ELLIPSISMASK|","_REALSIZECONTROL|",};
const UINT  aStaticStyleUINT[N_STATIC_STYLES]={SS_LEFT,SS_CENTER,SS_RIGHT,SS_ICON,SS_BLACKRECT,SS_GRAYRECT,SS_WHITERECT,SS_BLACKFRAME,SS_GRAYFRAME,SS_WHITEFRAME,SS_USERITEM,SS_SIMPLE,SS_LEFTNOWORDWRAP,SS_OWNERDRAW,SS_BITMAP,SS_ENHMETAFILE,SS_ETCHEDHORZ,SS_ETCHEDVERT,SS_ETCHEDFRAME,SS_TYPEMASK,SS_NOPREFIX,SS_NOTIFY,SS_CENTERIMAGE,SS_RIGHTJUST,SS_REALSIZEIMAGE,SS_SUNKEN,SS_ENDELLIPSIS,SS_PATHELLIPSIS,SS_WORDELLIPSIS,SS_ELLIPSISMASK,SS_REALSIZECONTROL,};
const UINT  aStaticStyleMask[N_STATIC_STYLES]={0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,0x000000FFL,SS_NOPREFIX,SS_NOTIFY,SS_CENTERIMAGE,SS_RIGHTJUST,SS_REALSIZEIMAGE,SS_SUNKEN,SS_ENDELLIPSIS,SS_PATHELLIPSIS,SS_WORDELLIPSIS,SS_ELLIPSISMASK,SS_REALSIZECONTROL,};

const char *aDateTimeStyleName[N_DATETIME_STYLES]={"_APPCANPARSE|","_LONGDATEFORMAT|","_RIGHTALIGN|","_SHOWNONE|","_TIMEFORMAT|","_UPDOWN|","_SHORTDATECENTURYFORMAT|",};
const UINT  aDateTimeStyleUINT[N_DATETIME_STYLES]={DTS_APPCANPARSE,DTS_LONGDATEFORMAT,DTS_RIGHTALIGN,DTS_SHOWNONE,DTS_TIMEFORMAT,DTS_UPDOWN,DTS_SHORTDATECENTURYFORMAT,};
const UINT  aDateTimeStyleMask[N_DATETIME_STYLES]={DTS_APPCANPARSE,DTS_LONGDATEFORMAT,DTS_RIGHTALIGN,DTS_SHOWNONE,DTS_TIMEFORMAT,DTS_UPDOWN,DTS_SHORTDATECENTURYFORMAT,};

const char *aMonthCalStyleName[N_MONTHCAL_STYLES]={"NOTODAY|","NOTODAYCIRCLE|","WEEKNUMBERS|","MULTISELECT|","DAYSTATE|","NOTRAILINGDATES|","SHORTDAYSOFWEEK|","NOSELCHANGEONNAV|",};
const UINT  aMonthCalStyleUINT[N_MONTHCAL_STYLES]={MCS_NOTODAY,MCS_NOTODAYCIRCLE,MCS_WEEKNUMBERS,MCS_MULTISELECT,MCS_DAYSTATE,MCS_NOTRAILINGDATES,MCS_SHORTDAYSOFWEEK,MCS_NOSELCHANGEONNAV,};
const UINT  aMonthCalStyleMask[N_MONTHCAL_STYLES]={MCS_NOTODAY,MCS_NOTODAYCIRCLE,MCS_WEEKNUMBERS,MCS_MULTISELECT,MCS_DAYSTATE,MCS_NOTRAILINGDATES,MCS_SHORTDAYSOFWEEK,MCS_NOSELCHANGEONNAV,};

const char *aSpinStyleName[N_SPIN_STYLES]={"_HORZ|","_WRAP|","_ARROWKEYS|","_SETBUDDYINT|","_NOTHOUSANDS|","_AUTOBUDDY|","_ALIGNRIGHT|","_ALIGNLEFT|","_HOTTRACK|",};
const UINT  aSpinStyleUINT[N_SPIN_STYLES]={UDS_HORZ,UDS_WRAP,UDS_ARROWKEYS,UDS_SETBUDDYINT,UDS_NOTHOUSANDS,UDS_AUTOBUDDY,UDS_ALIGNRIGHT,UDS_ALIGNLEFT,UDS_HOTTRACK,};
const UINT  aSpinStyleMask[N_SPIN_STYLES]={UDS_HORZ,UDS_WRAP,UDS_ARROWKEYS,UDS_SETBUDDYINT,UDS_NOTHOUSANDS,UDS_AUTOBUDDY,UDS_ALIGNRIGHT,UDS_ALIGNLEFT,UDS_HOTTRACK,};

const char *aTabStyleName[N_TAB_STYLES]={"_SCROLLOPPOSITE|","_BOTTOM|","_RIGHT|","_MULTISELECT|","_FLATBUTTONS|","_FORCEICONLEFT|","_FORCELABELLEFT|","_HOTTRACK|","_VERTICAL|","_BUTTONS|","_MULTILINE|","_FIXEDWIDTH|","_RAGGEDRIGHT|","_FOCUSONBUTTONDOWN|","_OWNERDRAWFIXED|","_TOOLTIPS|","_FOCUSNEVER|",};
const UINT  aTabStyleUINT[N_TAB_STYLES]={TCS_SCROLLOPPOSITE,TCS_BOTTOM,TCS_RIGHT,TCS_MULTISELECT,TCS_FLATBUTTONS,TCS_FORCEICONLEFT,TCS_FORCELABELLEFT,TCS_HOTTRACK,TCS_VERTICAL,TCS_BUTTONS,TCS_MULTILINE,TCS_FIXEDWIDTH,TCS_RAGGEDRIGHT,TCS_FOCUSONBUTTONDOWN,TCS_OWNERDRAWFIXED,TCS_TOOLTIPS,TCS_FOCUSNEVER,};
const UINT  aTabStyleMask[N_TAB_STYLES]={TCS_SCROLLOPPOSITE,TCS_BOTTOM,TCS_RIGHT,TCS_MULTISELECT,TCS_FLATBUTTONS,TCS_FORCEICONLEFT,TCS_FORCELABELLEFT,TCS_HOTTRACK,TCS_VERTICAL,TCS_BUTTONS,TCS_MULTILINE,TCS_FIXEDWIDTH,TCS_RAGGEDRIGHT,TCS_FOCUSONBUTTONDOWN,TCS_OWNERDRAWFIXED,TCS_TOOLTIPS,TCS_FOCUSNEVER,};

const char *aTabExStyleName[N_TAB_EX_STYLES]={"_EX_FLATSEPARATORS|","_EX_REGISTERDROP|",};
const UINT  aTabExStyleUINT[N_TAB_EX_STYLES]={TCS_EX_FLATSEPARATORS,TCS_EX_REGISTERDROP,};
const UINT  aTabExStyleMask[N_TAB_EX_STYLES]={TCS_EX_FLATSEPARATORS,TCS_EX_REGISTERDROP,};

const char *aSliderStyleName[N_SLIDER_STYLES]={"_VERT|","_AUTOTICKS|","_NOTICKS|","_BOTTOM|","_TOP|","_LEFT|","_BOTH|","_ENABLESELRANGE|","_FIXEDLENGTH|","_NOTHUMB|","_TOOLTIPS|","_REVERSED|","_DOWNISLEFT|","_NOTIFYBEFOREMOVE|","_TRANSPARENTBKGND|",};
const UINT  aSliderStyleUINT[N_SLIDER_STYLES]={TBS_VERT,TBS_AUTOTICKS,TBS_NOTICKS,TBS_BOTTOM,TBS_TOP,TBS_LEFT,TBS_BOTH,TBS_ENABLESELRANGE,TBS_FIXEDLENGTH,TBS_NOTHUMB,TBS_TOOLTIPS,TBS_REVERSED,TBS_DOWNISLEFT,TBS_NOTIFYBEFOREMOVE,TBS_TRANSPARENTBKGND};
const UINT  aSliderStyleMask[N_SLIDER_STYLES]={TBS_VERT,TBS_AUTOTICKS,TBS_NOTICKS,TBS_BOTTOM,TBS_TOP,TBS_LEFT,TBS_BOTH,TBS_ENABLESELRANGE,TBS_FIXEDLENGTH,TBS_NOTHUMB,TBS_TOOLTIPS,TBS_REVERSED,TBS_DOWNISLEFT,TBS_NOTIFYBEFOREMOVE,TBS_TRANSPARENTBKGND};

const char *aHeaderStyleName[N_HEADER_STYLES]={"_BUTTONS|","_HOTTRACK|","_HIDDEN|","_DRAGDROP|","_FULLDRAG|","_FILTERBAR|","_FLAT|","_CHECKBOXES|","_NOSIZING|","_OVERFLOW|",};
const UINT  aHeaderStyleUINT[N_HEADER_STYLES]={HDS_BUTTONS,HDS_HOTTRACK,HDS_HIDDEN,HDS_DRAGDROP,HDS_FULLDRAG,HDS_FILTERBAR,HDS_FLAT,HDS_CHECKBOXES,HDS_NOSIZING,HDS_OVERFLOW,};
const UINT  aHeaderStyleMask[N_HEADER_STYLES]={HDS_BUTTONS,HDS_HOTTRACK,HDS_HIDDEN,HDS_DRAGDROP,HDS_FULLDRAG,HDS_FILTERBAR,HDS_FLAT,HDS_CHECKBOXES,HDS_NOSIZING,HDS_OVERFLOW,};

const char *aTreeCtrlStyleName[N_TREECTRL_STYLES]={"_HASBUTTONS|","_HASLINES|","_LINESATROOT|","_EDITLABELS|","_DISABLEDRAGDROP|","_SHOWSELALWAYS|","_RTLREADING|","_NOTOOLTIPS|","_CHECKBOXES|","_TRACKSELECT|","_SINGLEEXPAND|","_INFOTIP|","_FULLROWSELECT|","_NOSCROLL|","_NONEVENHEIGHT|","_NOHSCROLL|",};
const UINT  aTreeCtrlStyleUINT[N_TREECTRL_STYLES]={TVS_HASBUTTONS,TVS_HASLINES,TVS_LINESATROOT,TVS_EDITLABELS,TVS_DISABLEDRAGDROP,TVS_SHOWSELALWAYS,TVS_RTLREADING,TVS_NOTOOLTIPS,TVS_CHECKBOXES,TVS_TRACKSELECT,TVS_SINGLEEXPAND,TVS_INFOTIP,TVS_FULLROWSELECT,TVS_NOSCROLL,TVS_NONEVENHEIGHT,TVS_NOHSCROLL,};
const UINT  aTreeCtrlStyleMask[N_TREECTRL_STYLES]={TVS_HASBUTTONS,TVS_HASLINES,TVS_LINESATROOT,TVS_EDITLABELS,TVS_DISABLEDRAGDROP,TVS_SHOWSELALWAYS,TVS_RTLREADING,TVS_NOTOOLTIPS,TVS_CHECKBOXES,TVS_TRACKSELECT,TVS_SINGLEEXPAND,TVS_INFOTIP,TVS_FULLROWSELECT,TVS_NOSCROLL,TVS_NONEVENHEIGHT,TVS_NOHSCROLL,};

const char *aTreeCtrlExStyleName[N_TREECTRL_EX_STYLES]={"_EX_MULTISELECT|","_EX_DOUBLEBUFFER|","_EX_NOINDENTSTATE|","_EX_RICHTOOLTIP|","_EX_AUTOHSCROLL|","_EX_FADEINOUTEXPANDOS|","_EX_PARTIALCHECKBOXES|","_EX_EXCLUSIONCHECKBOXES|","_EX_DIMMEDCHECKBOXES|","_EX_DRAWIMAGEASYNC|",};
const UINT  aTreeCtrlExStyleUINT[N_TREECTRL_EX_STYLES]={TVS_EX_MULTISELECT,TVS_EX_DOUBLEBUFFER,TVS_EX_NOINDENTSTATE,TVS_EX_RICHTOOLTIP,TVS_EX_AUTOHSCROLL,TVS_EX_FADEINOUTEXPANDOS,TVS_EX_PARTIALCHECKBOXES,TVS_EX_EXCLUSIONCHECKBOXES,TVS_EX_DIMMEDCHECKBOXES,TVS_EX_DRAWIMAGEASYNC,};
const UINT  aTreeCtrlExStyleMask[N_TREECTRL_EX_STYLES]={TVS_EX_MULTISELECT,TVS_EX_DOUBLEBUFFER,TVS_EX_NOINDENTSTATE,TVS_EX_RICHTOOLTIP,TVS_EX_AUTOHSCROLL,TVS_EX_FADEINOUTEXPANDOS,TVS_EX_PARTIALCHECKBOXES,TVS_EX_EXCLUSIONCHECKBOXES,TVS_EX_DIMMEDCHECKBOXES,TVS_EX_DRAWIMAGEASYNC,};

const char *aRTFOptionName[N_RTF_OPTIONS]={"_AUTOWORDSELECTION|","_AUTOVSCROLL|","_AUTOHSCROLL|","_NOHIDESEL|","_READONLY|","_WANTRETURN|","_SAVESEL|","_SELECTIONBAR|","_VERTICAL|",};
const UINT  aRTFOptionUINT[N_RTF_OPTIONS]={ECO_AUTOWORDSELECTION,ECO_AUTOVSCROLL,ECO_AUTOHSCROLL,ECO_NOHIDESEL,ECO_READONLY,ECO_WANTRETURN,ECO_SAVESEL,ECO_SELECTIONBAR,ECO_VERTICAL,};
const UINT  aRTFOptionMask[N_RTF_OPTIONS]={ECO_AUTOWORDSELECTION,ECO_AUTOVSCROLL,ECO_AUTOHSCROLL,ECO_NOHIDESEL,ECO_READONLY,ECO_WANTRETURN,ECO_SAVESEL,ECO_SELECTIONBAR,ECO_VERTICAL,};

const char *aStatusBarCtrlStyleName[N_STATUSBARCTRL_STYLES]={"_SIZEGRIP|","_TOOLTIPS|","_OWNERDRAW|","_NOBORDERS|","_POPOUT|","_RTLREADING|","_NOTABPARSING|",};
const UINT  aStatusBarCtrlStyleUINT[N_STATUSBARCTRL_STYLES]={SBARS_SIZEGRIP,SBT_TOOLTIPS,SBT_OWNERDRAW,SBT_NOBORDERS,SBT_POPOUT,SBT_NOTABPARSING,};
const UINT  aStatusBarCtrlStyleMask[N_STATUSBARCTRL_STYLES]={SBARS_SIZEGRIP,SBT_TOOLTIPS,SBT_OWNERDRAW,SBT_NOBORDERS,SBT_POPOUT,SBT_NOTABPARSING,};

const char *aStatusBarStyleName[N_STATUSBAR_STYLES]={"_SIZEGRIP|","_TOOLTIPS|","_OWNERDRAW|","_NOBORDERS|","_POPOUT|","_RTLREADING|","_NOTABPARSING|",};
const UINT  aStatusBarStyleUINT[N_STATUSBAR_STYLES]={SBARS_SIZEGRIP,SBT_TOOLTIPS,SBT_OWNERDRAW,SBT_NOBORDERS,SBT_POPOUT,SBT_RTLREADING,SBT_NOTABPARSING,};
const UINT  aStatusBarStyleMask[N_STATUSBAR_STYLES]={SBARS_SIZEGRIP,SBT_TOOLTIPS,SBT_OWNERDRAW,SBT_NOBORDERS,SBT_POPOUT,SBT_RTLREADING,SBT_NOTABPARSING,};

const char *aToolBarCtrlStyleName[N_TOOLBARCTRL_STYLES]={"_SEP|","_CHECK|","_GROUP|","_CHECKGROUP|","_DROPDOWN|","_AUTOSIZE|","_NOPREFIX|","_TOOLTIPS|","_WRAPABLE|","_ALTDRAG|","_FLAT|","_LIST|","_CUSTOMERASE|","_REGISTERDROP|","_TRANSPARENT|","_SHOWTEXT|","_WHOLEDROPDOWN|",};
const UINT  aToolBarCtrlStyleUINT[N_TOOLBARCTRL_STYLES]={TBSTYLE_SEP,TBSTYLE_CHECK,TBSTYLE_GROUP,TBSTYLE_CHECKGROUP,TBSTYLE_DROPDOWN,TBSTYLE_AUTOSIZE,TBSTYLE_NOPREFIX,TBSTYLE_TOOLTIPS,TBSTYLE_WRAPABLE,TBSTYLE_ALTDRAG,TBSTYLE_FLAT,TBSTYLE_LIST,TBSTYLE_CUSTOMERASE,TBSTYLE_REGISTERDROP,TBSTYLE_TRANSPARENT,BTNS_SHOWTEXT,BTNS_WHOLEDROPDOWN,};
const UINT  aToolBarCtrlStyleMask[N_TOOLBARCTRL_STYLES]={TBSTYLE_SEP,TBSTYLE_CHECK,TBSTYLE_GROUP,TBSTYLE_CHECKGROUP,TBSTYLE_DROPDOWN,TBSTYLE_AUTOSIZE,TBSTYLE_NOPREFIX,TBSTYLE_TOOLTIPS,TBSTYLE_WRAPABLE,TBSTYLE_ALTDRAG,TBSTYLE_FLAT,TBSTYLE_LIST,TBSTYLE_CUSTOMERASE,TBSTYLE_REGISTERDROP,TBSTYLE_TRANSPARENT,BTNS_SHOWTEXT,BTNS_WHOLEDROPDOWN,};

const char *aToolBarCtrlExStyleName[N_TOOLBARCTRL_EX_STYLES]={"_EX_DRAWDDARROWS|","_EX_HIDECLIPPEDBUTTONS|","_EX_MIXEDBUTTONS|","_EX_DOUBLEBUFFER|",};
const UINT  aToolBarCtrlExStyleUINT[N_TOOLBARCTRL_EX_STYLES]={TBSTYLE_EX_DRAWDDARROWS,TBSTYLE_EX_HIDECLIPPEDBUTTONS,TBSTYLE_EX_MIXEDBUTTONS,TBSTYLE_EX_DOUBLEBUFFER,};
const UINT  aToolBarCtrlExStyleMask[N_TOOLBARCTRL_EX_STYLES]={TBSTYLE_EX_DRAWDDARROWS,TBSTYLE_EX_HIDECLIPPEDBUTTONS,TBSTYLE_EX_MIXEDBUTTONS,TBSTYLE_EX_DOUBLEBUFFER,};

const char *aReBarCtrlStyleName[N_REBARCTRL_STYLES]={"RBS_TOOLTIPS|","RBS_VARHEIGHT|","RBS_BANDBORDERS|","RBS_FIXEDORDER|","RBS_REGISTERDROP|","RBS_AUTOSIZE|","RBS_VERTICALGRIPPER|","RBS_DBLCLKTOGGLE|",};
const UINT  aReBarCtrlStyleUINT[N_REBARCTRL_STYLES]={RBS_TOOLTIPS,RBS_VARHEIGHT,RBS_BANDBORDERS,RBS_FIXEDORDER,RBS_REGISTERDROP,RBS_AUTOSIZE,RBS_VERTICALGRIPPER,RBS_DBLCLKTOGGLE,};
const UINT  aReBarCtrlStyleMask[N_REBARCTRL_STYLES]={RBS_TOOLTIPS,RBS_VARHEIGHT,RBS_BANDBORDERS,RBS_FIXEDORDER,RBS_REGISTERDROP,RBS_AUTOSIZE,RBS_VERTICALGRIPPER,RBS_DBLCLKTOGGLE,};

const char *aOLECMDIDName[N_OLECMDID]={
		"OLECMDID_ZOOM","OLECMDID_UPDATEPAGESTATUS","OLECMDID_UPDATECOMMANDS","OLECMDID_UNDO","OLECMDID_STOPDOWNLOAD",
		"OLECMDID_STOP","OLECMDID_SPELL","OLECMDID_SHOWSCRIPTERROR","OLECMDID_SHOWPRINT","OLECMDID_SHOWPAGESETUP",
		"OLECMDID_SHOWMESSAGE","OLECMDID_SHOWFIND","OLECMDID_SETTITLE","OLECMDID_SETPROGRESSTEXT","OLECMDID_SETPROGRESSPOS",
		"OLECMDID_SETPROGRESSMAX","OLECMDID_SETPRINTTEMPLATE","OLECMDID_SETDOWNLOADSTATE","OLECMDID_SELECTALL","OLECMDID_SAVECOPYAS",
		"OLECMDID_SAVEAS","OLECMDID_SAVE","OLECMDID_REFRESH","OLECMDID_REDO","OLECMDID_PROPERTYBAG2",
		"OLECMDID_PROPERTIES","OLECMDID_PRINTPREVIEW2","OLECMDID_PRINTPREVIEW","OLECMDID_PRINT2","OLECMDID_PRINT",
		"OLECMDID_PREREFRESH","OLECMDID_PASTESPECIAL","OLECMDID_PASTE","OLECMDID_PAGESETUP","OLECMDID_OPEN",
		"OLECMDID_ONUNLOAD","OLECMDID_ONTOOLBARACTIVATED","OLECMDID_NEW","OLECMDID_HTTPEQUIV_DONE","OLECMDID_HTTPEQUIV",
		"OLECMDID_HIDETOOLBARS","OLECMDID_GETZOOMRANGE","OLECMDID_GETPRINTTEMPLATE","OLECMDID_FIND","OLECMDID_ENABLE_INTERACTION",
		"OLECMDID_DONTDOWNLOADCSS","OLECMDID_DELETE","OLECMDID_CUT","OLECMDID_COPY","OLECMDID_CLOSE",
		"OLECMDID_CLEARSELECTION","OLECMDID_ALLOWUILESSSAVEAS",
		};
const UINT  aOLECMDIDUINT[N_OLECMDID]={
		OLECMDID_ZOOM,OLECMDID_UPDATEPAGESTATUS,OLECMDID_UPDATECOMMANDS,OLECMDID_UNDO,OLECMDID_STOPDOWNLOAD,
		OLECMDID_STOP,OLECMDID_SPELL,OLECMDID_SHOWSCRIPTERROR,OLECMDID_SHOWPRINT,OLECMDID_SHOWPAGESETUP,
		OLECMDID_SHOWMESSAGE,OLECMDID_SHOWFIND,OLECMDID_SETTITLE,OLECMDID_SETPROGRESSTEXT,OLECMDID_SETPROGRESSPOS,
		OLECMDID_SETPROGRESSMAX,OLECMDID_SETPRINTTEMPLATE,OLECMDID_SETDOWNLOADSTATE,OLECMDID_SELECTALL,OLECMDID_SAVECOPYAS,
		OLECMDID_SAVEAS,OLECMDID_SAVE,OLECMDID_REFRESH,OLECMDID_REDO,OLECMDID_PROPERTYBAG2,
		OLECMDID_PROPERTIES,OLECMDID_PRINTPREVIEW2,OLECMDID_PRINTPREVIEW,OLECMDID_PRINT2,OLECMDID_PRINT,
		OLECMDID_PREREFRESH,OLECMDID_PASTESPECIAL,OLECMDID_PASTE,OLECMDID_PAGESETUP,OLECMDID_OPEN,
		OLECMDID_ONUNLOAD,OLECMDID_ONTOOLBARACTIVATED,OLECMDID_NEW,OLECMDID_HTTPEQUIV_DONE,OLECMDID_HTTPEQUIV,
		OLECMDID_HIDETOOLBARS,OLECMDID_GETZOOMRANGE,OLECMDID_GETPRINTTEMPLATE,OLECMDID_FIND,OLECMDID_ENABLE_INTERACTION,
		OLECMDID_DONTDOWNLOADCSS,OLECMDID_DELETE,OLECMDID_CUT,OLECMDID_COPY,OLECMDID_CLOSE,
		OLECMDID_CLEARSELECTION,OLECMDID_ALLOWUILESSSAVEAS,
		};



const char *cArrBytesName[]={
	"NUL","SOH","STX","ETX","EOT","ENQ","ACK","BEL",
	"BS","HT","LF","VT","FF","CR","SO","SI",
	"DLE","DC1","DC2","DC3","DC4","NAK","SYN","ETB",
	"CAN","EM","SUB","ESC","FS","GS","RS","US",
	"WS","!","\"","#","$","%","&","'",
	"(",")","*","+",",","-",".","/",
	"0","1","2","3","4","5","6","7",
	"8","9",":",";","<","=",">","?",
	"@","A","B","C","D","E","F","G",
	"H","I","J","K","L","M","N","O",
	"P","Q","R","S","T","U","V","W",
	"X","Y","Z","[","\\","]","^","_",
	"`","a","b","c","d","e","f","g",
	"h","i","j","k","l","m","n","o",
	"p","q","r","s","t","u","v","w",
	"x","y","z","{","|","}","~","BRK",
	"Ä","Å","Ç","É","Ñ","Ö","Ü","á",
	"à","â","ä","ã","å","ç","é","è",
	"ê","ë","í","ì","î","ï","ñ","ó",
	"ò","ô","ö","õ","ú","ù","û","ü",
	"†","°","¢","£","§","•","¶","ß",
	"®","©","™","´","¨","≠","Æ","Ø",
	"∞","±","≤","≥","¥","µ","∂","∑",
	"∏","π","∫","ª","º","Ω","æ","ø",
	"¿","¡","¬","√","ƒ","≈","∆","«",
	"»","…"," ","À","Ã","Õ","Œ","œ",
	"–","—","“","”","‘","’","÷","◊",
	"ÿ","Ÿ","⁄","€","‹","›","ﬁ","ﬂ",
	"‡","·","‚","„","‰","Â","Ê","Á",
	"Ë","È","Í","Î","Ï","Ì","Ó","Ô",
	"","Ò","Ú","Û","Ù","ı","ˆ","˜",
	"¯","˘","˙","˚","¸","˝","˛","ˇ",
	};


char *clfCharSet[18]={"ANSI","BALTIC","CHINESEBIG5","DEFAULT","EASTEUROPE","GB2312","GREEK","HANGUL","MAC","OEM","RUSSIAN","SHIFTJIS","SYMBOL","TURKISH","JOHAB","HEBREW","ARABIC","THAI",};
UINT  ulfCharSet[18]={ANSI_CHARSET,BALTIC_CHARSET,CHINESEBIG5_CHARSET,DEFAULT_CHARSET,EASTEUROPE_CHARSET,GB2312_CHARSET,GREEK_CHARSET,HANGUL_CHARSET,MAC_CHARSET,OEM_CHARSET,RUSSIAN_CHARSET,SHIFTJIS_CHARSET,SYMBOL_CHARSET,TURKISH_CHARSET,JOHAB_CHARSET,HEBREW_CHARSET,ARABIC_CHARSET,THAI_CHARSET,};
char *clfOutPrecision[9]={"CHARACTER","DEFAULT","DEVICE","OUTLINE","RASTER","STRING","STROKE","TT_ONLY","TT",};
UINT  ulfOutPrecision[9]={OUT_CHARACTER_PRECIS,OUT_DEFAULT_PRECIS,OUT_DEVICE_PRECIS,OUT_OUTLINE_PRECIS,OUT_RASTER_PRECIS,OUT_STRING_PRECIS,OUT_STROKE_PRECIS,OUT_TT_ONLY_PRECIS,OUT_TT_PRECIS,};
char *clfClipPrecision[7]={"DEFAULT","CHARACTER","STROKE","MASK","EMBEDDED","LH","TT",};
UINT  ulfClipPrecision[7]={CLIP_DEFAULT_PRECIS,CLIP_CHARACTER_PRECIS,CLIP_STROKE_PRECIS,CLIP_MASK,CLIP_EMBEDDED,CLIP_LH_ANGLES,CLIP_TT_ALWAYS,};
char *clfQuality[6]={"DEFAULT","DRAFT","PROOF","ANTIALIASED","CLEARTYPE","NONANTIALIASED",};
UINT  ulfQuality[6]={DEFAULT_QUALITY,DRAFT_QUALITY,PROOF_QUALITY,ANTIALIASED_QUALITY,CLEARTYPE_QUALITY,NONANTIALIASED_QUALITY,};
char *clfPitchAndFamily[18]={"DECOR","DONTCARE","MODERN","ROMAN","SCRIPT","SWISS","FIX_DECOR","FIX_DONTCARE","FIX_MODERN","FIX_ROMAN","FIX_SCRIPT","FIX_SWISS","VAR_DECOR","VAR_DONTCARE","VAR_MODERN","VAR_ROMAN","VAR_SCRIPT","VAR_SWISS",};
UINT  ulfPitchAndFamily[18]={DEFAULT_PITCH|FF_DECORATIVE,DEFAULT_PITCH|FF_DONTCARE,DEFAULT_PITCH|FF_MODERN,DEFAULT_PITCH|FF_ROMAN,DEFAULT_PITCH|FF_SCRIPT,DEFAULT_PITCH|FF_SWISS,FIXED_PITCH|FF_DECORATIVE,FIXED_PITCH|FF_DONTCARE,FIXED_PITCH|FF_MODERN,FIXED_PITCH|FF_ROMAN,FIXED_PITCH|FF_SCRIPT,FIXED_PITCH|FF_SWISS,VARIABLE_PITCH|FF_DECORATIVE,VARIABLE_PITCH|FF_DONTCARE,VARIABLE_PITCH|FF_MODERN,VARIABLE_PITCH|FF_ROMAN,VARIABLE_PITCH|FF_SCRIPT,VARIABLE_PITCH|FF_SWISS,};

const char *aUnitCommonMessages="OnSetFocus,OnKillFocus,OnCSetFocus,OnCKillFocus,OnTimer,OnClose,OnEnter,OnLockEnter,OnCtrlEnter,OnLockCtrlEnter,OnTab,OnBackTab,OnLockTab,OnLockBackTab,OnDrop,OnDragHover,OnDragMove,OnDragLeave,OnValChange,OnValChangeEx,OnLockWheel,";

const char *aUnitMessage[50];


/////////////////////////////////////////////////////////////////////////////
// CGP_TermApp

BEGIN_MESSAGE_MAP(CGP_TermApp, CWinApp)
	//{{AFX_MSG_MAP(CGP_TermApp)
	ON_COMMAND(ID_APP_ABOUT, OnAppAbout)
		// NOTE - the ClassWizard will add and remove mapping macros here.
		//    DO NOT EDIT what you see in these blocks of generated code!
	//}}AFX_MSG_MAP
	// Standard file based document commands
	ON_COMMAND(ID_FILE_NEW, CWinApp::OnFileNew)
	ON_COMMAND(ID_FILE_OPEN, CWinApp::OnFileOpen)
	// Standard print setup command
	ON_COMMAND(ID_FILE_PRINT_SETUP, CWinApp::OnFilePrintSetup)
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CGP_TermApp construction

HANDLE m_WaitAll;
BOOL m_StopPaint;
BOOL m_StopWorking;
CFindReplaceDialog *FRDlg;

CGP_TermApp::CGP_TermApp()
{

	aUnitMessage[GPUnit::UT_MAINDLGSCR]		="OnOk,OnCancel,";
	aUnitMessage[GPUnit::UT_CONTROL]		="OnCancel,OnOk,";
	aUnitMessage[GPUnit::UT_DRAW]			="OnCancel,OnOk,";
	aUnitMessage[GPUnit::UT_ANISTATIC]		="OnClicked,ParentNotify,";
	aUnitMessage[GPUnit::UT_ANIBUTTON]		="OnClicked,OnDoubleclicked,OnCheck,OnUncheck,OnIndeterminate,OnCheckChanged,OnAutoClick,OnRAutoClick,OnPaint,OnHilite,OnUnhilite,OnDisable,OnPush,OnFocus,";
	aUnitMessage[GPUnit::UT_FRAMEBAR]		="OnCancel,OnOk,";
	aUnitMessage[GPUnit::UT_DATETIMECTRL]	="OnCloseup,OnDatetimechange,OnDropdown,OnFormat,OnFormatquery,OnUserstring,OnWmkeydown,ParentNotify,";
	aUnitMessage[GPUnit::UT_DLGBAR]			="OnCancel,OnOk,";
	aUnitMessage[GPUnit::UT_RTF]			="OnChange,OnChangeEx,OnChangeVP,OnErrspace,OnHscroll,OnMaxtext,OnUpdate,OnVscroll,OnMsgfilter,OnRequestresize,OnSelchange,OnDropfiles,OnProtected,OnCorrecttext,OnStopnoundo,OnImechange,OnSaveclipboard,OnOleopfailed,OnObjectpositions,OnDragdropdone,OnParagraphexpanded,OnAlignltr,OnAlignrtl,OnLink,OnNotifyKillfocus,OnNotifySetfocus,OnALIGN_LTR_EC,OnALIGN_RTL_EC,";
	aUnitMessage[GPUnit::UT_TREECTRL]		="OnClick,OnDblclk,OnOutofmemory,OnRclick,OnRdblclk,OnReturn,OnBegindrag,OnBeginlabeledit,OnBeginrdrag,OnDeleteitem,OnEndlabeledit,OnCancellabeledit,OnGetdispinfo,OnItemexpanded,OnKeydown,OnItemexpanding,OnSelchanged,OnSelchanging,OnSelchangedEx,OnSelchangingEx,OnSetdispinfo,ParentNotify,OnSingleExpand,OnGetInfotip,OnHelper,OnNotifyKillfocus,OnNotifySetfocus,";
	aUnitMessage[GPUnit::UT_HEADER]			="OnTrack,OnItemclick,OnItemdblclick,OnBegintrack,OnEndtrack,OnDividerdblclick,OnEnddrag,OnItemchanged,OnItemchanging,OnBegindrag,OnDblclk,OnGetdispinfo,OnFilterChange,OnFilterBtnClick,";
	aUnitMessage[GPUnit::UT_SLIDER]			="OnOutofmemory,OnReleasedcapture,OnCustomdraw,OnLineup,OnLinedown,OnPageup,OnPagedown,OnThumbPosition,OnThumbTrack,OnTop,OnBottom,OnEndTrack,";
	aUnitMessage[GPUnit::UT_TABCTRL]		="OnSelchange,OnSelchanging,OnKeydown,OnGetobject,OnRclick,OnClick,OnOutofmemory,OnFocusChange,OnReleasedCapture,";
	aUnitMessage[GPUnit::UT_SPINBUTTON]		="OnOutofmemory,OnDeltapos,OnCanged,";
	aUnitMessage[GPUnit::UT_BBUTTON]		="OnClicked,OnDoubleclicked,OnCheck,OnUncheck,OnIndeterminate,OnCheckChanged,OnAutoClick,OnRAutoClick,OnPaint,OnHilite,OnUnhilite,OnDisable,OnPush,OnFocus,";
	aUnitMessage[GPUnit::UT_STATIC]			="OnClicked,ParentNotify,OnDblClk,OnEnable,OnDisable,";
	aUnitMessage[GPUnit::UT_EDIT]			="OnHscroll,OnChange,OnChangeVP,OnErrspace,OnMaxtext,OnUpdate,OnVscroll,OnChangeEx,OnNotifyKillfocus,OnNotifySetfocus,OnALIGN_LTR_EC,OnALIGN_RTL_EC,";
	aUnitMessage[GPUnit::UT_BUTTON]			="OnClicked,OnDoubleclicked,OnCheck,OnUncheck,OnIndeterminate,OnCheckChanged,OnAutoClick,OnRAutoClick,OnPaint,OnHilite,OnUnhilite,OnDisable,OnPush,OnFocus,";
	aUnitMessage[GPUnit::UT_LISTBOX]		="OnSelchange,OnDblclk,OnErrspace,OnSelcancel,Onclk,OnNotifyKillfocus,OnNotifySetfocus,";
	aUnitMessage[GPUnit::UT_COMBOBOX]		="OnEditchange,OnCloseup,OnDblclk,OnDropdown,OnEditupdate,OnErrspace,OnSelchange,OnSelendcancel,OnSelendok,OnNotifyKillfocus,OnNotifySetfocus,";
	aUnitMessage[GPUnit::UT_SCROLLBAR]		="ParentNotify,";
	aUnitMessage[GPUnit::UT_PROGRESS]		="OnOutofmemory,";
	aUnitMessage[GPUnit::UT_ANIMAT]			="OnOutofmemory,";
	aUnitMessage[GPUnit::UT_CHECKLISTBOX]	="OnSelchange,OnDblclk,OnErrspace,OnSelcancel,Onclk,OnNotifyKillfocus,OnNotifySetfocus,OnCheck,";
	aUnitMessage[GPUnit::UT_DRAGLISTBOX]	="OnSelchange,OnDblclk,OnErrspace,OnSelcancel,Onclk,OnNotifyKillfocus,OnNotifySetfocus,OnBeginDrag,";
	aUnitMessage[GPUnit::UT_LISTCTRL]		="OnClick,OnDblclk,OnCSetFocusEx,OnCKillFocusEx,OnOutofmemory,OnRclick,OnRdblclk,OnReturn,OnBegindrag,OnHdrBegindrag,OnBeginlabeledit,OnBeginrdrag,OnColumnclick,OnDeleteallitems,OnDeleteitem,OnEndlabeledit,OnHdrGetdispinfo,OnGetdispinfo,OnInsertitem,OnItemchanged,OnItemchanging,OnKeydown,OnSetdispinfo,OnOdcachehint,OnOdfinditem,OnOdstatechanged,OnHdrTrack,OnHdrItemclick,OnHdrItemdblclick,OnHdrBegintrack,OnHdrEndtrack,OnDividerdblclick,OnHdrEnddrag,OnSelchange,OnEditPos,OnEditPosEx,OnCheck,OnClearSubItem,OnHdrFilterChange,OnHdrFilterBtnClick,OnLUPTest,OnRUPTest,OnItemTextReflect,OnHdrItemchanged,OnHdrItemchanging,OnChangeLine,OnChangeColumn,OnEndOfTable,OnBeginScroll,OnEndScroll,OnGetInfotip,OnHotTrack,OnItemActivate,OnMarqueeBegin,OnSubItemClick,OnSubItemDblclk,OnKeydownOnEnd,OnKeydownOnBegin,OnVLRequest,";
	aUnitMessage[GPUnit::UT_STATUSBARCTRL]	="OnClick,OnDblClick,OnRClick,OnRDblClick,OnSimpleModeChange,";
	aUnitMessage[GPUnit::UT_TOOLBARCTRL]	="OnClicked,OnBeginAdjust,OnQueryInsert,OnQueryDelete,OnDropDown,OnDragOut,OnRClick,OnRDblClick,OnHotImageChange,OnToolBarChange,OnBeginDrag,OnEndDrag,OnReset,OnCustHelp,OnNClick,OnNDblClick,OnNKillFocus,OnNOutOfMemory,OnNReturn,OnNSetFocus,OnNEndAdjust,OnDeletingButton,OnNRestore,OnNSave,OnNInitCustomize,OnNGetInfotip,OnGetButtonInfo,";
	aUnitMessage[GPUnit::UT_STATUSBAR]		="OnClick,OnDblClick,OnRClick,OnRDblClick,OnSimpleModeChange,";
	aUnitMessage[GPUnit::UT_TOOLBAR]		="OnClicked,OnBeginAdjust,OnQueryInsert,OnQueryDelete,OnDropDown,OnDragOut,OnRClick,OnRDblClick,OnHotImageChange,OnToolBarChange,OnBeginDrag,OnEndDrag,OnReset,OnCustHelp,OnNClick,OnNDblClick,OnNKillFocus,OnNOutOfMemory,OnNReturn,OnNSetFocus,";
	aUnitMessage[GPUnit::UT_DIALOGBAR]		="OnCancel,OnOk,";
	aUnitMessage[GPUnit::UT_REBARCTRL]		="OnCancel,OnOk,OnHeightChange,OnGetObject,OnLayoutChanged,OnAutoSize,OnBeginDrag,OnEndDrag,OnDeletingBand,OnDeletedBand,OnChildSize,OnChevronPushed,AutoBreak,OnMinMax,";
	aUnitMessage[GPUnit::UT_REBAR]			="OnCancel,OnOk,OnHeightChange,OnGetObject,OnLayoutChanged,OnAutoSize,OnBeginDrag,OnEndDrag,OnDeletingBand,OnDeletedBand,OnChildSize,OnChevronPushed,AutoBreak,OnMinMax,";
	aUnitMessage[GPUnit::UT_FLEXGRID]		="OnCancel,OnOk,OnLockEnter,OnFGClick,OnFGKeyDown,OnFGDblClick,OnFGKeyPress,OnFGKeyUp,OnFGMouseDown,OnFGMouseMove,OnFGMouseUp,OnFGSelChange,OnFGRowColChange,OnFGEnterCell,OnFGLeaveCell,OnFGScroll,OnFGOLEStartDrag,OnFGOLEGiveFeedback,OnFGOLESetData,OnFGOLECompleteDrag,OnFGOLEDragOver,OnFGOLEDragDrop,OnColumnClick,OnRowClick,";
	aUnitMessage[GPUnit::UT_MONTHCAL]		="ParentNotify,OnGetdaystate,OnSelchange,OnSelect,OnReleasedcapture,";
	aUnitMessage[GPUnit::UT_WEBBROWSER]		="OnCancel,OnOk,OnStatusText,OnProgress,OnCommandState,OnDownloadBegin,OnDownloadComplete,OnTitle,OnProperty,OnBeforeNavigate2,OnNewWindow2,OnNavigateComplete2,OnDocumentComplete,OnQuit,OnVisible,OnToolBar,OnMenuBar,OnStatusBar,OnFullScreen,OnTheaterMode,OnSetResizable,OnSetLeft,OnSetTop,OnSetWidth,OnSetHeight,OnClosing,OnSetSecureLockIcon,OnClientToHost,OnFileDownload,OnNavigateError,OnPrintInstantiation,OnPrintTeardown,OnUpdatePageStatus,OnPrivacyImpactedState,OnClosingA,OnFileDownloadA,OnBeforeNavigate2A,OnNewWindow2A,OnNavigateErrorA,";
	aUnitMessage[GPUnit::UT_COMBOBOXEX]		="OnEditchange,OnCloseup,OnDblclk,OnDropdown,OnEditupdate,OnErrspace,OnSelchange,OnSelendcancel,OnSelendok,OnNotifyKillfocus,OnNotifySetfocus,OnInsertItem,OnDeleteItem,OnBeginEdit,OnDragBegin,OnEndEdit,";
	aUnitMessage[GPUnit::UT_EDITOR]			="OnENChange,OnENKillFocus,OnENSetFocus,OnModified,OnUpdateUI,OnCharAdded,OnStyleNeeded,OnPainted,OnSavepointLeft,OnDoubleClick,OnCallTipClick,OnDWellEnd,OnDWellStart,OnHotspotClick,OnHotspotDoubleclick,OnKey,OnMacroRecord,OnMarginClick,OnModifyAttemptRO,OnNeedShown,OnSavepointReached,OnURIDropped,OnUserListSelection,OnZoom,OnAutocSelection,";
				


/*
	char SIMPL[]={
		0xD5,0xE6,0xD5,0xFD,0xD6,0xAE,0xBB,0xF5,
		0xC3,0xFB,0xC7,0xB7,0xC8,0xB1,0xD6,0xBB,
		0xD6,0xAA,0xCE,0xAA,0xC6,0xD5,0xCD,0xA8,
		0xBB,0xF5,0xC6,0xB7,0x0,0x0,0x0,0x0,
	};
	char TRAD[]={
		0xAF,0x75,0xA5,0xBF,0xA4,0xA7,0xB3,0x66,
		0xA6,0x57,0xA4,0xED,0xAF,0xCA,0xA5,0x75,
		0xAA,0xBE,0xAC,0xB0,0xB4,0xB6,0xB3,0x71,
		0xB3,0x66,0xAB,0x7E,0x0,0x0,0x0,0x0,
	};

0xBB,0xF5,0xCE,0xAA,0xBB,0xF5
0xB3,0x66,0xAC,0xB0,0xB6,0x55

*/
/*	char SIMPLe[]={
		0xD5,0xE6,0xD5,0xFD,0xD6,0xAE,0xBB,0xF5,
		0xC3,0xFB,0xC7,0xB7,0xC8,0xB1,0xD6,0xBB,
		0xD6,0xAA,0xD6,0xAA,0xC6,0xD5,0xCD,0xA8,
		0xBB,0xF5,0xC6,0xB7,0x0,0x0,0x0,0x0,
	};
	char TRADe[]={
		0xAF,0x75,0xA5,0xBF,0xA4,0xA7,0xB3,0x66,
		0xA6,0x57,0xA4,0xED,0xAF,0xCA,0xA5,0x75,
		0xAA,0xBE,0xAA,0xBE,0xB4,0xB6,0xB3,0x71,
		0xB3,0x66,0xAB,0x7E,0x0,0x0,0x0,0x0,
	};

	
	unsigned short tmpwstr[100];

	DWORD cparr[8]={51936,936,52936,10008,950,20000,20002,10002,};
	DWORD dwMapFlags[3]={0,LCMAP_SIMPLIFIED_CHINESE,LCMAP_TRADITIONAL_CHINESE,};
	DWORD dwMapFlags2[2]={0,LCMAP_BYTEREV,};
	DWORD dwMapFlags3[3]={0,LCMAP_FULLWIDTH,LCMAP_HALFWIDTH,};
	
	DWORD dwSortId[5]={SORT_CHINESE_BIG5,SORT_CHINESE_BOPOMOFO,SORT_CHINESE_PRC,SORT_CHINESE_PRCP,SORT_CHINESE_UNICODE,};
	DWORD dwSubLangId[5]={SUBLANG_CHINESE_TRADITIONAL,SUBLANG_CHINESE_SIMPLIFIED,SUBLANG_CHINESE_HONGKONG,SUBLANG_CHINESE_SINGAPORE,SUBLANG_CHINESE_MACAU,};


	for(int inArr=14;inArr<15;inArr++)
	for(int icparr=0;icparr<8;icparr++)
	for(int icparr2=0;icparr2<8;icparr2++)
	for(int idwSortId=0;idwSortId<5;idwSortId++)
	for(int idwSubLangId=0;idwSubLangId<5;idwSubLangId++)
	{
		DWORD lng=MAKELCID(MAKELANGID(LANG_CHINESE,dwSubLangId[idwSubLangId]),dwSortId[idwSortId]);

		for(int idwMapFlags=0;idwMapFlags<3;idwMapFlags++)
		for(int idwMapFlags2=0;idwMapFlags2<2;idwMapFlags2++)
		for(int idwMapFlags3=0;idwMapFlags3<3;idwMapFlags3++)
		{
			char cnv[50]={0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,};
			char cnv2[50]={0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,};

	char SIMPL[]={
		0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	};
	char TRAD[]={
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
	};
	for(int j=0;j<inArr*2;j++)
	{
		SIMPL[j]=SIMPLe[j];
		TRAD[j]=TRADe[j];
	}

int i;

			MultiByteToWideChar(cparr[icparr], 0, SIMPL, inArr*2, tmpwstr, inArr);
			WideCharToMultiByte(cparr[icparr2], 0, tmpwstr, inArr, cnv, inArr*2, NULL, FALSE);
			::LCMapString(lng,dwMapFlags[idwMapFlags]|dwMapFlags2[idwMapFlags2]|dwMapFlags3[idwMapFlags3] 
				,cnv,inArr*2,cnv2,inArr*2);

			for( i=0;i<inArr*2 && cnv2[i]==TRAD[i];i++);

				if (i>=inArr*2)
				{
					i=i;
				}


			::LCMapString(lng,dwMapFlags[idwMapFlags]|dwMapFlags2[idwMapFlags2]|dwMapFlags3[idwMapFlags3] 
				,SIMPL,inArr*2,cnv2,inArr*2);

			for( i=0;i<inArr*2 && cnv2[i]==TRAD[i];i++);

				if (i>=inArr*2)
				{
					i=i;
				}

			::LCMapString(lng,dwMapFlags[idwMapFlags]|dwMapFlags2[idwMapFlags2]|dwMapFlags3[idwMapFlags3] 
				,SIMPL,inArr*2,cnv2,inArr*2);

			MultiByteToWideChar(cparr[icparr], 0, cnv2, inArr*2, tmpwstr, inArr);
			WideCharToMultiByte(cparr[icparr2], 0, tmpwstr, inArr, cnv2, inArr*2, NULL, FALSE);

			for( i=0;i<inArr*2 && cnv2[i]==TRAD[i];i++);

				if (i>=inArr*2)
				{
					i=i;
				}


		}
	}

	int jj;
	jj=0;

*/
}

/////////////////////////////////////////////////////////////////////////////
// The one and only CGP_TermApp object

CGP_TermApp theApp;

// This identifier was generated to be statistically unique for your app.
// You may change it if you prefer to choose a specific identifier.

// {1509E7A6-DD4C-11D3-970D-0080AD863699}
static const CLSID clsid =
{ 0x1509e7a6, 0xdd4c, 0x11d3, { 0x97, 0xd, 0x0, 0x80, 0xad, 0x86, 0x36, 0x99 } };

/////////////////////////////////////////////////////////////////////////////
// CGP_TermApp initialization


BOOL CGP_TermApp::InitInstance()
{
	if (!AfxSocketInit())
	{
		AfxMessageBox(IDP_SOCKETS_INIT_FAILED);
		return FALSE;
	}

	// Initialize OLE libraries
	if (!AfxOleInit())
	{
		AfxMessageBox(IDP_OLE_INIT_FAILED);
		return FALSE;
	}

	if (!InitATL())
		return FALSE;

	AfxEnableControlContainer();

	// Standard initialization
	// If you are not using these features and wish to reduce the size
	//  of your final executable, you should remove from the following
	//  the specific initialization routines you do not need.

#ifndef _VC80_UPGRADE
	#ifdef _AFXDLL
			Enable3dControls();			// Call this when using MFC in a shared DLL
	#else
		Enable3dControlsStatic();	// Call this when linking to MFC statically
	#endif
#endif

	// Change the registry key under which our settings are stored.
	// TODO: You should modify this string to be something appropriate
	// such as the name of your company or organization.
#ifdef BRIZ
	SetRegistryKey(_T("INFOTOOLS Applications"));
#else
	SetRegistryKey(_T("Local AppWizard-Generated Applications"));
#endif
	{
		#ifdef RUS
			GPC.csLocaleStr=AfxGetApp()->GetProfileString(GPC.cs_RegTermViewSetName, "LOCALESTR",".1251");
		#else
			GPC.csLocaleStr=AfxGetApp()->GetProfileString(GPC.cs_RegTermViewSetName, "LOCALESTR","");
		#endif
		setlocale( LC_ALL, GPC.csLocaleStr );
		setlocale( LC_NUMERIC, "English_USA.1252");
	}

	LoadStdProfileSettings();  // Load standard INI file options (including MRU)

	// Register the application's document templates.  Document templates
	//  serve as the connection between documents, frame windows and views.

	CSingleDocTemplate* pDocTemplate;
	pDocTemplate = new CSingleDocTemplate(
		IDR_GP_TERTYPE, /*IDR_MAINFRAME*/
		RUNTIME_CLASS(CGP_TermDoc),
		RUNTIME_CLASS(CMainFrame),       // main SDI frame window
		RUNTIME_CLASS(CGP_TermView));
	pDocTemplate->SetContainerInfo(IDR_CNTR_INPLACE);
	pDocTemplate->SetServerInfo(
		IDR_SRVR_EMBEDDED, IDR_SRVR_INPLACE,
		RUNTIME_CLASS(CInPlaceFrame));
	AddDocTemplate(pDocTemplate);



	// Connect the COleTemplateServer to the document template.
	//  The COleTemplateServer creates new documents on behalf
	//  of requesting OLE containers by using information
	//  specified in the document template.
	m_server.ConnectTemplate(clsid, pDocTemplate, FALSE);
		// Note: SDI applications register server objects only if /Embedding
		//   or /Automation is present on the command line.

	// Enable DDE Execute open
	EnableShellOpen();
	RegisterShellFileTypes(TRUE);

	// Parse command line for standard shell commands, DDE, file open
	CCommandLineInfo cmdInfo;
	ParseCommandLine(cmdInfo);

	cmdInfo.m_bShowSplash=AfxGetApp()->GetProfileInt(GPC.cs_RegTermViewSetName, "ShowSplash",1);
	CSplashWnd::EnableSplashScreen(cmdInfo.m_bShowSplash);

    _Module.UpdateRegistryFromResource(IDR_GP_TERM, TRUE);
	_Module.RegisterServer(TRUE);

/////////////	COleTemplateServer::RegisterAll();

	_Module.RegisterClassObjects(CLSCTX_LOCAL_SERVER, 	REGCLS_MULTIPLEUSE);

	ScintillaWin::Register(AfxGetInstanceHandle());
	COleTemplateServer::RegisterAll();

	// Check to see if launched as OLE server
	if (cmdInfo.m_bRunEmbedded || cmdInfo.m_bRunAutomated)
	{
		// Register all OLE server (factories) as running.  This enables the
		//  OLE libraries to create objects from other applications.
		COleTemplateServer::RegisterAll();
		// Application was run with /Embedding or /Automation.  Don't show the
		//  main window in this case.
		return TRUE;
	}

	// When a server application is launched stand-alone, it is a good idea
	//  to update the system registry in case it has been damaged.
	m_server.UpdateRegistry(OAT_DOC_OBJECT_SERVER);
	COleObjectFactory::UpdateRegistryAll();

	{
		char buffer[_MAX_PATH];
		if (!_getcwd( buffer, _MAX_PATH )) *buffer=0;
		AfxGetApp()->WriteProfileString(GPC.cs_RegTermViewSetName, "LastInitPath",buffer);
	}

#ifdef BRIZ
	if (AfxGetApp()->GetProfileInt(GPC.cs_RegTermViewSetName, "STERMENABLE",0)==1)
#else
	if (AfxGetApp()->GetProfileInt(GPC.cs_RegTermViewSetName, "STERMENABLE",1)==1)
#endif
	{
		HANDLE hQuit=CreateEvent(NULL,TRUE,FALSE,"GP_TERMproccess");
		if (GetLastError()== ERROR_ALREADY_EXISTS)
		{
			if (AfxGetApp()->GetProfileInt(GPC.cs_RegTermViewSetName, "STERMWARNING",1)==1)
				AfxMessageBox(IDS_SINGLETERMWARNING);
			return FALSE;
		}
	}

	GPC.InitialLoad();

	// Dispatch commands specified on the command line
	if (!ProcessShellCommand(cmdInfo))
		return FALSE;

	// The one and only window has been initialized, so show and update it.

	m_pMainWnd->ShowWindow((GPC.dw_StartFlags&GP_STRTFLG_HIDE)?SW_HIDE:SW_SHOW);
	m_pMainWnd->UpdateWindow();
	if (AfxGetApp()->GetProfileInt(GPC.cs_RegTermViewSetName, "ShowSplash",1))
		CSplashWnd::ShowSplashScreen(m_pMainWnd);

	// Enable drag/drop open
	m_pMainWnd->DragAcceptFiles();
	srand((int)CTime::GetCurrentTime().GetTime());
	
   	Scintilla_RegisterClasses(AfxGetInstanceHandle());

	return TRUE;
}


/////////////////////////////////////////////////////////////////////////////
// CAboutDlg dialog used for App About

class CAboutDlg : public CDialog
{
public:
	CAboutDlg();

// Dialog Data
	//{{AFX_DATA(CAboutDlg)
	enum { IDD = IDD_ABOUTBOX };
	//}}AFX_DATA

	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CAboutDlg)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support
	//}}AFX_VIRTUAL

// Implementation
protected:
	//{{AFX_MSG(CAboutDlg)
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};

CAboutDlg::CAboutDlg() : CDialog(CAboutDlg::IDD)
{
	//{{AFX_DATA_INIT(CAboutDlg)
	//}}AFX_DATA_INIT
}

void CAboutDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);
	//{{AFX_DATA_MAP(CAboutDlg)
	//}}AFX_DATA_MAP
}

BEGIN_MESSAGE_MAP(CAboutDlg, CDialog)
	//{{AFX_MSG_MAP(CAboutDlg)
	//}}AFX_MSG_MAP
END_MESSAGE_MAP()

// App command to run the dialog
void CGP_TermApp::OnAppAbout()
{
	CAboutDlg aboutDlg;
	aboutDlg.DoModal();
}

/////////////////////////////////////////////////////////////////////////////
// CGP_TermApp message handlers



CGP_TermModule _Module;

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_GPTInterface, CGPTInterface)
OBJECT_ENTRY(CLSID_AutoSizing, CAutoSizing)
OBJECT_ENTRY(CLSID_Connector, CConnector)
OBJECT_ENTRY(CLSID_COMImport, CCOMImport)
END_OBJECT_MAP()

LONG CGP_TermModule::Unlock()
{
	AfxOleUnlockApp();
	return -1;
}

LONG CGP_TermModule::Lock()
{
	AfxOleLockApp();
	return 1;
}


int CGP_TermApp::ExitInstance()
{
   	Scintilla_ReleaseResources();
	if (m_bATLInited)
	{
		_Module.RevokeClassObjects();
		_Module.Term();
	}

	return CWinApp::ExitInstance();

}

BOOL CGP_TermApp::InitATL()
{
	m_bATLInited = TRUE;

	_Module.Init(ObjectMap, AfxGetInstanceHandle());
	_Module.dwThreadID = GetCurrentThreadId();

	return TRUE;

}

///////////////////////////////////////////////
///////////////////////////////////////////////
///////////////////////////////////////////////
///////////////////////////////////////////////


BOOL CGP_TermApp::PreTranslateMessage(MSG* pMsg)
{
	// CG: The following lines were added by the Splash Screen component.
	if (CSplashWnd::PreTranslateAppMessage(pMsg))	return TRUE;
	GPC.uLastMessage=0;
	BOOL ret=CWinApp::PreTranslateMessage(pMsg);
	GPC.uLastMessage=0;
	return ret;
}

///////////////////////////////////////////////
///////////////////////////////////////////////
///////////////////////////////////////////////
///////////////////////////////////////////////

void ReadColor127()
{
	CString inn;
	inn=AfxGetApp()->GetProfileString(GPC.cs_RegTermViewSetName, "RGB_cRf","1315858 255 65535 16711935 65280 16776960 16711680 16777215 0 150 46003 10027158 39168 10066176 10027008 12170936");
	m_LastScanf=sscanf(inn,"%d %d %d %d %d %d %d %d %d %d %d %d %d %d %d %d",cFEtalon,cFEtalon+1,cFEtalon+2,cFEtalon+3,cFEtalon+4,cFEtalon+5,cFEtalon+6,cFEtalon+7,cFEtalon+8,cFEtalon+9,cFEtalon+10,cFEtalon+11,cFEtalon+12,cFEtalon+13,cFEtalon+14,cFEtalon+15);
	inn=AfxGetApp()->GetProfileString(GPC.cs_RegTermViewSetName, "RGB_cRb","0 242 61680 16122100 60928 14336256 15400960 15129549");
	m_LastScanf=sscanf(inn,"%d %d %d %d %d %d %d %d",cBEtalon,cBEtalon+1,cBEtalon+2,cBEtalon+3,cBEtalon+4,cBEtalon+5,cBEtalon+6,cBEtalon+7);
	int i;
	for(i=8;i<16;i++)
		cBEtalon[i]=cFEtalon[i];

	GPC.DefFrgColorInd=(AfxGetApp()->GetProfileInt(GPC.cs_RegTermViewSetName, "m_DefFrgClr",7)&0x000F);
	GPC.DefBkgColorInd=(AfxGetApp()->GetProfileInt(GPC.cs_RegTermViewSetName, "m_DefBkgClr",0));
	GPC.DefFrgColor=cFEtalon[GPC.DefFrgColorInd];
	GPC.DefBkgColor=cBEtalon[GPC.DefBkgColorInd];
	if (GPC.m_Document)
	{
		GPScreen *s=GPC.m_Document->GetActiveScreen();
		s->SetChrColorIndex(GPC.DefFrgColorInd,0);
		s->SetBkgColorIndex(GPC.DefBkgColorInd,0);
	}

	GPC.m_curOutScrBkg=AfxGetApp()->GetProfileInt(GPC.cs_RegTermViewSetName, "m_curOutScrBkg",8);
}


CDocument* CGP_TermApp::OpenDocumentFile(LPCTSTR lpszFileName)
{
	return NULL;
//	return CWinApp::OpenDocumentFile(lpszFileName);
}
#include "Connector.h"
#include "COMImport.h"
