#if !defined(AFX_GPROWCURSOR_H__10ABAC0F_4DC8_4959_93C2_A60736B56A5E__INCLUDED_)
#define AFX_GPROWCURSOR_H__10ABAC0F_4DC8_4959_93C2_A60736B56A5E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// GPCRowCursor wrapper class

class GPCRowCursor : public COleDispatchDriver
{
public:
	GPCRowCursor() {}		// Calls COleDispatchDriver default constructor
	GPCRowCursor(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	GPCRowCursor(const GPCRowCursor& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GPROWCURSOR_H__10ABAC0F_4DC8_4959_93C2_A60736B56A5E__INCLUDED_)
