// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "GP_term.h"
#include "GPWebBrowser2.h"
#include "GP_TermView.h"

// Dispatch interfaces referenced by this interface
#include "GPOleFont.h"
#include "GPPicture.h"
#include "gprowcursor.h"
//#include "occimpl.h"


const UINT GPWebBrowser2::uNMethods=56;
const char *GPWebBrowser2::cArrMethods[]={
/*00*/	"GoBack","GoForward","GoHome","GoSearch","Refresh",
/*05*/	"Refresh2","Stop","Quit","Navigate","GetType",
/*10*/	"GetLeft","SetLeft","GetTop","SetTop","GetWidth",
/*15*/	"SetWidth","GetHeight","SetHeight","GetLocationName","GetLocationURL",
/*20*/	"GetBusy","GetOffline","SetOffline","GetVisible","SetVisible",
/*25*/	"GetFullScreen","SetFullScreen","GetSilent","SetSilent","GetRegisterAsBrowser",
/*30*/	"SetRegisterAsBrowser","GetRegisterAsDropTarget","SetRegisterAsDropTarget","GetResizable","SetResizable",
/*35*/	"GetTheaterMode","SetTheaterMode","GetAddressBar","SetAddressBar","GetStatusBar",
/*40*/	"SetStatusBar","GetStatusText","SetStatusText","GetToolBar","SetToolBar",
/*45*/	"GetMenuBar","SetMenuBar","Navigate2","ClientToWindow","GetName",
/*50*/	"GetFullName","GetPath","GetReadyState","ShowBrowserBar","WBExec",
/*55*/	"WBPrint","","","","",
/*60*/	"","","","","",
	};

const char *GPWebBrowser2::cArrMethodsParams[]={
/*00*/	"","","","","",
/*05*/	"Level","","","url,Flags,TargetFrameName,PostData,Headers","",
/*10*/	"","Left","","Top","",
/*15*/	"Width","","Height","","",
/*20*/	"","","Offline","","Visible",
/*25*/	"","FullScreen","","Silent","",
/*30*/	"RegisterAsBrowser","","RegisterAsDropTarget","","Resizable",
/*35*/	"","TheaterMode","","AddressBar","",
/*40*/	"StatusBar","","StatusText","","ToolBar",
/*45*/	"","MenuBar","url,Flags,TargetFrameName,PostData,Headers","CX,CY","",
/*50*/	"","","","","",
/*55*/	"[PrintDialog][,Template File]","","","","",
/*60*/	"","","","","",
	};
/*
PutProperty
GetProperty_


QueryStatusWB
GetHwnd
GetParent
GetContainer
GetApplication
GetDocument
GetTopLevelContainer
*/
/////////////////////////////////////////////////////////////////////////////
// GPWebBrowser2

const UINT GPWebBrowser2::uNRefrLevel=10;
const char *GPWebBrowser2::cArrRefrLevel[10]={
		"REFRESH_NORMAL","REFRESH_IFEXPIRED","REFRESH_CONTINUE","REFRESH_COMPLETELY","REFRESH_NO_CACHE",
		"REFRESH_RELOAD","REFRESH_LEVELMASK","REFRESH_CLEARUSERINPUT","REFRESH_PROMPTIFOFFLINE","REFRESH_THROUGHSCRIPT",
	};
const UINT GPWebBrowser2::uArrRefrLevel[10]={
		REFRESH_NORMAL,REFRESH_IFEXPIRED,RFRSH_CONTINUE,REFRESH_COMPLETELY,RFRSH_NO_CACHE,
		RFRSH_RELOAD,RFRSH_LEVELMASK,RFRSH_CLEARUSERINPUT,RFRSH_PROMPTIFOFFLINE,RFRSH_THROUGHSCRIPT,
	};

const UINT GPWebBrowser2::uNNavConst=7;
const char *GPWebBrowser2::cArrNavConst[7]={
		"NAVOPENINNEWWINDOW","NAVNOHISTORY","NAVNOREADFROMCACHE","NAVNOWRITETOCACHE","NAVALLOWAUTOSEARCH",
		"NAVBROWSERBAR","NAVHYPERLINK",
	};
const UINT GPWebBrowser2::uArrNavConst[7]={
		navOpenInNewWindow,navNoHistory,navNoReadFromCache,navNoWriteToCache,navAllowAutosearch,
		navBrowserBar,navHyperlink,
	};

const UINT GPWebBrowser2::uNHStatus=39;
const char *GPWebBrowser2::cArrHStatus[39]={
		"HS_CONTINUE","HS_SWITCH_PROTOCOLS","HS_OK","HS_CREATED","HS_ACCEPTED",
		"HS_PARTIAL","HS_NO_CONTENT","HS_RESET_CONTENT","HS_PARTIAL_CONTENT","HS_AMBIGUOUS",
		"HS_MOVED","HS_REDIRECT","HS_REDIRECT_METHOD","HS_NOT_MODIFIED","HS_USE_PROXY",
		"HS_REDIRECT_KEEP_VERB","HS_BAD_REQUEST","HS_DENIED","HS_PAYMENT_REQ","HS_FORBIDDEN",
		"HS_NOT_FOUND","HS_BAD_METHOD","HS_NONE_ACCEPTABLE","HS_PROXY_AUTH_REQ","HS_REQUEST_TIMEOUT",
		"HS_CONFLICT","HS_GONE","HS_LENGTH_REQUIRED","HS_PRECOND_FAILED","HS_REQUEST_TOO_LARGE",
		"HS_URI_TOO_LONG","HS_UNSUPPORTED_MEDIA","HS_RETRY_WITH","HS_SERVER_ERROR","HS_NOT_SUPPORTED",
		"HS_BAD_GATEWAY","HS_SERVICE_UNAVAIL","HS_GATEWAY_TIMEOUT","HS_VERSION_NOT_SUP",
	};
const UINT GPWebBrowser2::uArrHStatus[39]={
		HTTP_STATUS_CONTINUE,HTTP_STATUS_SWITCH_PROTOCOLS,HTTP_STATUS_OK,HTTP_STATUS_CREATED,HTTP_STATUS_ACCEPTED,
		HTTP_STATUS_PARTIAL,HTTP_STATUS_NO_CONTENT,HTTP_STATUS_RESET_CONTENT,HTTP_STATUS_PARTIAL_CONTENT,HTTP_STATUS_AMBIGUOUS,
		HTTP_STATUS_MOVED,HTTP_STATUS_REDIRECT,HTTP_STATUS_REDIRECT_METHOD,HTTP_STATUS_NOT_MODIFIED,HTTP_STATUS_USE_PROXY,
		HTTP_STATUS_REDIRECT_KEEP_VERB,HTTP_STATUS_BAD_REQUEST,HTTP_STATUS_DENIED,HTTP_STATUS_PAYMENT_REQ,HTTP_STATUS_FORBIDDEN,
		HTTP_STATUS_NOT_FOUND,HTTP_STATUS_BAD_METHOD,HTTP_STATUS_NONE_ACCEPTABLE,HTTP_STATUS_PROXY_AUTH_REQ,HTTP_STATUS_REQUEST_TIMEOUT,
		HTTP_STATUS_CONFLICT,HTTP_STATUS_GONE,HTTP_STATUS_LENGTH_REQUIRED,HTTP_STATUS_PRECOND_FAILED,HTTP_STATUS_REQUEST_TOO_LARGE,
		HTTP_STATUS_URI_TOO_LONG,HTTP_STATUS_UNSUPPORTED_MEDIA,HTTP_STATUS_RETRY_WITH,HTTP_STATUS_SERVER_ERROR,HTTP_STATUS_NOT_SUPPORTED,
		HTTP_STATUS_BAD_GATEWAY,HTTP_STATUS_SERVICE_UNAVAIL,HTTP_STATUS_GATEWAY_TIMEOUT,HTTP_STATUS_VERSION_NOT_SUP,
	};

const UINT GPWebBrowser2::uNReadyState=5;
const char *GPWebBrowser2::cArrReadyState[5]={
		"RS_UNINITIALIZED","RS_LOADING","RS_LOADED","RS_INTERACTIVE","RS_COMPLETE",
	};
const UINT GPWebBrowser2::uArrReadyState[5]={
		READYSTATE_UNINITIALIZED,READYSTATE_LOADING,READYSTATE_LOADED,READYSTATE_INTERACTIVE,READYSTATE_COMPLETE,
	};

//IMPLEMENT_DYNCREATE(GPWebBrowser2, CWnd)

BEGIN_MESSAGE_MAP(GPWebBrowser2, CWnd)
	//{{AFX_MSG_MAP(GPWebBrowser2)
	ON_WM_SIZING()
	ON_WM_NCHITTEST()
	ON_WM_KILLFOCUS()
	ON_WM_SETFOCUS()
	ON_WM_SIZE()
	ON_WM_HSCROLL()
	ON_WM_VSCROLL()
	ON_WM_CTLCOLOR()
	//}}AFX_MSG_MAP
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// GPWebBrowser2 properties

/////////////////////////////////////////////////////////////////////////////
// GPWebBrowser2 operations

GPWebBrowser2::GPWebBrowser2(UINT iUnitId)
{
	referGPU=NULL;
	UnitId=iUnitId;
	m_Sink=NULL;
	pCP = NULL;
	m_dwCookie=0;
	m_JustDoIt=0;
}

GPWebBrowser2::~GPWebBrowser2()
{
	if (pCP)
	{
		pCP->Unadvise(m_dwCookie);
		pCP->Release();
	}

	if (m_Sink!=NULL) delete m_Sink;
	m_Sink=NULL;
}

void GPWebBrowser2::ConnectSink()
{
	if (m_Sink==NULL)
	{
		m_Sink = new GPWebBrowser2Sink();
		m_Sink->SetGPWebBrowser(this);
		LPDISPATCH pUnkSink = m_Sink->GetIDispatch(FALSE);

		IConnectionPointContainer* pCPC = 0;
		IID iid;
		m_pCtrlSite->GetEventIID(&iid);
		HRESULT hr = GetControlUnknown( )/*m_pCtrlSite->m_pObject*/->QueryInterface(IID_IConnectionPointContainer,(void **)&pCPC);
		if (SUCCEEDED(hr))
		{
			hr=pCPC->FindConnectionPoint(iid,&pCP);
			if (SUCCEEDED(hr))
			{
				LPUNKNOWN punk;
				hr=pUnkSink->QueryInterface(IID_IUnknown,(void **)&punk);
				if (SUCCEEDED(hr))
					pCP->Advise(punk,&m_dwCookie );
			}
			pCPC->Release();
		}
	}
}


/////////////////////////////////////////////////////////////////////////////
// GPWebBrowser2 properties

/////////////////////////////////////////////////////////////////////////////
// GPWebBrowser2 operations

UINT GPWebBrowser2::DoMethod(const char *iStr, char *oStr)
{
	char met[150];
	strncpy(met,iStr,145);met[45]=0;
	const char *pos=strchr(iStr,' ');
	if (pos++) *strchr(met,' ')=0;
	else		pos="";	

	int nfunc=0;

	int retint=-123456;
	int atoipos=atoi(pos);
	CString *m_ParamDelimiter=&(referGPU[UnitId&0xFFFF]->m_ParamDelimiter);

	if (*met>='0' && *met<='9') nfunc=atoi(met);
	else
	{
		static const char *sccArrMethods[sizeof(cArrMethods)/sizeof(char *)];
		static DWORD scdMethodsId[sizeof(cArrMethods)/sizeof(char *)];
		if (!*sccArrMethods)
		{
			DWORD i;
			for(i=0;i<uNMethods;i++)
			{
				sccArrMethods[i]=cArrMethods[i];
				scdMethodsId[i]=i;
			}
			qsCharILineAndDWORD(sccArrMethods, scdMethodsId, 0, uNMethods-1);
			scdMethodsId[i]=i;
		}
		nfunc=scdMethodsId[FindInSortArrayIC(met, sccArrMethods, uNMethods)];
	}
	try
	{
		switch(nfunc)
		{
		case  0: /*GoBack */		WBGoBack();		break;
		case  1: /*GoForward */		WBGoForward();	break;
		case  2: /*GoHome */		WBGoHome();		break;
		case  3: /*GoSearch */		WBGoSearch();	break;
		case  4: /*Refresh */		WBRefresh();	break;
		case  5: /*Refresh2 Level*/
			{
				COleVariant var((long)atoipos,VT_I4);
				if (*pos>'9') var.lVal=StringToRefrLevel(pos);
				WBRefresh2(&var);
			}
			break;
		case  6: /*Stop */		WBStop();	break;
		case  7: /*Quit */		WBQuit();	break;
		case  8: /*Navigate url,Flags,TargetFrameName,PostData,Headers*/
		case 47: /*Navigate2 url,Flags,TargetFrameName,PostData,Headers*/
			{
				m_JustDoIt|=0x1;
				CString tmp;
				CString pURL=ExtractField(pos,1,(LPCSTR)*m_ParamDelimiter);
				if (pURL!="" && pURL.Find(":",0)<0)
				{
					char tmpDir[500];
					*tmpDir=0;
					tmpDir[GetCurrentDirectory(490,tmpDir)]=0;
					if (*tmpDir)
					{
						strcat(tmpDir,"\\");
						pURL=tmpDir+pURL;
					}
				}

				COleVariant Flags;
				tmp=ExtractField(pos,2,(LPCSTR)*m_ParamDelimiter);
				if (tmp!="") {Flags.ChangeType(VT_I4); Flags.lVal=StringToNavConst((LPCSTR)tmp);}
				COleVariant TargetFrameName;
				tmp=ExtractField(pos,3,(LPCSTR)*m_ParamDelimiter);
				if (tmp!="") {TargetFrameName=COleVariant(tmp,VT_BSTR);}

				tmp=ExtractField(pos,4,(LPCSTR)*m_ParamDelimiter);
				COleVariant Headers;
				if (tmp!="") {Headers=COleVariant(tmp,VT_BSTR);}

				COleVariant PostData;
				tmp=FindField(pos,5,(LPCSTR)*m_ParamDelimiter);
				if (tmp!="")
				{
					Headers=COleVariant(tmp,VT_BSTR);
					CString tmpcstr;
					StringToArray(tmp, &PostData,tmpcstr,VT_UI1, 2);
				}

				if (nfunc==8)
					WBNavigate(pURL,&Flags,&TargetFrameName,&PostData,&Headers);
				else
				{
					COleVariant vURL(pURL,VT_BSTR);
					WBNavigate2(vURL,&Flags,&TargetFrameName,&PostData,&Headers);
				}
			}
			break;
		case  9: /*GetType*/
			if (oStr)	strcpy(oStr,WBGetType());
			break;
		case 10: /*GetLeft*/	retint=WBGetLeft();		break;
		case 11: /*SetLeft*/	WBSetLeft(atoipos);		break;
		case 12: /*GetTop*/		retint=WBGetTop();		break;
		case 13: /*SetTop*/		WBSetTop(atoipos);		break;
		case 14: /*GetWidth*/	retint=WBGetWidth();	break;
		case 15: /*SetWidth*/	WBSetWidth(atoipos);	break;
		case 16: /*GetHeight*/	retint=WBGetHeight();	break;
		case 17: /*SetHeight*/	WBSetHeight(atoipos);	break;
		case 18: /*GetLocationName*/
			if (oStr)	strcpy(oStr,WBGetLocationName());
			break;
		case 19: /*GetLocationURL*/
			if (oStr)	strcpy(oStr,WBGetLocationURL());
			break;
		case 20: /*GetBusy*/	retint=WBGetBusy();		break;
		case 21: /*GetOffline*/	retint=WBGetOffline();	break;
		case 22: /*SetOffline*/	WBSetOffline(atoipos);	break;
		case 23: /*GetVisible*/	retint=WBGetVisible();	break;
		case 24: /*SetVisible*/	WBSetVisible(atoipos);	break;
		case 25: /*GetFullScreen*/	retint=WBGetFullScreen();	break;
		case 26: /*SetFullScreen*/	WBSetFullScreen(atoipos);	break;
		case 27: /*GetSilent*/	retint=WBGetSilent();	break;
		case 28: /*SetSilent*/	WBSetSilent(atoipos);	break;
		case 29: /*GetRegisterAsBrowser*/		retint=WBGetRegisterAsBrowser();	break;
		case 30: /*SetRegisterAsBrowser*/		WBSetRegisterAsBrowser(atoipos);	break;
		case 31: /*GetRegisterAsDropTarget*/	retint=WBGetRegisterAsDropTarget();	break;
		case 32: /*SetRegisterAsDropTarget*/	WBSetRegisterAsDropTarget(atoipos);	break;
		case 33: /*GetResizable*/	retint=WBGetResizable();	break;
		case 34: /*SetResizable*/	WBSetResizable(atoipos);	break;
		case 35: /*GetTheaterMode*/	retint=WBGetTheaterMode();	break;
		case 36: /*SetTheaterMode*/	WBSetTheaterMode(atoipos);	break;
		case 37: /*GetAddressBar*/	retint=WBGetAddressBar();	break;
		case 38: /*SetAddressBar*/	WBSetAddressBar(atoipos);	break;
		case 39: /*GetStatusBar*/	retint=WBGetStatusBar();	break;
		case 40: /*SetStatusBar*/	WBSetStatusBar(atoipos);	break;
		case 41: /*GetStatusText*/
			if (oStr)	strcpy(oStr,WBGetStatusText());
			break;
		case 42: /*SetStatusText*/	WBSetStatusText(CString(pos));	break;
		case 43: /*GetToolBar*/		retint=WBGetToolBar();		break;
		case 44: /*SetToolBar*/		WBSetToolBar(atoipos);		break;
		case 45: /*GetMenuBar*/		retint=WBGetMenuBar();		break;
		case 46: /*SetMenuBar*/		WBSetMenuBar(atoipos);		break;
		case 48: /*ClientToWindow CX,CY*/
			if (oStr)
			{
				long CX=0,CY=0;
				m_LastScanf=sscanf(pos,"%d,%d",&CX,&CY);
				WBClientToWindow(&CX,&CY);
				sprintf(oStr,"%d\x7F%d",CX,CY);
			}
			break;
		case 49: /*GetName*/
			if (oStr)	strcpy(oStr,WBGetName());
			break;
		case 50: /*GetFullName*/
			if (oStr)	strcpy(oStr,WBGetFullName());
			break;
		case 51: /*GetPath*/
			if (oStr)	strcpy(oStr,WBGetPath());
			break;
		case 52: /*GetReadyState*/
			if (oStr)	strcpy(oStr,ReadyStateToString(WBGetReadyState()));
			break;
		case 53: /*ShowBrowserBar*/
			{
				COleVariant clsids(ExtractField(pos,1,(LPCSTR)*m_ParamDelimiter),VT_BSTR);
				COleVariant varShow((long)(atoi(ExtractField(pos,2,(LPCSTR)*m_ParamDelimiter))),VT_BOOL);
				COleVariant pvarSize;
				WBShowBrowserBar(&clsids,&varShow,&pvarSize);
			}
			break;
		case 54: /*WBExec*/
			{
				#define N_OLECMDID			52
				extern const char *aOLECMDIDName[];
				extern const UINT  aOLECMDIDUINT[];
			}
			break;

		case 55: /*WBPrint*/
			{
				LPDISPATCH lpDispatch = NULL;
				LPOLECOMMANDTARGET lpOleCommandTarget = NULL;
				CString tmpsIN=ExtractField(pos,2,",");
				if (tmpsIN!="" && tmpsIN.Find(":",0)<0)
				{
					char tmpDir[500];
					*tmpDir=0;
					tmpDir[GetCurrentDirectory(490,tmpDir)]=0;
					if (*tmpDir)
					{
						strcat(tmpDir,"\\");
						tmpsIN=tmpDir+tmpsIN;
					}
				}
				lpDispatch = WBGetDocument();
				if (lpDispatch)
				{
					lpDispatch->QueryInterface(IID_IOleCommandTarget, (void**)&lpOleCommandTarget);
					lpDispatch->Release();

					// Print contents of WebBrowser control.
					if (lpOleCommandTarget)
					{
						/*
						typedef enum  
						{ 
							OLECMDEXECOPT_DODEFAULT        = 0, 
							OLECMDEXECOPT_PROMPTUSER       = 1, 
							LECMDEXECOPT_DONTPROMPTUSER    = 2, 
							OLECMDEXECOPT_SHOWHELP         = 3 
						} OLECMDEXECOPT; 

						*/
						COleVariant vIn(tmpsIN);
						lpOleCommandTarget->Exec(NULL, OLECMDID_PRINT, atoipos ,(tmpsIN=="")?NULL:&vIn,NULL);
						lpOleCommandTarget->Release();
					}
				}
			}
			break;

		default: if (oStr!=NULL)	sprintf(oStr,ErrObjSub,met);nfunc=0xFFFFFFFFL;break;
		}
	}catch(...)
	{
		char *str=new char [200+(int)strlen(pos)];
		#ifdef RUS
			sprintf(str,"Ошибка выполнения метода %s %s",met,pos);
			MessageBox(str,"Ошибка метода");
		#else
			sprintf(str,"Error execution of method %s %s",met,pos);
			MessageBox(str,"Error execution");
		#endif
		if (oStr!=NULL) strcpy(oStr,str);

		GPC.m_ErrReport.GPWriteErrorLog("GPWebBrowser2", "DoMethod",iStr);

		nfunc=0xFFFFFFFFL;
		delete[] str;
	}

	if (oStr!=NULL && *oStr==0 && retint!=-123456) sprintf(oStr,"%d",retint);
	return nfunc;
}


UINT GPWebBrowser2::GPSetProperty(char *iStr)
{
	char *iValue=new char [(int)strlen(iStr)+5];
	strcpy(iValue,iStr);
	UINT ret=1;
	char *pos=strchr(iValue,'=');

	if (pos!=NULL && m_hWnd)
	{
		char *prop[]={ "ADDSTYLE", "DELSTYLE","STYLE",};
		int propnum;
		*(pos++)=0;
		for(propnum=0;propnum<3 && strcmp(prop[propnum],iValue)!=0;propnum++);
		if (propnum>=3) ret=2;
		else
		{
			ret=3;
			switch(propnum)
			{
			case 0: // ADDSTYLE
			case 1: // DELSTYLE
			case 2: // STYLE
				ret=1;
				break;
			default: /* end */
				ret=2;
				break;
			}

		}
		*(--pos)='=';
	}

	delete[] iValue;
	return ret;
}

void GPWebBrowser2::OnDragMouseHover()
{
	if (referGPU[UnitId&0xFFFF]->m_DropNamesArray && referGPU[UnitId&0xFFFF]->m_DropNamesArray->GetIdByVal(GPC.m_DragDrop.DragName)<0xFFFFFFFFL)
	{
		// Reset the timer.
		SetTimer(DRAG_TIMER_ID, referGPU[UnitId&0xFFFF]->m_nScrollInterval, NULL);

		// Get the current cursor position and window height.
		DWORD dwPos = ::GetMessagePos();
		CPoint point(LOWORD(dwPos), HIWORD(dwPos));
		ScreenToClient(&point);

		CRect rect;
		GetClientRect(rect);
		int cy = rect.Height();


		// Scroll the window if the cursor is near the top or bottom.
		if (point.y >= 0 && point.y <= referGPU[UnitId&0xFFFF]->m_nScrollMargin)
		{
			int nFirstVisibleLine = GetScrollPos(SB_VERT);
			GPC.m_DragDrop.pImageList->DragShowNolock(FALSE);
			SendMessage(WM_VSCROLL, MAKEWPARAM(SB_LINEUP, 0), NULL);
			GPC.m_DragDrop.pImageList->DragShowNolock(TRUE);

			// Kill the timer if the window did not scroll, or redraw the drop target highlight if the window did scroll.
			if (GetScrollPos(SB_VERT) == nFirstVisibleLine)
				::KillTimer(GPC.m_DragDrop.hWndDrag,DRAG_TIMER_ID);
			else
				HighlightDropTarget(&GPC.m_DragDrop, point);
		}
		else
			if (point.y >= cy - referGPU[UnitId&0xFFFF]->m_nScrollMargin && point.y <= cy)
			{
				int nFirstVisibleLine = GetScrollPos(SB_VERT);
				GPC.m_DragDrop.pImageList->DragShowNolock(FALSE);
				SendMessage(WM_VSCROLL, MAKEWPARAM(SB_LINEDOWN, 0), NULL);
				GPC.m_DragDrop.pImageList->DragShowNolock(TRUE);

				// Kill the timer if the window did not scroll, or redraw the drop target highlight if the window did scroll.
				if (GetScrollPos(SB_VERT) == nFirstVisibleLine) ::KillTimer(GPC.m_DragDrop.hWndDrag,DRAG_TIMER_ID);
				else
					HighlightDropTarget(&GPC.m_DragDrop, point);
			}
			else  ::KillTimer(GPC.m_DragDrop.hWndDrag,DRAG_TIMER_ID);

		CString tmps;
		POINTL pol;
		pol.x=point.x;
		pol.y=point.y;
		long nchar = SendMessage(EM_CHARFROMPOS,0,(LPARAM)&pol);
		long nline = SendMessage(EM_LINEFROMCHAR,nchar,0);
		long ncharINline = SendMessage(EM_LINEINDEX,nline,0);
		tmps.Format("%d\x07%d\x07%d",nchar,nline,ncharINline);
		referGPU[UnitId&0xFFFF]->SendDropHoverEvent(tmps,&GPC.m_DragDrop,&point);
	}
}

void GPWebBrowser2::OnMouseDragMove(PGPDRAGDROPSTRUCT pDrDrStruct, LPPOINT point)
{
	if (pDrDrStruct && pDrDrStruct->pImageList != NULL)
	{
		::ScreenToClient(m_hWnd,point);
		::KillTimer(pDrDrStruct->hWndDrag,DRAG_TIMER_ID);
		// Offset point
		if (referGPU && referGPU[UnitId&0xFFFF])
			referGPU[UnitId&0xFFFF]->OffsetWndPoint(point);

		// Erase the old drag image and draw a new one.
		if (pDrDrStruct->hWndLast!=m_hWnd)
		{
			pDrDrStruct->pImageList->DragLeave(CWnd::FromHandle(pDrDrStruct->hWndLast));
			pDrDrStruct->hWndLast=m_hWnd;
			pDrDrStruct->pImageList->DragEnter(this, CPoint(*point));
		}
		pDrDrStruct->pImageList->DragMove(CPoint(*point));

		DWORD dwHighlightItem=0xFFFFFFFF;
		BOOL mDrop=referGPU[UnitId&0xFFFF]->m_DropNamesArray && referGPU[UnitId&0xFFFF]->m_DropNamesArray->GetIdByVal(pDrDrStruct->DragName)<0xFFFFFFFFL;
		// Highlight the drop target if the cursor is over an item.
		if (mDrop)
			dwHighlightItem = HighlightDropTarget(pDrDrStruct, CPoint(*point));
		// Modify the cursor to provide visual feedback to the user. Note: It's important to do this AFTER the call to DragMove.
		::SetCursor(dwHighlightItem == -1 ?
			AfxGetApp()->LoadStandardCursor(IDC_NO) :
			(HCURSOR) ::GetClassLong(m_hWnd, GCL_HCURSOR));

		CString tmps;
		POINTL pol;
		pol.x=point->x;
		pol.y=point->y;
		long nchar = SendMessage(EM_CHARFROMPOS,0,(LPARAM)&pol);
		long nline = SendMessage(EM_LINEFROMCHAR,nchar,0);
		long ncharINline = SendMessage(EM_LINEINDEX,nline,0);
		tmps.Format("%d\x07%d\x07%d",nchar,nline,ncharINline);
		referGPU[UnitId&0xFFFF]->SendDropMoveEvent(tmps,pDrDrStruct,point);

		if (mDrop)
			::SetTimer(pDrDrStruct->hWndDrag,DRAG_TIMER_ID, referGPU[UnitId&0xFFFF]->m_nDelayInterval, NULL);
	}
}

void GPWebBrowser2::OnDragLButtonUp(PGPDRAGDROPSTRUCT pDrDrStruct, LPPOINT point)
{
	BOOL mDrop=referGPU[UnitId&0xFFFF]->m_DropNamesArray && referGPU[UnitId&0xFFFF]->m_DropNamesArray->GetIdByVal(pDrDrStruct->DragName)<0xFFFFFFFFL;
	if (pDrDrStruct && mDrop && referGPU)
	{
		::ScreenToClient(m_hWnd,point);
		CString tmp;
		POINTL pol;
		pol.x=point->x;
		pol.y=point->y;
		long nchar = SendMessage(EM_CHARFROMPOS,0,(LPARAM)&pol);
		long nline = SendMessage(EM_LINEFROMCHAR,nchar,0);
		long ncharINline = SendMessage(EM_LINEINDEX,nline,0);
		tmp.Format("%d\x07%d\x07%d",nchar,nline,ncharINline);
		referGPU[UnitId&0xFFFF]->SendDropEvent(tmp,pDrDrStruct,point);
	}
}

DWORD GPWebBrowser2::HighlightDropTarget(PGPDRAGDROPSTRUCT pDrDrStruct, CPoint point)
{
	return 0;
}

LRESULT GPWebBrowser2::OnNcHitTest(CPoint point)
{
	LRESULT ret=CWnd::OnNcHitTest(point);
	if (referGPU && referGPU[UnitId&0xFFFF])
		ret=referGPU[UnitId&0xFFFF]->GPNCHitTest(point,ret);
	return ret;
}

#include "GP_TermDoc.h"

void GPWebBrowser2::OnKillFocus(CWnd* pNewWnd)
{
	CWnd::OnKillFocus(pNewWnd);
	GPUNITINFO ui;
	GPUNITINFO uiold;
	if (referGPU && referGPU[UnitId&0xFFFF])
		referGPU[UnitId&0xFFFF]->GetUnitInfo(ui);
	if (pNewWnd)
	{
		GPC.m_Document->FindObject(pNewWnd->m_hWnd,uiold);
		ui.hWnd2=uiold.hWnd;
		ui.IdDlg2=uiold.IdDlg;
		ui.IdObj2=uiold.IdObj;
	}
	if (referGPU && referGPU[UnitId&0xFFFF] && referGPU[UnitId&0xFFFF]->GPMSG)
	{
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent
			(m_hWnd, UnitId,"OnKillFocus",GPUnit::UnitInfoToString2(&ui,"\x7F"));
	}
	::SendMessage(::GetParent(m_hWnd),GPM_CLIENTKILLFOCUS,(WPARAM)(pNewWnd?pNewWnd->m_hWnd:NULL),(LPARAM)&ui);
}

void GPWebBrowser2::OnSetFocus(CWnd* pOldWnd)
{
	CWnd::OnSetFocus(pOldWnd);
	GPUNITINFO ui;
	GPUNITINFO uiold;
	if (referGPU && referGPU[UnitId&0xFFFF])
		referGPU[UnitId&0xFFFF]->GetUnitInfo(ui);
	if (pOldWnd)
	{
		GPC.m_Document->FindObject(pOldWnd->m_hWnd,uiold);
		ui.hWnd2=uiold.hWnd;
		ui.IdDlg2=uiold.IdDlg;
		ui.IdObj2=uiold.IdObj;
	}
	if (referGPU && referGPU[UnitId&0xFFFF] && referGPU[UnitId&0xFFFF]->GPMSG)
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent
			(m_hWnd, UnitId,"OnSetFocus",GPUnit::UnitInfoToString2(&ui,"\x7F"));

	::SendMessage(::GetParent(m_hWnd),GPM_CLIENTSETFOCUS,(WPARAM)(pOldWnd?pOldWnd->m_hWnd:NULL),(LPARAM)&ui);
}

void GPWebBrowser2::OnSize(UINT nType, int cx, int cy)
{
	CWnd::OnSize(nType, cx, cy);

	if (m_hWnd)
	{
		if (referGPU!=NULL && referGPU[UnitId&0xFFFF])
			referGPU[UnitId&0xFFFF]->UpdateSizerSize();
	}
}

void GPWebBrowser2::OnSizing(UINT fwSide, LPRECT pRect)
{
	BOOL EnableSz=TRUE;
	UINT SizStyle=referGPU[UnitId&0xFFFF]->SizStyle;
	if ((SizStyle&0xFFFF)!=0)
	{
		CRect re;
		GetWindowRect(&re);
		switch(fwSide)
		{
		case WMSZ_BOTTOM:
			if ((SizStyle&GPUA_BOTTOM)!=GPUA_BOTTOM) EnableSz=FALSE;
			break;
		case WMSZ_BOTTOMLEFT:
			if ((SizStyle&GPUA_BOTTOM)!=GPUA_BOTTOM &&(SizStyle&GPUA_LEFT)!=GPUA_LEFT) EnableSz=FALSE;
			break;
		case WMSZ_BOTTOMRIGHT:
			if ((SizStyle&GPUA_BOTTOM)!=GPUA_BOTTOM &&(SizStyle&GPUA_RIGHT)!=GPUA_RIGHT) EnableSz=FALSE;
			break;
		case WMSZ_LEFT:
			if ((SizStyle&GPUA_LEFT)!=GPUA_LEFT) EnableSz=FALSE;
			break;
		case WMSZ_RIGHT:
			if ((SizStyle&GPUA_RIGHT)!=GPUA_RIGHT) EnableSz=FALSE;
			break;
		case WMSZ_TOP:
			if ((SizStyle&GPUA_TOP)!=GPUA_TOP) EnableSz=FALSE;
			break;
		case WMSZ_TOPLEFT:
			if ((SizStyle&GPUA_LEFT)!=GPUA_LEFT &&(SizStyle&GPUA_TOP)!=GPUA_TOP) EnableSz=FALSE;
			break;
		case WMSZ_TOPRIGHT:
			if ((SizStyle&GPUA_RIGHT)!=GPUA_RIGHT &&(SizStyle&GPUA_TOP)!=GPUA_TOP) EnableSz=FALSE;
			break;
		}
		if (EnableSz==FALSE)
		{
			pRect->top=re.top;
			pRect->left=re.left;
			pRect->right=re.right;
			pRect->bottom=re.bottom;
		}
		else
		{
			GetParent()->SendMessage(WM_SIZE);
		}
	}
	if (EnableSz) CWnd::OnSizing(fwSide, pRect);
}

void GPWebBrowser2::GPOnSizing(UINT fwSide, LPRECT pRect)
{
	BOOL EnableSz=TRUE;
	UINT SizStyle=referGPU[UnitId&0xFFFF]->SizStyle;
	if ((SizStyle&0xFFFF)!=0)
	{
		CRect re;
		GetWindowRect(&re);
		switch(fwSide)
		{
		case WMSZ_BOTTOM:
			if ((SizStyle&GPUA_BOTTOM)!=GPUA_BOTTOM) EnableSz=FALSE;
			break;
		case WMSZ_BOTTOMLEFT:
			if ((SizStyle&GPUA_BOTTOM)!=GPUA_BOTTOM &&(SizStyle&GPUA_LEFT)!=GPUA_LEFT) EnableSz=FALSE;
			break;
		case WMSZ_BOTTOMRIGHT:
			if ((SizStyle&GPUA_BOTTOM)!=GPUA_BOTTOM &&(SizStyle&GPUA_RIGHT)!=GPUA_RIGHT) EnableSz=FALSE;
			break;
		case WMSZ_LEFT:
			if ((SizStyle&GPUA_LEFT)!=GPUA_LEFT) EnableSz=FALSE;
			break;
		case WMSZ_RIGHT:
			if ((SizStyle&GPUA_RIGHT)!=GPUA_RIGHT) EnableSz=FALSE;
			break;
		case WMSZ_TOP:
			if ((SizStyle&GPUA_TOP)!=GPUA_TOP) EnableSz=FALSE;
			break;
		case WMSZ_TOPLEFT:
			if ((SizStyle&GPUA_LEFT)!=GPUA_LEFT &&(SizStyle&GPUA_TOP)!=GPUA_TOP) EnableSz=FALSE;
			break;
		case WMSZ_TOPRIGHT:
			if ((SizStyle&GPUA_RIGHT)!=GPUA_RIGHT &&(SizStyle&GPUA_TOP)!=GPUA_TOP) EnableSz=FALSE;
			break;
		}
		if (EnableSz==FALSE)
		{
			pRect->top=re.top;
			pRect->left=re.left;
			pRect->right=re.right;
			pRect->bottom=re.bottom;
		}
		else
		{
			GetParent()->SendMessage(WM_SIZE);
		}
	}
	GetParent()->SendMessage(GPN_UPDATESIZE);
}

BOOL GPWebBrowser2::PreTranslateMessage(MSG* pMsg)
{
	if (referGPU && referGPU[UnitId&0xFFFF])
	{
		referGPU[UnitId&0xFFFF]->m_CurPreMessage=pMsg;
		if (!referGPU[UnitId&0xFFFF]->DefPreTranslateMessage(pMsg)) return 0;
		if (referGPU[UnitId&0xFFFF]->GPMSG)
		{
			UINT ret;
			if (pMsg->message!=WM_KEYDOWN || pMsg->wParam==VK_RETURN || pMsg->wParam==VK_TAB || pMsg->wParam==VK_CANCEL || pMsg->wParam==VK_ESCAPE || pMsg->wParam==VK_HELP)
			{
				if ((ret=referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjMessage(m_hWnd, UnitId, pMsg->message, pMsg->wParam, pMsg->lParam))>0) return ret;
				if (pMsg->message==WM_KEYDOWN && referGPU!=NULL && referGPU[UnitId&0xFFFF]->UnitHotkey && this->m_hWnd!=NULL && IsWindowEnabled()==TRUE && IsWindowVisible()==TRUE)
						if ((ret=referGPU[UnitId&0xFFFF]->UnitHotkey->SendHotkeyMessage(pMsg->message, pMsg->wParam,pMsg->lParam))>0) return ret;
			}
		}
	}

	switch(pMsg->message)
	{
	case WM_SIZING:			GPOnSizing(pMsg->wParam,(LPRECT)pMsg->lParam);			break;
	case WM_PAINT:
		if (m_Sink==NULL)
		{
			ConnectSink();
		}
		break;
	case WM_KILLFOCUS: 		OnGPKillFocus(CWnd::FromHandle((HWND)pMsg->wParam));	break;
	case WM_RBUTTONDOWN:
		break;
	}

	BOOL ret=CWnd::PreTranslateMessage(pMsg);

	WindowProc(pMsg->message, pMsg->wParam, pMsg->lParam);

	return ret;
}

LRESULT GPWebBrowser2::WindowProc(UINT message, WPARAM wParam, LPARAM lParam)
{
	if (referGPU && referGPU[UnitId&0xFFFF])
	{
		referGPU[UnitId&0xFFFF]->m_CurMessage.message=message;
		referGPU[UnitId&0xFFFF]->m_CurMessage.wParam=wParam;
		referGPU[UnitId&0xFFFF]->m_CurMessage.lParam=lParam;
		referGPU[UnitId&0xFFFF]->DefWindowProc(message, wParam, lParam);
	}

	if (message==GPM_SETAUTOSIZE)
		GetParent()->PostMessage(GPM_SETAUTOSIZE,wParam);

	if (message==GPN_UPDATESIZE) GetParent()->SendMessage(GPN_UPDATESIZE);

	if (referGPU && referGPU[UnitId&0xFFFF] && referGPU[UnitId&0xFFFF]->GPMSG)
	{
		if (message==GPM_CLIENTKILLFOCUS || message==GPM_CLIENTSETFOCUS)
		{
			PGPUNITINFO ui=(PGPUNITINFO)lParam;
			if (ui)
				referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent
					(m_hWnd, UnitId,message==GPM_CLIENTSETFOCUS?"OnCSetFocus":"OnCKillFocus",GPUnit::UnitInfoToString2(ui,"\x7F"));
		}
		UINT ret;
		if ((ret=referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjMessage(m_hWnd, UnitId, message, wParam, lParam))>0) return ret;
		if (message==WM_KEYDOWN && referGPU!=NULL && referGPU[UnitId&0xFFFF]->UnitHotkey && this->m_hWnd!=NULL && IsWindowEnabled()==TRUE && IsWindowVisible()==TRUE)
				if ((ret=referGPU[UnitId&0xFFFF]->UnitHotkey->SendHotkeyMessage(message, wParam,lParam))>0) return ret;
		if (message==GPM_PROCHOTKEY)
		{
			if(referGPU[UnitId&0xFFFF]->UnitHotkey && (ret=referGPU[UnitId&0xFFFF]->UnitHotkey->SendHotkeyMessage(WM_KEYDOWN, wParam,lParam))>0) return ret;
			GetParent()->SendMessage(message, wParam,lParam);
		}
		else
		if  (message==WM_KEYDOWN)
			GetParent()->SendMessage(GPM_PROCHOTKEY, wParam,lParam);
	}

	switch(message)
	{
	case GPM_DRAGMOUSELEAVE:
		if (referGPU!=NULL)	referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnDragLeave","");
		break;
	case GPM_DRAGMOUSEMOVE:
		OnMouseDragMove((PGPDRAGDROPSTRUCT)wParam,(LPPOINT)lParam);
		break;
	case GPM_DRAGMOUSEHOVER:
		OnDragMouseHover();
		break;
	case GPM_DROPITEMS:
		OnDragLButtonUp((PGPDRAGDROPSTRUCT)wParam,(LPPOINT)lParam);
		break;
	}

	LRESULT lpr=0;
	if (message==WM_SETCURSOR && GPC.m_bWaitCursor) lpr=FALSE;
	//	else lpr=CWnd::WindowProc(message, wParam, lParam);

	if (message==WM_SIZEPARENT && referGPU!=NULL)
	{
		UINT SizStyle=referGPU[UnitId&0xFFFF]->SizStyle;
		if ((SizStyle&0xFFFF0000)!=0)
		{
			AFX_SIZEPARENTPARAMS* lpLayout =(AFX_SIZEPARENTPARAMS*)lParam;

			CRect re;
			GetWindowRect(&re);
			switch((SizStyle&0xFFFF0000)/0x10000)
			{
			case GPUA_TOP:
				MoveWindow(lpLayout->rect.left,lpLayout->rect.top,lpLayout->rect.right-lpLayout->rect.left,re.Height());
				lpLayout->rect.top+=re.Height();
				break;
			case GPUA_BOTTOM:
				MoveWindow(lpLayout->rect.left,lpLayout->rect.bottom-re.Height(),lpLayout->rect.right-lpLayout->rect.left,re.Height());
				lpLayout->rect.bottom-=re.Height();
				break;
			case GPUA_LEFT:
				MoveWindow(lpLayout->rect.left,lpLayout->rect.top,re.Width(),lpLayout->rect.bottom-lpLayout->rect.top);
				lpLayout->rect.left+=re.Width();
				break;
			case GPUA_RIGHT:
				MoveWindow(lpLayout->rect.right-re.Width(),lpLayout->rect.top,re.Width(),lpLayout->rect.bottom-lpLayout->rect.top);
				lpLayout->rect.right-=re.Width();
				break;
			}
		}
	}
	return lpr;
}

void GPWebBrowser2::OnGPKillFocus(CWnd* pNewWnd)
{
	MayBeChangeEdit=TRUE;
}

/////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////

void GPWebBrowser2::WBGoBack()
{
	InvokeHelper(0x64, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void GPWebBrowser2::WBGoForward()
{
	InvokeHelper(0x65, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void GPWebBrowser2::WBGoHome()
{
	InvokeHelper(0x66, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void GPWebBrowser2::WBGoSearch()
{
	InvokeHelper(0x67, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void GPWebBrowser2::WBNavigate(LPCTSTR URL, VARIANT* Flags, VARIANT* TargetFrameName, VARIANT* PostData, VARIANT* Headers)
{
	static BYTE parms[] =
		VTS_BSTR VTS_PVARIANT VTS_PVARIANT VTS_PVARIANT VTS_PVARIANT;
	InvokeHelper(0x68, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 URL, Flags, TargetFrameName, PostData, Headers);
}

void GPWebBrowser2::WBRefresh()
{
	InvokeHelper(DISPID_REFRESH, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void GPWebBrowser2::WBRefresh2(VARIANT* Level)
{
	static BYTE parms[] =
		VTS_PVARIANT;
	InvokeHelper(0x69, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Level);
}

void GPWebBrowser2::WBStop()
{
	InvokeHelper(0x6a, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

LPDISPATCH GPWebBrowser2::WBGetApplication()
{
	LPDISPATCH result;
	InvokeHelper(0xc8, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&result, NULL);
	return result;
}

LPDISPATCH GPWebBrowser2::WBGetParent()
{
	LPDISPATCH result;
	InvokeHelper(0xc9, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&result, NULL);
	return result;
}

LPDISPATCH GPWebBrowser2::WBGetContainer()
{
	LPDISPATCH result;
	InvokeHelper(0xca, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&result, NULL);
	return result;
}

LPDISPATCH GPWebBrowser2::WBGetDocument()
{
	LPDISPATCH result;
	InvokeHelper(0xcb, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&result, NULL);
	return result;
}

BOOL GPWebBrowser2::WBGetTopLevelContainer()
{
	BOOL result;
	InvokeHelper(0xcc, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

CString GPWebBrowser2::WBGetType()
{
	CString result;
	InvokeHelper(0xcd, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

long GPWebBrowser2::WBGetLeft()
{
	long result;
	InvokeHelper(0xce, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetLeft(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xce, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long GPWebBrowser2::WBGetTop()
{
	long result;
	InvokeHelper(0xcf, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetTop(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xcf, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long GPWebBrowser2::WBGetWidth()
{
	long result;
	InvokeHelper(0xd0, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetWidth(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xd0, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long GPWebBrowser2::WBGetHeight()
{
	long result;
	InvokeHelper(0xd1, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetHeight(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xd1, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

CString GPWebBrowser2::WBGetLocationName()
{
	CString result;
	InvokeHelper(0xd2, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString GPWebBrowser2::WBGetLocationURL()
{
	CString result;
	InvokeHelper(0xd3, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL GPWebBrowser2::WBGetBusy()
{
	BOOL result;
	InvokeHelper(0xd4, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBQuit()
{
	InvokeHelper(0x12c, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void GPWebBrowser2::WBClientToWindow(long* pcx, long* pcy)
{
	static BYTE parms[] =
		VTS_PI4 VTS_PI4;
	InvokeHelper(0x12d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pcx, pcy);
}

void GPWebBrowser2::WBPutProperty(LPCTSTR Property_, const VARIANT& vtValue)
{
	static BYTE parms[] =
		VTS_BSTR VTS_VARIANT;
	InvokeHelper(0x12e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Property_, &vtValue);
}

VARIANT GPWebBrowser2::WBGetProperty_(LPCTSTR Property_)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x12f, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		Property_);
	return result;
}

CString GPWebBrowser2::WBGetName()
{
	CString result;
	InvokeHelper(0x0, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

long GPWebBrowser2::WBGetHwnd()
{
	long result;
	InvokeHelper(DISPID_HWND, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CString GPWebBrowser2::WBGetFullName()
{
	CString result;
	InvokeHelper(0x190, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

CString GPWebBrowser2::WBGetPath()
{
	CString result;
	InvokeHelper(0x191, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

BOOL GPWebBrowser2::WBGetVisible()
{
	BOOL result;
	InvokeHelper(0x192, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetVisible(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x192, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL GPWebBrowser2::WBGetStatusBar()
{
	BOOL result;
	InvokeHelper(0x193, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetStatusBar(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x193, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

CString GPWebBrowser2::WBGetStatusText()
{
	CString result;
	InvokeHelper(0x194, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetStatusText(LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x194, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 lpszNewValue);
}

long GPWebBrowser2::WBGetToolBar()
{
	long result;
	InvokeHelper(0x195, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetToolBar(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x195, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

BOOL GPWebBrowser2::WBGetMenuBar()
{
	BOOL result;
	InvokeHelper(0x196, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetMenuBar(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x196, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL GPWebBrowser2::WBGetFullScreen()
{
	BOOL result;
	InvokeHelper(0x197, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetFullScreen(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x197, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

void GPWebBrowser2::WBNavigate2(VARIANT* URL, VARIANT* Flags, VARIANT* TargetFrameName, VARIANT* PostData, VARIANT* Headers)
{
	static BYTE parms[] =
		VTS_PVARIANT VTS_PVARIANT VTS_PVARIANT VTS_PVARIANT VTS_PVARIANT;
	InvokeHelper(0x1f4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 URL, Flags, TargetFrameName, PostData, Headers);
}

long GPWebBrowser2::WBQueryStatusWB(long cmdID)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1f5, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		cmdID);
	return result;
}

void GPWebBrowser2::WBExecWB(long cmdID, long cmdexecopt, VARIANT* pvaIn, VARIANT* pvaOut)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_PVARIANT VTS_PVARIANT;
	InvokeHelper(0x1f6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 cmdID, cmdexecopt, pvaIn, pvaOut);
}

void GPWebBrowser2::WBShowBrowserBar(VARIANT* pvaClsid, VARIANT* pvarShow, VARIANT* pvarSize)
{
	static BYTE parms[] =
		VTS_PVARIANT VTS_PVARIANT VTS_PVARIANT;
	InvokeHelper(0x1f7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pvaClsid, pvarShow, pvarSize);
}

long GPWebBrowser2::WBGetReadyState()
{
	long result;
	InvokeHelper(DISPID_READYSTATE, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL GPWebBrowser2::WBGetOffline()
{
	BOOL result;
	InvokeHelper(0x226, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetOffline(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x226, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL GPWebBrowser2::WBGetSilent()
{
	BOOL result;
	InvokeHelper(0x227, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetSilent(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x227, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL GPWebBrowser2::WBGetRegisterAsBrowser()
{
	BOOL result;
	InvokeHelper(0x228, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetRegisterAsBrowser(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x228, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL GPWebBrowser2::WBGetRegisterAsDropTarget()
{
	BOOL result;
	InvokeHelper(0x229, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetRegisterAsDropTarget(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x229, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL GPWebBrowser2::WBGetTheaterMode()
{
	BOOL result;
	InvokeHelper(0x22a, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetTheaterMode(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x22a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL GPWebBrowser2::WBGetAddressBar()
{
	BOOL result;
	InvokeHelper(0x22b, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetAddressBar(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x22b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL GPWebBrowser2::WBGetResizable()
{
	BOOL result;
	InvokeHelper(0x22c, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void GPWebBrowser2::WBSetResizable(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x22c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

////////////////////////////////////////////
///// Events /////
////////////////////////////////////////////

void GPWebBrowser2::OnStatusTextChangeExplorer(LPCTSTR Text)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnStatusText"))
	{
 		CString strEvt(Text);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnStatusText",(LPCSTR)strEvt);
	}
}

void GPWebBrowser2::OnProgressChangeExplorer(long Progress, long ProgressMax)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnProgress"))
	{
		CString strEvt;
		strEvt.Format("%ld\x7F%ld", Progress, ProgressMax);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnProgress",(LPCSTR)strEvt);
	}
}

void GPWebBrowser2::OnCommandStateChangeExplorer(long Command, BOOL Enable)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnCommandState"))
	{
		CString strEvt;
		strEvt.Format("%ld\x7F%d", Command, Enable);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnCommandState",(LPCSTR)strEvt);
	}
}

void GPWebBrowser2::OnDownloadBeginExplorer()
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnDownloadBegin"))
	{
			referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnDownloadBegin","");
	}
}

void GPWebBrowser2::OnDownloadCompleteExplorer()
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnDownloadComplete"))
	{
			referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnDownloadComplete","");
	}
}

void GPWebBrowser2::OnTitleChangeExplorer(LPCTSTR Text)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnTitle"))
	{
		CString strEvt(Text);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnTitle",(LPCSTR)strEvt);
	}
}

void GPWebBrowser2::OnPropertyChangeExplorer(LPCTSTR szProperty)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnProperty"))
	{
		CString strEvt(szProperty);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnProperty",(LPCSTR)strEvt);
	}
}

void GPWebBrowser2::OnBeforeNavigate2Explorer(LPDISPATCH pDisp, VARIANT FAR* URL, VARIANT FAR* Flags, VARIANT FAR* TargetFrameName, VARIANT FAR* PostData, VARIANT FAR* Headers, BOOL FAR* Cancel)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && URL)
	{
		USES_CONVERSION;
		CString strEvt(URL->bstrVal);
		strEvt += "\x7F";
		if (Flags) NavConstToString(Flags->lVal);
		strEvt += "\x7F";
		if (TargetFrameName) strEvt +=TargetFrameName->bstrVal;
		strEvt += "\x7F";
		CString tmps;
		ConvVariantToString(*PostData,tmps,"\x07");
		strEvt+=tmps+"\x7F";
		ConvVariantToString(*Headers,tmps,"\x07");
		strEvt+=tmps+"\x7F";

		if (referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnBeforeNavigate2A"))
		{
			referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnBeforeNavigate2A",(LPCSTR)strEvt);
			if ((m_JustDoIt&0x1))
			{
				m_JustDoIt^=0x1;
				*Cancel=TRUE;
			}
		}
		else
		if (referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnBeforeNavigate2"))
			referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnBeforeNavigate2",(LPCSTR)strEvt);
	}
}

void GPWebBrowser2::OnNewWindow2Explorer(LPDISPATCH FAR* ppDisp, BOOL FAR* Cancel)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive(""))
	{
		if (referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnNewWindow2A"))
		{
			*Cancel=TRUE;
			referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnNewWindow2A","");
		}
		else
		if (referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnNewWindow2"))
		{
			referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnNewWindow2","");
		}
	}
}

void GPWebBrowser2::OnNavigateComplete2Explorer(LPDISPATCH pDisp, VARIANT FAR* URL)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnNavigateComplete2"))
	{
		USES_CONVERSION;
		CString strEvt(URL->bstrVal);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnNavigateComplete2",(LPCSTR)strEvt);
	}
}

void GPWebBrowser2::OnDocumentCompleteExplorer(LPDISPATCH pDisp, VARIANT FAR* URL)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnDocumentComplete"))
	{
		USES_CONVERSION;
		CString strEvt(URL->bstrVal);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnDocumentComplete",(LPCSTR)strEvt);
	}
}

void GPWebBrowser2::OnOnQuitExplorer()
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnQuit"))
	{
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnQuit","");
	}
}

void GPWebBrowser2::OnOnVisibleExplorer(BOOL Visible)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnVisible"))
	{
		char str[25];
		sprintf(str,"%d",Visible);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnVisible",str);
	}
}

void GPWebBrowser2::OnOnToolBarExplorer(BOOL ToolBar)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnToolBar"))
	{
		char str[25];
		sprintf(str,"%d",ToolBar);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnToolBar",str);
	}
}

void GPWebBrowser2::OnOnMenuBarExplorer(BOOL MenuBar)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnMenuBar"))
	{
		char str[25];
		sprintf(str,"%d",MenuBar);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnMenuBar",str);
	}
}

void GPWebBrowser2::OnOnStatusBarExplorer(BOOL StatusBar)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnStatusBar"))
	{
		char str[25];
		sprintf(str,"%d",StatusBar);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnStatusBar",str);
	}
}

void GPWebBrowser2::OnOnFullScreenExplorer(BOOL FullScreen)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnFullScreen"))
	{
		char str[25];
		sprintf(str,"%d",FullScreen);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnFullScreen",str);
	}
}

void GPWebBrowser2::OnOnTheaterModeExplorer(BOOL TheaterMode)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnTheaterMode"))
	{
		char str[25];
		sprintf(str,"%d",TheaterMode);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnTheaterMode",str);
	}
}

void GPWebBrowser2::OnWindowSetResizableExplorer(BOOL Resizable)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnSetResizable"))
	{
		char str[25];
		sprintf(str,"%d",Resizable);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnSetResizable",str);
	}
}

void GPWebBrowser2::OnWindowSetLeftExplorer(long Left)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnSetLeft"))
	{
		char str[25];
		sprintf(str,"%d",Left);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnSetLeft",str);
	}
}

void GPWebBrowser2::OnWindowSetTopExplorer(long Top)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnSetTop"))
	{
		char str[25];
		sprintf(str,"%d",Top);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnSetTop",str);
	}
}

void GPWebBrowser2::OnWindowSetWidthExplorer(long Width)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnSetWidth"))
	{
		char str[25];
		sprintf(str,"%d",Width);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnSetWidth",str);
	}
}

void GPWebBrowser2::OnWindowSetHeightExplorer(long Height)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnSetHeight"))
	{
		char str[25];
		sprintf(str,"%d",Height);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnSetHeight",str);
	}
}

void GPWebBrowser2::OnWindowClosingExplorer(BOOL IsChildWindow, BOOL FAR* Cancel)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG)
	{
		char str[25];
		sprintf(str,"%d",IsChildWindow);
		if (referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnClosingA"))
		{
			referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnClosingA",str);
			*Cancel=TRUE;
		}
		else
		if (referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnClosing"))
			referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnClosing",str);
	}
}

void GPWebBrowser2::OnSetSecureLockIconExplorer(long SecureLockIcon)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnSetSecureLockIcon"))
	{
		char str[25];
		sprintf(str,"%d",SecureLockIcon);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnSetSecureLockIcon",str);
	}
}

void GPWebBrowser2::OnClientToHostWindowExplorer(long FAR* CX, long FAR* CY)
{
	if (referGPU && referGPU[UnitId&0xFFFF] && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnClientToHost"))
	{
		char str[25];
		sprintf(str,"%d\x7F%d",*CX,*CY);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnClientToHost",str);

	}
	if (referGPU && referGPU[UnitId&0xFFFF])
	{
		CRect re;
		if (referGPU[UnitId&0xFFFF] && referGPU[UnitId&0xFFFF]->UnitHWND)
			::GetWindowRect(referGPU[UnitId&0xFFFF]->UnitHWND,&re);
		*CX=re.Width();
		*CY=re.Height();
	}
}


void GPWebBrowser2::OnFileDownloadExplorer(BOOL FAR* Cancel)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG)
	{
		if (referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnFileDownloadA"))
		{
			*Cancel=TRUE;
			referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnFileDownloadA","");
		}
		else
		if (referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnFileDownload"))
			referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnFileDownload","");
	}
}

void GPWebBrowser2::OnNavigateErrorExplorer(LPDISPATCH pDisp, VARIANT FAR* URL, VARIANT FAR* Frame, VARIANT FAR* StatusCode, BOOL FAR* Cancel)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG )
	{
		USES_CONVERSION;
		CString strEvt(URL->bstrVal);
		strEvt+="\x7F";
		CString csTmp(Frame->bstrVal);
		strEvt+=csTmp;
		strEvt+="\x7F"+HStatusToString(StatusCode->lVal);

		if (referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnNavigateErrorA"))
		{
			*Cancel=TRUE;
			referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnNavigateErrorA",strEvt);
		}
		else
		if (referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnNavigateError"))
			referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnNavigateError",strEvt);
	}
}

void GPWebBrowser2::OnPrintTemplateInstantiationExplorer(LPDISPATCH pDisp)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnPrintInstantiation"))
	{
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnPrintInstantiation","");
	}
}

void GPWebBrowser2::OnPrintTemplateTeardownExplorer(LPDISPATCH pDisp)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnPrintTeardown"))
	{
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnPrintTeardown","");
	}
}

void GPWebBrowser2::OnUpdatePageStatusExplorer(LPDISPATCH pDisp, VARIANT FAR* nPage, VARIANT FAR* fDone)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnUpdatePageStatus"))
	{
		CString strEvt;
		CString tmp;
		ConvVariantToString(*nPage,strEvt,"\x07");
		strEvt+="\x7F";
		ConvVariantToString(*fDone,tmp,"\x07");
		strEvt+=tmp;
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnUpdatePageStatus",strEvt);
	}
}

void GPWebBrowser2::OnPrivacyImpactedStateChangeExplorer(BOOL bImpacted)
{
	if (referGPU!=NULL && referGPU[UnitId&0xFFFF]->GPMSG && referGPU[UnitId&0xFFFF]->GPMSG->FindInActive("OnPrivacyImpactedState"))
	{
		char str[25];
		sprintf(str,"%d",bImpacted);
		referGPU[UnitId&0xFFFF]->GPMSG->GPSendObjEvent(m_hWnd, UnitId,"OnPrivacyImpactedState",str);
	}
}

//////////////////////////////
/// tools
//////////////////////////////

const CString GPWebBrowser2::RefrLevelToString(UINT iRefrLevel)
{
	CString ret;
	UINT i;
	for(i=0;i<uNRefrLevel;i++)
		if ((iRefrLevel&uArrRefrLevel[i])==uArrRefrLevel[i])
		{
			if (ret=="") ret=cArrRefrLevel[i];
			else {ret+="|";ret+=cArrRefrLevel[i];}
		}
	return ret;
}

UINT GPWebBrowser2::StringToRefrLevel(const char* iStr)
{
	UINT ret=0;
	if (iStr==NULL)
	{
		UINT i;
		for(i=0;i<uNRefrLevel;i++)
			ret|=uArrRefrLevel[i];
	}
	else
	{
		CString tmps=iStr;
		tmps.MakeUpper();
		tmps+="|";
		tmps.Replace(" ","");

		UINT i;
		for(i=0;i<uNRefrLevel;i++)
			if (tmps.Find(cArrRefrLevel[i],0)>=0) ret|=uArrRefrLevel[i];
	}

	return ret;
}

const CString GPWebBrowser2::NavConstToString(UINT iNavConst)
{
	CString ret;
	UINT i;
	for(i=0;i<uNNavConst;i++)
		if ((iNavConst&uArrNavConst[i])==uArrNavConst[i])
		{
			if (ret=="") ret=cArrNavConst[i];
			else {ret+="|";ret+=cArrNavConst[i];}
		}
	return ret;
}

UINT GPWebBrowser2::StringToNavConst(const char* iStr)
{
	UINT ret=0;
	if (iStr==NULL)
	{
		UINT i;
		for(i=0;i<uNNavConst;i++)
			ret|=uArrNavConst[i];
	}
	else
	{
		CString tmps=iStr;
		tmps.MakeUpper();
		tmps+="|";
		tmps.Replace(" ","");

		UINT i;
		for(i=0;i<uNNavConst;i++)
			if (tmps.Find(cArrNavConst[i],0)>=0) ret|=uArrNavConst[i];
	}

	return ret;
}

const CString GPWebBrowser2::HStatusToString(UINT iHStatus)
{
	CString ret;
	UINT i;
	for(i=0;i<uNHStatus;i++)
		if ((iHStatus&uArrHStatus[i])==uArrHStatus[i])
		{
			if (ret=="") ret=cArrHStatus[i];
			else {ret+="|";ret+=cArrHStatus[i];}
		}
	return ret;
}

UINT GPWebBrowser2::StringToHStatus(const char* iStr)
{
	UINT ret=0;
	if (iStr==NULL)
	{
		UINT i;
		for(i=0;i<uNHStatus;i++)
			ret|=uArrHStatus[i];
	}
	else
	{
		CString tmps=iStr;
		tmps.MakeUpper();
		tmps+="|";
		tmps.Replace(" ","");

		UINT i;
		for(i=0;i<uNHStatus;i++)
			if (tmps.Find(cArrHStatus[i],0)>=0) ret|=uArrHStatus[i];
	}

	return ret;
}

const CString GPWebBrowser2::ReadyStateToString(UINT iReadyState)
{
	CString ret;
	UINT i;
	for(i=0;i<uNReadyState;i++)
		if (iReadyState==READYSTATE_UNINITIALIZED || (uArrReadyState[i]!=READYSTATE_UNINITIALIZED && (iReadyState&uArrReadyState[i])==uArrReadyState[i]))
		{
			if (ret=="") ret=cArrReadyState[i];
			else {ret+="|";ret+=cArrReadyState[i];}
		}
	return ret;
}

UINT GPWebBrowser2::StringToReadyState(const char* iStr)
{
	UINT ret=0;
	if (iStr==NULL)
	{
		UINT i;
		for(i=0;i<uNReadyState;i++)
			ret|=uArrReadyState[i];
	}
	else
	{
		CString tmps=iStr;
		tmps.MakeUpper();
		tmps+="|";
		tmps.Replace(" ","");

		UINT i;
		for(i=0;i<uNReadyState;i++)
			if (tmps.Find(cArrReadyState[i],0)>=0) ret|=uArrReadyState[i];
	}

	return ret;
}

void GPWebBrowser2::OnHScroll(UINT nSBCode, UINT nPos, CScrollBar* pScrollBar)
{
	CWnd::OnHScroll(nSBCode, nPos, pScrollBar);
	if (referGPU && referGPU[UnitId&0xFFFF]->m_SizerArray)	Invalidate();
}

void GPWebBrowser2::OnVScroll(UINT nSBCode, UINT nPos, CScrollBar* pScrollBar)
{
	CWnd::OnVScroll(nSBCode, nPos, pScrollBar);
	if (referGPU && referGPU[UnitId&0xFFFF]->m_SizerArray)	Invalidate();
}

HBRUSH GPWebBrowser2::OnCtlColor(CDC* pDC, CWnd* pWnd, UINT nCtlColor) 
{
	HBRUSH hbr = NULL;
	if (referGPU && referGPU[UnitId&0xFFFF]->m_brBkgnd) 
	{
		hbr = (HBRUSH) *(referGPU[UnitId&0xFFFF]->m_brBkgnd);
	    RECT rc;
		::GetWindowRect(pWnd->m_hWnd, &rc);
		::MapWindowPoints(NULL, m_hWnd, (POINT *)&rc, 2);
		::SetBrushOrgEx(pDC->m_hDC, -rc.left, -rc.top, NULL);
	}

	if (pWnd && pDC && pWnd->m_hWnd && pDC->m_hDC)
		GPUnit::ChildCtlColor(referGPU, pDC->m_hDC, pWnd->m_hWnd, hbr, CWnd::OnCtlColor(pDC, pWnd, nCtlColor), nCtlColor);

	return hbr;
}

int GPWebBrowser2::AddChar(char iChar, DWORD iFlags)
{
	return 0;
}
