#if !defined(AFX_GPOLEFONT_H__796FD454_A655_4B38_81C3_C672A06EB688__INCLUDED_)
#define AFX_GPOLEFONT_H__796FD454_A655_4B38_81C3_C672A06EB688__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// GPCOleFont wrapper class

class GPCOleFont : public COleDispatchDriver
{
public:
	GPCOleFont() {}		// Calls COleDispatchDriver default constructor
	GPCOleFont(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	GPCOleFont(const GPCOleFont& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetName();
	void SetName(LPCTSTR);
	CY GetSize();
	void SetSize(const CY&);
	BOOL GetBold();
	void SetBold(BOOL);
	BOOL GetItalic();
	void SetItalic(BOOL);
	BOOL GetUnderline();
	void SetUnderline(BOOL);
	BOOL GetStrikethrough();
	void SetStrikethrough(BOOL);
	short GetWeight();
	void SetWeight(short);
	short GetCharset();
	void SetCharset(short);

// Operations
public:
	const CString GetFontDescription();
	void SetFontFromString(const char *iStr);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GPOLEFONT_H__796FD454_A655_4B38_81C3_C672A06EB688__INCLUDED_)
