#if !defined(AFX_GPPICTURE_H__5B394067_3019_4EF5_9AD6_915240E81F38__INCLUDED_)
#define AFX_GPPICTURE_H__5B394067_3019_4EF5_9AD6_915240E81F38__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// GPCPicture wrapper class

class GPCPicture : public COleDispatchDriver
{
public:
	GPCPicture() {}		// Calls COleDispatchDriver default constructor
	GPCPicture(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	GPCPicture(const GPCPicture& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetHandle();
	long GetHPal();
	void SetHPal(long);
	short GetType();
	long GetWidth();
	long GetHeight();

// Operations
public:
	// method 'Render' not emitted because of invalid return type or parameter type
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GPPICTURE_H__5B394067_3019_4EF5_9AD6_915240E81F38__INCLUDED_)
