//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GP_Term.rc
//
#define IDOK2                           3
#define IDR_SRVR_INPLACE                4
#define IDR_SRVR_EMBEDDED               5
#define IDR_CNTR_INPLACE                6
#define IDP_OLE_INIT_FAILED             100
#define IDD_GP_TERM_FORM                101
#define IDP_FAILED_TO_CREATE            102
#define IDR_GP_TERM                     103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_GPTINTERFACE                105
#define IDR_AUTOSIZING                  106
#define IDR_CONNECTOR                   107
#define IDB_SPLASH                      108
#define IDC_RICHEDITPRG                 109
#define IDR_COMIMPORT                   110
#define IDR_MAINFRAME                   128
#define IDR_GP_TERTYPE                  129
#define IDR_DEVTOOLBAR                  130
#define IDD_COM_SETINGS                 131
#define IDR_GP_TERTYPEWARN              132
#define IDD_DIALOGOLESET                133
#define IDD_DIALOGSENDFILE              134
#define IDD_DIALOGPAGESETUP             135
#define IDD_DIALOGFINDREPLACE           141
#define IDR_STRINGDOCTMPL               142
#define IDD_DLGMETHODS                  144
#define IDD_DIALOGCOLOR                 145
#define IDD_DIALOGCOMMTYPE              146
#define IDD_DIALOGBAR                   147
#define IDD_DIALOGPROGRESS              148
#define IDD_DIALOGTELSET                149
#define IDD_DIALOGADMISON               150
#define IDD_DIALOGTERMSET               151
#define IDD_DIALOGDRAWEDIT              152
#define IDD_DLGCONTROLINIT              153
#define IDD_DIALOGVIEWSPR               154
#define IDD_DIALOGVIEWVARS              155
#define IDD_DIALOGVIEWITEM              156
#define IDD_DIALOGDEBUG                 157
#define IDD_DIALOGDUMPSETTINGS          158
#define IDD_DIALOGOBJECTS               159
#define IDD_DIALOGSMBTABLE              160
#define IDD_DIALOGNEWVALUE              161
#define IDD_DIALOGNEWSPR                164
#define IDD_DLGCLIENTFILES              165
#define IDD_DIALOGREGISTER              171
#define IDD_DIALOGVIEWIOFILES           176
#define IDD_DIALOGVIEWFSMETHODS         177
#define IDD_DIALOGEDITORCLR             182
#define IDD_DIALOGVIEWREGMETHODS        183
#define IDC_CURSOR_HGETLEFT             185
#define IDC_CURSOR_HDRAW                186
#define IDC_CURSOR_HEDIT                187
#define IDC_CURSOR_HGET                 188
#define IDC_CURSOR5                     189
#define IDC_CURSOR6                     190
#define IDC_CURSOR7                     191
#define IDC_CURSOR8                     192
#define IDC_CURSOR9                     193
#define IDD_DIALOGNOTEPADSET            195
#define IDB_BITMAPTBMF                  197
#define IDB_BITMAPTBDEV                 198
#define IDD_ABOUTBOX                    200
#define IDD_DLGVIEWINPUTSET             202
#define IDD_DLGVIEWOUTPUTSET            203
#define IDD_DLGVIEWINPUT                204
#define IDD_DLGVIEWOUTPUT               205
#define IDD_DLGVIEWINPUTALL             206
#define IDD_DLGSEPARATEVIEW             208
#define IDD_DLGVIEWINFRAME              209
#define IDC_CURSOR_HO_SIZEB             212
#define IDR_VERSION2                    213
#define IDB_BITMAPSEPVIEW               217
#define IDB_BITMAPSEPVIEWDIS            218
#define IDD_DLGFILEITEMNAME             219
#define IDD_DLGKEYWORDS                 220
#define IDD_DLGSCFIND                   221
#define IDD_DLGKEYEDITOR                222
#define IDD_DLGVIEWIMAGELISTS           223
#define IDD_DLGCREATEIMAGELIST          224
#define IDD_DLGIMAGEMASK                225
#define IDD_DLGCODECO                   226
#define IDD_DLGTERMCAP                  227
#define IDR_VERSION3                    228
#define IDD_DLGEDITCONTEXTMENU          229
#define IDD_DLGTERMCAP_TERMINAL         230
#define IDD_DIALOGVIEWCONTMENUMETH      231
#define IDR_VERSION4                    231
#define IDD_DLGTERMCAP_ESC              232
#define IDD_DLGTERMCAP_KBD              233
#define IDD_DLGTERMCAPESCLINE           234
#define IDR_VERSION5                    235
#define IDD_DLGSTATISTICS               236
#define IDD_DIALOGVIEWSYSTEMMETH        237
#define IDR_VERSION6                    237
#define IDD_DIALOGEDPRINT               238
#define IDD_DLGDELIMITERS               239
#define IDR_VERSION7                    240
#define IDR_VERSION8                    241
#define IDR_VERSION9                    242
#define IDD_DIALOGSSH                   243
#define IDD_DIALOGLOGIN                 245
#define IDD_DLGFONTSET                  246
#define IDD_DLGGUISET                   247
#define IDD_DIALOGNEWSESSION            248
#define IDD_DIALOGGRAPHCODE             249
#define IDD_DIALOGCMDMIXER              250
#define IDC_CURSOR1                     251
#define IDD_DLGSCREENSIZE               252
#define IDD_DLGERRORS                   253
#define IDC_PORTCOMBO                   1000
#define IDC_BUTTONINVERT                1001
#define IDC_EDWAITTCL                   1002
#define IDC_BAUDCOMBO                   1003
#define IDC_BUTTONDEFAULT               1004
#define IDC_BUTTONCOMCONF2              1005
#define IDC_EDWAITFWRITE                1006
#define IDC_CHECKABORTONERROR           1007
#define IDC_BUTTONCOMCONF3              1008
#define IDC_EDWAITFOTHER                1009
#define IDC_PARITYCOMBO                 1010
#define IDC_BUTTONCOMCONF4              1011
#define IDC_DATABITSCOMBO               1012
#define IDC_BUTTONCOMCONF5              1013
#define IDC_CHECKPRINT                  1014
#define IDC_SPINWAITTCL                 1015
#define IDC_CHECKSLAVEPRINT             1015
#define IDC_STOPBITSCOMBO               1016
#define IDC_CHECKSLAVEPRINTCHARVIEW     1016
#define IDC_BUTTONCOMCONF1              1017
#define IDC_CHECKSLAVEPRINTASTEXT       1017
#define IDC_SPINWAITSUB                 1018
#define IDC_CHECKBINARY                 1019
#define IDC_BUTTONCOMCONF6              1020
#define IDC_CHECKBEEP                   1021
#define IDC_SPINWAITFOTHER              1022
#define IDC_CHECKDSRSENSITIVITY         1023
#define IDC_CHECKKEYBUF                 1024
#define IDC_SPINWAITINPUT               1025
#define IDC_CHECKERRORCHAR              1026
#define IDC_CHECKEXIT                   1027
#define IDC_BUTOLEDEFLOAD               1028
#define IDC_CHECKINX                    1029
#define IDC_CHECKEXIT2                  1030
#define IDC_CHECKNULLREPLACE            1031
#define IDC_CHECKEXIT3                  1032
#define IDC_CHECKOUTX                   1033
#define IDC_CHECKUOTXCTSFLOW            1034
#define IDC_CHECKUOTXDSRFLOW            1035
#define IDC_CHECKTXCONTONXOFF           1036
#define IDC_DTRCONTROL                  1037
#define IDC_RTSCONTROL                  1038
#define IDC_CHECKPARITY                 1039
#define IDC_EDITPACKETSIZE              1040
#define IDC_EDIT3                       1041
#define IDC_EDITPORT                    1042
#define IDC_EDITFRG                     1043
#define IDC_EDITINITDALAY               1044
#define IDC_EDITBRUSH                   1045
#define IDC_EDITWS                      1046
#define IDC_EDITREGION                  1047
#define IDC_EDITWSE                     1048
#define IDC_EDITOS                      1049
#define IDC_EDITOSE                     1050
#define IDC_CHECKTOPMOST                1051
#define IDC_BUTTON1                     1052
#define IDC_EDITKBD                     1053
#define IDC_BUTTONTEST                  1053
#define IDC_BUTTON7                     1053
#define IDC_BUTTON6                     1053
#define IDC_BUTTONUNREG                 1054
#define IDC_EDITCONTEXTMENU             1054
#define IDC_BUTTON8                     1054
#define IDC_BUTTON3                     1055
#define IDC_PROGRESS1                   1056
#define IDC_BUTTONINSERT                1056
#define IDC_BUTTONSAVE                  1057
#define IDC_BUTTON4                     1058
#define IDC_BUTTONAPPLY                 1058
#define IDC_SFSORSE                     1059
#define IDC_BUTTONLOAD                  1060
#define IDC_SFDEST                      1061
#define IDC_CHECKCRLF                   1062
#define IDC_SFLENGTH                    1063
#define IDC_CHECKCRLF2                  1063
#define IDC_COMBOFONT                   1064
#define IDC_CHECKLOCKECHO               1065
#define IDC_COMBODEFCHRCOLOR            1066
#define IDC_CHECKLOCKEND                1066
#define IDC_IPADDRESS1                  1067
#define IDC_COMBOSIZINGMODE             1067
#define IDC_COMBODEFBKGCOLOR            1068
#define IDC_CHECKLOCKEND2               1068
#define IDC_COMBOFIND                   1069
#define IDC_COMBODEFBKGCOLOR2           1069
#define IDC_COMBOREPLACE                1070
#define IDC_BUTTONREPLACE               1071
#define IDC_RADIO1                      1072
#define IDC_BUTTONREPLACEALL            1073
#define IDC_RADIOSSH2                   1073
#define IDC_RADIOSOCKET                 1073
#define IDC_RADIOASONSCREEN             1073
#define IDC_RADIO2                      1074
#define IDC_RADIOCUSTOM                 1074
#define IDC_CHECKCAPS                   1075
#define IDC_RADIO3                      1076
#define IDC_CHECKWORD                   1077
#define IDC_RADIO4                      1078
#define IDC_BUTTONFINDNEXT              1079
#define IDC_RADIO5                      1080
#define IDC_BUTTONFINDPREV              1081
#define IDC_RADIO6                      1082
#define IDC_CHECKSELECTION              1083
#define IDC_RADIO7                      1084
#define IDC_RADIOUP                     1085
#define IDC_RADIO8                      1086
#define IDC_RADIODOWN                   1087
#define IDC_CHECKSELECT                 1088
#define IDC_RADIO9                      1089
#define IDC_CHECKCLIPBOARD              1090
#define IDC_COMBO1                      1091
#define IDC_RADIO10                     1092
#define IDC_COMBOCOLOR                  1092
#define IDC_COMBO5                      1092
#define IDC_COMBO4                      1093
#define IDC_RADIO11                     1094
#define IDC_COMBO6                      1094
#define IDC_BUTTON2                     1095
#define IDC_RADIO12                     1096
#define IDC_BUTTON9                     1096
#define IDC_CHECK1                      1097
#define IDC_RADIO13                     1098
#define IDC_COMBOMETHODS                1099
#define IDC_CHWARNINGS                  1099
#define IDC_CHECK2                      1100
#define IDC_CHWARNINGS2                 1100
#define IDC_RADIO14                     1101
#define IDC_CHWARNINGSW                 1101
#define IDC_EDITRESULT                  1102
#define IDC_CHECKOPAQUE                 1102
#define IDC_CHWARNINGSW2                1102
#define IDC_CHECK3                      1103
#define IDC_CHECKBLINK                  1103
#define IDC_RADIO15                     1104
#define IDC_CHECK9                      1105
#define IDC_CHECKGRAPH                  1105
#define IDC_EDITEVENTS                  1106
#define IDC_RADIO16                     1107
#define IDC_EDITPARAMSHELP              1108
#define IDC_RADIO17                     1109
#define IDC_EDITPARAMS                  1110
#define IDC_SLIDER5                     1111
#define IDC_BTNDOPROPERTY               1112
#define IDC_STATIC_RED                  1113
#define IDC_STATICPROPERTY              1114
#define IDC_RADIO18                     1115
#define IDC_EDITEVENTSOUTPUT            1116
#define IDC_RADIO19                     1117
#define IDC_LIST1                       1118
#define IDC_LISTEVENTS                  1119
#define IDC_LIST16                      1119
#define IDC_RADIO20                     1120
#define IDC_LIST17                      1120
#define IDC_BTNCLALLEV                  1121
#define IDC_LIST18                      1121
#define IDC_LIST2                       1122
#define IDC_RADIO21                     1123
#define IDC_BTNCLALLTEXT                1124
#define IDC_LIST3                       1125
#define IDC_RADIO22                     1126
#define IDC_BTNBKG                      1127
#define IDC_LIST4                       1128
#define IDC_RADIO23                     1129
#define IDC_BTNFRG                      1130
#define IDC_LIST5                       1131
#define IDC_RADIO24                     1132
#define IDC_BTNBRUSH                    1133
#define IDC_LIST6                       1134
#define IDC_STATIC_GREEN                1135
#define IDC_EDITBKG                     1136
#define IDC_LIST7                       1137
#define IDC_SLIDER6                     1138
#define IDC_CBBRUSHSTYLE                1139
#define IDC_LIST8                       1140
#define IDC_SLIDER7                     1141
#define IDC_CBBRUSHTYPE                 1142
#define IDC_LIST9                       1143
#define IDC_STATIC_BLUE                 1144
#define IDC_BTNBRUSHDLG                 1145
#define IDC_LIST10                      1146
#define IDC_SLIDER8                     1147
#define IDC_EDITEOFCHAR                 1148
#define IDC_BTNFRGDLG                   1149
#define IDC_EDITPOINT                   1150
#define IDC_LIST11                      1151
#define IDC_SLIDER9                     1152
#define IDC_EDITERRORCHAR               1153
#define IDC_BTNBKGDLG                   1154
#define IDC_EDITRECT                    1155
#define IDC_LIST12                      1156
#define IDC_SLIDER10                    1157
#define IDC_EDITEVENTCHAR               1158
#define IDC_RADIOCOMM1                  1159
#define IDC_LIST13                      1160
#define IDC_STATIC_RED2                 1161
#define IDC_EDITXOFFCHAR                1162
#define IDC_BTCOLOR                     1163
#define IDC_LIST14                      1164
#define IDC_STATIC_GREEN2               1165
#define IDC_EDITXONCHAR                 1166
#define IDC_RADIOCOMM3                  1167
#define IDC_EDITCOLOR                   1168
#define IDC_LIST15                      1169
#define IDC_STATIC_BLUE2                1170
#define IDC_EDITXONLIM                  1171
#define IDC_RADIOCOMM4                  1172
#define IDC_BUTTONRELOAD                1173
#define IDC_EDITXOFFLIM                 1174
#define IDC_RADIOCOMM2                  1175
#define IDC_EDITICON                    1176
#define IDC_EDITCLSID                   1177
#define IDC_RADIOCOMM5                  1178
#define IDC_EDITINITSTR                 1179
#define IDC_EDITITEMS                   1180
#define IDC_STATICPARAMS                1181
#define IDC_RADIOCOMM6                  1182
#define IDC_EDITCOMMENT                 1183
#define IDC_EDITFONT                    1184
#define IDC_BTNEXECUTE                  1185
#define IDC_EDITPEN                     1186
#define IDC_BTNEXECUTE2                 1186
#define IDC_GROUP                       1187
#define IDC_EDITINITSTR2                1188
#define IDC_EDITINT                     1189
#define IDC_EDITCMDLINE                 1189
#define IDC_LISTFILTERS                 1190
#define IDC_EDITDOUBLE                  1191
#define IDC_TABVAR                      1192
#define IDC_EDITURECT                   1193
#define IDC_EDITUPOINT                  1194
#define IDC_EDITDBSC                    1195
#define IDC_EDITDASC                    1196
#define IDC_EDIT1                       1197
#define IDC_LISTSTACK                   1198
#define IDC_EDIT16                      1198
#define IDC_EDITDBSL                    1199
#define IDC_EDITITEM                    1199
#define IDC_EDITDUMPNCHAR               1200
#define IDC_EDIT2                       1201
#define IDC_STATICSTACK                 1202
#define IDC_EDITMAXDATA                 1202
#define IDC_EDITDASL                    1203
#define IDC_EDWAITSUB                   1204
#define IDC_LISTVARS                    1205
#define IDC_EDIT4                       1206
#define IDC_EDITDUMPREFIX               1207
#define IDC_EDITDBSB                    1208
#define IDC_EDWAITFREAD                 1209
#define IDC_STATICWATCH                 1210
#define IDC_EDIT7                       1211
#define IDC_EDITDASB                    1212
#define IDC_EDIT5                       1213
#define IDC_BTNBREAK                    1214
#define IDC_EDIT8                       1215
#define IDC_EDIT6                       1216
#define IDC_BTNGO                       1217
#define IDC_EDIT9                       1218
#define IDC_EDWAITINPUT                 1219
#define IDC_EDITNGO                     1220
#define IDC_EDIT10                      1221
#define IDC_STATICVERSION               1222
#define IDC_EDWAITSYSTEM                1223
#define IDC_EDIT11                      1224
#define IDC_EDITDELAY                   1225
#define IDC_EDWAITMM                    1226
#define IDC_EDITNPRGLINE                1227
#define IDC_EDIT12                      1228
#define IDC_EDITDELAYCURSOR             1229
#define IDC_EDCNTTCL                    1230
#define IDC_EDIT13                      1231
#define IDC_EDCNTSUB                    1232
#define IDC_BUTTONUPD                   1233
#define IDC_EDITBREAKCHAR               1234
#define IDC_EDIT14                      1235
#define IDC_EDCNTFREAD                  1236
#define IDC_BUTTONNEWVALUE              1237
#define IDC_EDITDELAY2                  1238
#define IDC_EDIT15                      1239
#define IDC_EDITBORDERL                 1239
#define IDC_CHECKDUMPIN                 1240
#define IDC_EDITBORDERR                 1240
#define IDC_EDCNTFWRITE                 1241
#define IDC_EDITBORDERT                 1241
#define IDC_BUTTONADD                   1242
#define IDC_EDITBORDERB                 1242
#define IDC_CHECKDUMPOUT                1243
#define IDC_BUTTONADDCOPY               1243
#define IDC_EDCNTFOTHER                 1244
#define IDC_BUTTONEXPORT                1244
#define IDC_BUTTONDEL                   1245
#define IDC_BUTTONIMPORT                1245
#define IDC_CHECKDUMPREM                1246
#define IDC_EDCNTINPUT                  1247
#define IDC_EDIT18                      1248
#define IDC_CHECKDUMPINHEX              1249
#define IDC_EDCNTSYSTEM                 1250
#define IDC_EDIT19                      1251
#define IDC_CHECKDUMPINDEC              1252
#define IDC_EDCNTMM                     1253
#define IDC_CHECKAUTOUPDATE             1254
#define IDC_EDIT20                      1255
#define IDC_CHECKDUMPINCHAR             1256
#define IDC_EDCNTTCL2                   1257
#define IDC_BTNADD                      1258
#define IDC_EDIT21                      1259
#define IDC_CHECKDUMPOUTHEX             1260
#define IDC_EDCNTSUB2                   1261
#define IDC_BTNDELETE                   1262
#define IDC_EDIT22                      1263
#define IDC_CHECKDUMPOUTDEC             1264
#define IDC_EDCNTFREAD2                 1265
#define IDC_EDITNFIELDS                 1266
#define IDC_BTNDELETETEXT               1267
#define IDC_EDIT23                      1268
#define IDC_CHECKDUMPOUTCHAR            1269
#define IDC_EDCNTFWRITE2                1270
#define IDC_EDITNAME                    1271
#define IDC_EDIT24                      1272
#define IDC_CHECKDUMPREMHEX             1273
#define IDC_EDCNTFOTHER2                1274
#define IDC_LISTNAMEDDATA               1275
#define IDC_EDIT25                      1276
#define IDC_CHECKDUMPREMDEC             1277
#define IDC_EDCNTINPUT2                 1278
#define IDC_LISTOBJNAME                 1279
#define IDC_CHECKDUMPREMCHAR            1280
#define IDC_EDCNTSYSTEM2                1281
#define IDC_CHECKDUMPREMID              1282
#define IDC_EDCNTMM2                    1283
#define IDC_CHSO_DEBUG                  1284
#define IDC_EDITDUMPNLINE               1285
#define IDC_CHSO_DONTLINGER             1286
#define IDC_CHECKDUMPSPACE              1287
#define IDC_CHSO_DONTROUTE              1288
#define IDC_CHECKDUMPCRLF               1289
#define IDC_CHSO_KEEPALIVE              1291
#define IDC_EDITUNREG                   1292
#define IDC_EDSO_LINGER                 1293
#define IDC_EDITREG                     1294
#define IDC_EDSO_LINGER2                1295
#define IDC_BUTTONREG                   1296
#define IDC_CHSO_OOBINLINE              1297
#define IDC_TREE1                       1298
#define IDC_EDSO_RCVBUF                 1299
#define IDC_CHSO_REUSEADDR              1301
#define IDC_BUTTONDELETE                1303
#define IDC_EDSO_CONNECT_TIME           1304
#define IDC_EDSO_SNDBUF                 1306
#define IDC_BUTTONEDIT                  1306
#define IDC_CHTCP_NODELAY               1307
#define IDC_BUTTONRENAME                1307
#define IDC_CHSO_SYNCHRONOUS_ALERT      1308
#define IDC_COMBOIOFILES                1309
#define IDC_BUTTONMORE                  1310
#define IDC_SPIN1                       1311
#define IDC_SPIN2                       1312
#define IDC_SPINWAITFREAD               1313
#define IDC_CHECKWINDOWLESS             1314
#define IDC_SPINWAITFWRITE              1315
#define IDC_EDITTITLE                   1316
#define IDC_LISTUNIT                    1317
#define IDC_SPINWAITSYSTEM              1318
#define IDC_EDITTITLE2                  1319
#define IDC_SPIN5                       1321
#define IDC_CHSO_ACCEPTCONN             1322
#define IDC_EDITTITLE3                  1323
#define IDC_SLIDERFRG                   1324
#define IDC_SPIN6                       1325
#define IDC_CHSO_OPTIONS                1326
#define IDC_STATICRGB                   1327
#define IDC_LISTUNITTYPE                1328
#define IDC_SPINWAITMM                  1329
#define IDC_SLIDERBKG                   1330
#define IDC_LISTUSESTL                  1332
#define IDC_SPINCNTTCL                  1333
#define IDC_STATICFRG                   1334
#define IDC_LISTUSESTL2                 1335
#define IDC_SPINCNTSUB                  1336
#define IDC_STATICBKG                   1337
#define IDC_TAB1                        1338
#define IDC_SPINCNTFREAD                1339
#define IDC_STATIC1                     1340
#define IDC_SPINCNTFWRITE               1341
#define IDC_STATIC_2                    1341
#define IDC_STATIC_3                    1342
#define IDC_EDITFONTSIZE                1343
#define IDC_STATIC_4                    1343
#define IDC_STATIC2                     1344
#define IDC_EDITFONTSIZE2               1344
#define IDC_STATIC_5                    1344
#define IDC_SPINCNTFOTHER               1345
#define IDC_STATIC8                     1345
#define IDC_STATIC_6                    1345
#define IDC_CHECKITALIC                 1346
#define IDC_STATIC_11                   1346
#define IDC_STATIC3                     1347
#define IDC_CHECKITALIC2                1347
#define IDC_STATIC_12                   1347
#define IDC_SPINCNTINPUT                1348
#define IDC_STATIC_13                   1348
#define IDC_EDSO_RCVTIMEO               1349
#define IDC_STATIC_14                   1349
#define IDC_CHECKBOLD                   1350
#define IDC_STATIC_15                   1350
#define IDC_STATIC4                     1351
#define IDC_CHECKBOLD2                  1351
#define IDC_STATIC_16                   1351
#define IDC_SPINCNTSYSTEM               1352
#define IDC_CHECKUNDERLINE              1353
#define IDC_BUTTONUPDATE                1354
#define IDC_CHECKUNDERLINE2             1354
#define IDC_SPINCNTMM                   1355
#define IDC_EDSO_SNDTIMEO               1356
#define IDC_STATIC5                     1357
#define IDC_STATICCS                    1358
#define IDC_STATICSIZE                  1359
#define IDC_EDSO_TYPE                   1360
#define IDC_STATICCS2                   1360
#define IDC_STATICOBJSIZE               1361
#define IDC_STATICSIZE2                 1361
#define IDC_STATICFONT                  1362
#define IDC_EDITCHARSET                 1363
#define IDC_COMBOSIZING                 1364
#define IDC_STATICFONT2                 1364
#define IDC_CHECKVISIBLE                1365
#define IDC_EDITCHARSET2                1365
#define IDC_EDITSIZING                  1366
#define IDC_CHECKHOTSPOT                1367
#define IDC_STATICSIZING                1368
#define IDC_CHECKEOLFILLED              1369
#define IDC_STATICTEXT                  1370
#define IDC_CHECKEOLFILLED2             1370
#define IDC_COMBOCASE                   1371
#define IDC_EDITTEXT                    1372
#define IDC_COMBOCASE2                  1372
#define IDC_STATICCASE                  1373
#define IDC_COMBOTERMTYPE               1374
#define IDC_STATICCASE2                 1374
#define IDC_BUTTONCREATOCLIP            1375
#define IDC_EDIT0                       1376
#define IDC_EDITTOOLTIP                 1377
#define IDC_CHECKTELNET                 1378
#define IDC_STATICTOOLTIP               1379
#define IDC_CHECKSSH                    1379
#define IDC_BUTTONCOLORS                1380
#define IDC_CHECKTELNET2                1380
#define IDC_BUTTONBUFFALL               1381
#define IDC_BUTTONCOLORS2               1381
#define IDC_CHECKHIDDEN                 1381
#define IDC_SLIDER1                     1382
#define IDC_CHECKDISABLEALT             1382
#define IDC_EDITPROPERTY                1383
#define IDC_BUTTONCOLORS3               1383
#define IDC_COMBOOWNER                  1385
#define IDC_BUTTONMESSAGETOCLIP         1387
#define IDC_STATICGROUP                 1388
#define IDC_STATICOWNER                 1389
#define IDC_EDITGROUP                   1390
#define IDC_MULTISESSIONENABLE          1391
#define IDC_MULTISESSIONWARNING         1392
#define IDC_BTNUPDATE                   1393
#define IDC_RESTORESIZE                 1393
#define IDC_APPLY                       1394
#define IDC_USEMBCONV                   1394
#define IDC_SHOWSPLASH                  1394
#define IDC_BTNVARTABLE                 1395
#define IDC_USEMBCONV2                  1395
#define IDC_EDITMAXLEN                  1396
#define IDC_USEMBCONV3                  1396
#define IDC_EDITMAXLEN2                 1397
#define IDC_LISTSYMBOL                  1398
#define IDC_LISTVIEWSET                 1399
#define IDC_BTNFONTCOLOR                1400
#define IDC_EDITSB                      1401
#define IDC_EDITCLFILE                  1402
#define IDC_EDITSRVFILE                 1403
#define IDC_EDITSRVFILE2                1404
#define IDC_BUTTONBROWSE                1405
#define IDC_BUTTONKEYWORDS              1408
#define IDC_EDITFILE                    1409
#define IDC_BUTTONFIND                  1410
#define IDC_CHECKMATCHCASE              1411
#define IDC_CHECKWHOLEWORD              1412
#define IDC_CHECKWORDSTART              1413
#define IDC_CHECKREGEXP                 1414
#define IDC_CHECKPOSIX                  1415
#define IDC_BUTTONEX                    1416
#define IDC_BUTTONEDITKEY               1422
#define IDC_BUTTONOK                    1423
#define IDC_BUTTONCANCEL                1424
#define IDC_COMBOIMAGELISTS             1425
#define IDC_COMBOTAB                    1426
#define IDC_COMBOINDENTATION            1427
#define IDC_CANCEL                      1428
#define IDC_BTNLOAD                     1429
#define IDC_BTNSAVE                     1430
#define IDC_BTNDEF                      1431
#define IDC_BTNCURRENT                  1432
#define IDC_SPIN3                       1433
#define IDC_SPIN4                       1434
#define IDC_STATICR                     1435
#define IDC_STATICG                     1436
#define IDC_STATICB                     1437
#define IDC_BUTTON5                     1438
#define IDC_COMBO3                      1439
#define IDC_COMBO2                      1440
#define IDC_CHECK4                      1441
#define IDC_CHECK5                      1442
#define IDC_CHECK6                      1443
#define IDC_CHECK7                      1444
#define IDC_CHECK8                      1445
#define IDC_BUTTONEXECUTE               1446
#define IDC_CHECK10                     1447
#define IDC_BUTTONADD2                  1448
#define IDC_BUTTONDELETE2               1449
#define IDC_COMBOLEXER                  1450
#define IDC_BUTTONKEYWORDS2             1451
#define IDC_OK                          1452
#define IDC_STATIC6                     1455
#define IDC_STATIC7                     1456
#define IDC_BUTTONCLOSE                 1457
#define IDC_BUTTONUP                    1458
#define IDC_BUTTONDOWN                  1459
#define IDC_BUTTONUP2                   1460
#define IDC_BUTTONDOWN2                 1461
#define IDC_COMBOESCTYPE                1462
#define IDC_COMBOESCVALUE               1463
#define IDC_EDITLISTENPORT              1463
#define IDC_COMBOESCVALUE2              1464
#define IDC_EDITLISTENDELAY             1464
#define IDC_COMBOMAGNIFICATION          1464
#define IDC_CHECKWORDWRAP               1465
#define IDC_CHECKHEADER                 1466
#define IDC_CHECKFOOTER                 1467
#define IDC_EDITHEADER                  1468
#define IDC_STATICHEADER                1469
#define IDC_EDITFOOTER                  1470
#define IDC_STATICFOOTER                1471
#define IDC_BUTTONPAGESETUP             1472
#define IDC_CHECKLINENUM                1473
#define IDC_COMBOFONT2                  1474
#define IDC_EDITINPUT1                  1476
#define IDC_CHECKINVERT                 1476
#define IDC_EDITINPUT2                  1477
#define IDC_BUTTONDELIMITERS            1477
#define IDC_CHECKWIDEON2POS             1477
#define IDC_EDITINPUT3                  1478
#define IDC_COMBOCP                     1478
#define IDC_EDITINPUT4                  1479
#define IDC_COMBOLANGUAGE               1479
#define IDC_EDITINPUT5                  1480
#define IDC_COMBOSUBLANGUAGE            1480
#define IDC_EDITINPUT6                  1481
#define IDC_EDITOUTPUT1                 1482
#define IDC_COMBOCOMPOSITINGQUALITY     1482
#define IDC_EDITOUTPUT2                 1483
#define IDC_COMBOINTERPOLATIONMODE      1483
#define IDC_EDITOUTPUT3                 1484
#define IDC_COMBOPIXELOFFSETMODE        1484
#define IDC_EDITOUTPUT4                 1485
#define IDC_COMBOSMOOTHINGMODE          1485
#define IDC_EDITOUTPUT5                 1486
#define IDC_COMBOTEXTCONTRAST           1486
#define IDC_EDITOUTPUT6                 1487
#define IDC_COMBOTEXTRENDERINGHINT      1487
#define IDC_STATIC_1                    1488
#define IDC_BUTTONADVANCED              1489
#define IDC_STATIC10                    1490
#define IDC_STATIC11                    1491
#define IDC_BUTTONBROWSETC              1492
#define IDC_STATICAL                    1493
#define IDC_EDITLOCALE                  1494
#define IDC_BUTTONSSH                   1495
#define IDC_RADIOSSH1                   1496
#define IDC_EDITFONTOX                  1496
#define IDC_CHECKCOMPRESSION            1497
#define IDC_EDITFONTOY                  1497
#define IDC_CHECKPSEUDOTERM             1498
#define IDC_COMBOCHARCET                1498
#define IDC_EDITFONTDX                  1498
#define IDC_CHECKCHANGEUSER             1499
#define IDC_EDITCODEPAGE                1499
#define IDC_EDITFONTDY                  1499
#define IDC_CHECKFORWARD                1500
#define IDC_EDITPASSWORD                1500
#define IDC_EDITUSERID                  1501
#define IDC_CHECKFORWARDX11             1501
#define IDC_STATICDESCRIPTION           1502
#define IDC_CHECKCONFROMOTHERHOSTS      1502
#define IDC_COMBOACTION                 1503
#define IDC_EDITUSERID2                 1503
#define IDC_CHECKCONFROMOTHERHOSTS2     1503
#define IDC_CHECKREMOTEPORTDOSAME       1503
#define IDC_EDITPASSWORD2               1504
#define IDC_CHECKDONTCOMMAND            1504
#define IDC_BUTTONCLEAR                 1505
#define IDC_CHECKDEFAULT                1506
#define IDC_EDITPOINTSIZE               1507
#define IDC_EDITWEIGHT                  1508
#define IDC_EDITREMOTECOMMAND           1508
#define IDC_EDITITALIC                  1509
#define IDC_CHECKTISAUTO                1509
#define IDC_CHECKKEYBOARDAUTO           1510
#define IDC_EDITPRIVATEKEYFILE          1511
#define IDC_EDITXLOCATION               1512
#define IDC_RADIO_MIT                   1513
#define IDC_RADIO_XDM                   1514
#define IDC_LISTENCRIPTION              1515
#define IDC_CHECKSINGLEDES              1516
#define IDC_LISTPOLICY                  1517
#define IDC_EDITMINUTES                 1518
#define IDC_RADIOCOM                    1519
#define IDC_STATICNAME                  1520
#define IDC_STATICCAPTION               1521
#define IDC_STATICLISTENPORT            1522
#define IDC_STATICLISTENTIME            1523
#define IDC_BUTTONADDCOM                1525
#define IDC_BUTTONADDSOCKET             1526
#define IDC_BUTTONLISTEN                1527
#define IDC_EDITROTNAME                 1528
#define IDC_STATICROT                   1529
#define IDC_BUTTONGRAPH                 1536
#define IDC_EDITROWS                    1537
#define IDC_EDITCOLUMNS                 1538
#define IDC_BUTTONBKGDLG                1538
#define IDC_BUTTONFRGDLG                1539
#define IDC_COMBOFRG                    1539
#define IDC_COMBOBKG                    1540
#define IDC_CHECKFULL                   1541
#define IDC_COMBOTERMINAL               1542
#define IDC_CHECKREVERSE                1543
#define IDC_CHECKALLOFF                 1544
#define IDC_COMBOSRVPC                  1545
#define IDC_COMBOPCSRV                  1546
#define IDC_COMBOLNGSRVPC               1547
#define IDC_COMBOSUBLNGSRVPC            1548
#define IDC_COMBOLNGPCSRV               1549
#define IDC_COMBOSUBLNGPCSRV            1550
#define IDC_CHECKBRSRVPC                1551
#define IDC_CHECKBRPCSRV                1552
#define IDC_COMBOCONVSRVPC              1553
#define IDC_EDITCPSRVPC                 1554
#define IDC_COMBOCONVPCSRV              1555
#define IDC_BUTTONERRORS                1555
#define IDC_COMBOWIDTHSRVPC             1556
#define IDC_CHERRORS                    1556
#define IDC_COMBOWIDTHPCSRV             1557
#define IDC_CHERRORS2                   1557
#define IDC_COMBOSHUTDOWN               1557
#define IDC_COMBOCASESRVPC              1558
#define IDC_CHERRORSW                   1558
#define IDC_EDITSVCNAME                 1558
#define IDC_COMBOCASEPCSRV              1559
#define IDC_CHERRORSW2                  1559
#define IDC_EDITSVCPARAMS               1559
#define IDC_EDITCPPCSRV                 1560
#define IDC_EDITSVCNAME2                1560
#define IDC_CHECKSVCASK                 1561
#define IDC_COMBOSVCWAIT                1563
#define IDC_COMBOQUALITY                1564
#define IDC_BUTTONPSETUP                1566
#define IDC_EDITLEFT                    1567
#define IDC_EDITRIGHT                   1568
#define IDC_EDITTOP                     1569
#define IDC_EDITBOTTOM                  1570
#define IDC_CHECKPRINTBORDERS           1571
#define IDC_RADIOFITTOPAGE              1572
#define IDC_EDITHW                      1573
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_OLESETTINGSDLG               32770
#define ID_TERM_HIDE                    32771
#define KEYB_ALTB                       32772
#define ID_COMSETTINGSDLG               32773
#define KEYALTF1                        32774
#define KEYALTF10                       32775
#define KEYALTF11                       32776
#define KEYALTF12                       32777
#define KEYALTF2                        32778
#define KEYALTF3                        32779
#define KEYALTF5                        32780
#define KEYALTF6                        32781
#define KEYALTF7                        32782
#define KEYALTF9                        32783
#define ID_KEYBLOCK                     32784
#define ID_TERMINALTYPE                 32785
#define ID_TRANSLATE_TCL                32787
#define ID_DEFCOLOR                     32790
#define ID_BUTTONCALC                   32791
#define ID_COLORDLG127                  32792
#define ID_STARTNEWSESSION              32793
#define ID_PROTERTFIELDS                32794
#define ID_SENTINITSTR                  32799
#define ID_MENUADM                      32800
#define ID_ALT_B                        32801
#define ID_TERM_SETTINGS                32802
#define ID_RECONNECT                    32803
#define ID_CLSSCR                       32804
#define ID_REMOVEALLOBJ                 32805
#define ID_REMOVEALLMENU                32806
#define ID_DUMPCLEAR                    32807
#define ID_TERM_FONT_LOCAL_SETTINGS     32808
#define ID_DUMPSTARTSTOP                32809
#define ID_DUMPPREVIEW                  32810
#define ID_BRIZMENUSHOW                 32811
#define ID_REMOVEALLDLG                 32812
#define ID_DUMPSETTINGS                 32814
#define ID_LASTTPRINTVIEW               32815
#define ID_CREATEFRAME                  32816
#define ID_LASTTPRINT                   32817
#define KEYALTF8                        32818
#define IDVK_F10                        32819
#define ID_TANDEMONOFF                  32820
#define IDM_SHOWDLGMETHODS              32821
#define ID_CLSSCR0                      32822
#define ID_CREATEDLG                    32823
#define KEYSHF10                        32824
#define IDM_DLGVIEWSPR                  32825
#define IDM_DLGDEBUGER                  32826
#define IDM_DLGPICKDATA                 32827
#define IDM_FILEDIALOG                  32828
#define ID_VIEW_DEVTOOLBAR              32829
#define ID_BREAKSLAVE                   32830
#define ID_DUMPSOCKERROR                32831
#define ID_TERM_GUI_SETTINGS            32832
#define ID_BEGINSLAVE                   32833
#define ID_ENDSLAVE                     32834
#define IDM_NOHIDEOUTPUT                32835
#define IDM_REGISTERTERM                32836
#define IDM_DLGERRORS                   32837
#define ID_DESKTOPDLG                   32849
#define IDM_DLGVIEWIOFILE               32850
#define IDM_DLGVIEWFSMETHODS            32851
#define IDS_GPOLEEXEPTION1001           32852
#define IDS_GPOLEEXEPTION1002           32853
#define IDS_GPOLEEXEPTION1003           32854
#define IDS_GPOLEEXEPTION1004           32855
#define IDS_GPOLEEXEPTION1005           32856
#define IDS_GPOLEEXEPTION1006           32857
#define IDS_GPOLEEXEPTION1007           32858
#define IDS_GPOLEEXEPTION1008           32859
#define IDS_GPOLEEXEPTION1009           32860
#define IDS_STRINGDOCTMPL               32861
#define ID_SCROBJDLG                    32862
#define IDM_DLGVIEWREGMETHODS           32863
#define ID_EDIT_SCREEN_TO_CB            32864
#define ID_DUMPCAPTUREPREVIEW           32865
#define ID_DUMPCAPTUREPREVIEWSETUP      32866
#define ID_DUMPCAPTURECLEAR             32867
#define ID_DUMPCAPTURESTARTSTOP         32868
#define ID_DUMPCAPTURESTOP              32869
#define ID_DUMPSTOP                     32870
#define IDS_SINGLETERMWARNING           32871
#define CG_IDS_SOCKETS_INIT_FAILED      32872
#define IDM_SEPARATEVIEWMODE            32873
#define IDM_SEPARATEVIEWINFRAME         32874
#define IDM_DLGVIEWIMAGELISTS           32875
#define IDM_TERMCAP                     32876
#define IDM_ENABLECONTEXTMENU           32877
#define IDM_EDITCONTEXTMENU             32878
#define ID_FULLCONTEXTMENU              32879
#define IDM_DLGVIEWCMMETHODS            32880
#define IDM_STATISTIC                   32881
#define IDM_DLGVIEWSYSMETHODS           32882
#define IDM_TERMCAPAV                   32883
#define IDS_GPOLEEXEPTION1010           32884
#define ID_SCRSIZE79X24                 32885
#define ID_SCRSIZE79X25                 32886
#define ID_SCRSIZE80X24                 32887
#define ID_SCRSIZE80X25                 32888
#define ID_SCRSIZE80X32                 32889
#define ID_SCRSIZE80X46                 32890
#define ID_SCRSIZE88X24                 32891
#define ID_SCRSIZE88X32                 32892
#define ID_SCRSIZE88X72                 32893
#define ID_SCRSIZE128X24                32894
#define ID_SCRSIZE128X25                32895
#define ID_SCRSIZE128X36                32896
#define ID_SCRSIZE128X46                32897
#define ID_SCRSIZE128X60                32898
#define ID_SCRSIZE128X72                32899
#define ID_SCRSIZE132X24                32900
#define ID_SCRSIZE132X25                32901
#define ID_SCRSIZE132X36                32902
#define ID_SCRSIZE132X46                32903
#define ID_SCRSIZE132X60                32904
#define ID_SCRSIZE132X72                32905
#define ID_SCRSIZECUSTOM                32906
#define ID_SCREENSIZE                   32907
#define ID_BUTTON32908                  32908
#define ID_WINDOWGRID                   32909
#define ID_SLAVEPRINTPAGESETUP          32910
#define ID_PAGESETUP                    32911

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        257
#define _APS_NEXT_COMMAND_VALUE         32912
#define _APS_NEXT_CONTROL_VALUE         1573
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
